import {escapeText as esc,statusLabel,formatTime,formatMetric} from './customer-display.mjs';
const link=(text,page,kind='')=>`<button data-action="home-data" data-page="${page}" ${kind?`data-kind="${kind}"`:''}>${text} ↗</button>`;
const action=(text,kind,id)=>`<button data-action="${kind}" data-id="${id}">${text}</button>`;
const ask=text=>`<button data-assistant-prompt="${esc(text)}">问这项工作</button>`;
const count=v=>typeof v==='number'&&Number.isFinite(v)&&v>=0?v:null;
function metric(label,value,note,page,kind=''){return `<button class="home-metric" data-action="home-data" data-page="${page}" ${kind?`data-kind="${kind}"`:''}><span>${label}</span><strong>${esc(formatMetric(count(value)))}</strong><small>${esc(note)}</small></button>`;}
function bars(items){const maximum=Math.max(1,...items.map(v=>v[1]));return items.map(([label,n])=>`<div class="home-bar"><span>${esc(label)}</span><div><i style="width:${n/maximum*100}%"></i></div><b>${n}</b></div>`).join('');}
export function homeView(data){
 if(!data)return '<h2>本期要点</h2><p>正在读取当前网站的稿件、关键词、页面检查与服务进度。</p>';
 const confirmed=data.deliveries.filter(v=>v.workflow_status==='awaiting_customer_confirmation'&&(v.allowed_actions.confirm_as_customer===true||v.allowed_actions.confirm_as_advisor_proxy===true));
 const advisor=data.deliveries.filter(v=>v.permission_basis?.active_site_advisor_assignment===true&&['edit_content','review','start_publication'].some(k=>v.allowed_actions[k]===true));
 const tasks=data.executions?.items??[],phases=data.service?.phases??{},site=phases['SEO-A02']?.facts??{},publication=phases['SEO-A05']?.facts??{};
 const keywords=data.keywords?.items??[],pages=data.pages?.items??[];
 const validRank=v=>!v.rank_is_stale&&typeof v.latest_rank==='number'&&Number.isFinite(v.latest_rank)&&v.latest_rank>0;
 const bands=[['前 3 名',keywords.filter(v=>validRank(v)&&v.latest_rank<=3).length],['第 4–10 名',keywords.filter(v=>validRank(v)&&v.latest_rank>3&&v.latest_rank<=10).length],['10 名以后',keywords.filter(v=>validRank(v)&&v.latest_rank>10).length],['待更新 / 无名次',keywords.filter(v=>!validRank(v)).length]];
 const contentBands=['planned','drafting','review','ready','published'].map(s=>[statusLabel(s),data.contents.items.filter(v=>v.status===s).length]);
 return `<section id="summary" class="home-summary"><div class="section-head"><div><small>SEO · 当前客户与网站</small><h2>本期要点</h2></div><button data-action="refresh">刷新概览</button></div><p class="meta">当前存量概览 · 读取于 ${esc(formatTime(data.readAt))} · 各项观测时间见明细</p><div class="point"><span class="type">待办</span>本次核对 ${data.deliveries.length} 篇稿件，<b>${confirmed.length} 篇</b>可由当前身份确认。${link('查看稿件','内容')}${ask('现在需要我做什么？')}</div><div class="point"><span class="type">进度</span>已登记 <b>${esc(formatMetric(data.executions?.total))} 项</b>服务任务，完成情况以任务记录为准。${link('查看进度','进度')}</div><div class="point"><span class="type risk">关注</span>${count(site.pages_with_issues)!==null?`<b>${site.pages_with_issues} 个</b>页面记录有待处理问题。`:'网站检查情况可在页面明细中核对。'}${link('查看页面','数据','pages')}${ask('网站有哪些问题？')}</div>${data.readFailures?.length?`<p class="home-alert">部分数据未读到：${data.readFailures.map(esc).join('、')}。已读数据继续展示，可刷新重试。</p>`:''}<details><summary>数据范围与依据</summary><p>当前网站存量，不是某一自然周的增量。关键词预览最多20条，稿件状态覆盖本次${data.contents.items.length}篇；总量与局部分布分别标注。搜索点击与访问趋势未接入本首页，未用稿件数替代。</p><p>单项数据时间：页面检查 ${esc(formatTime(phases['SEO-A02']?.as_of))} · 排名观测 ${esc(formatTime(phases['SEO-A03']?.as_of))} · 发布记录 ${esc(formatTime(phases['SEO-A05']?.as_of))}</p></details></section>
 <section class="summary-grid home-kpis" aria-label="关键数据">${metric('网站稿件',data.contents.total,'全部状态','内容')}${metric('启用关键词',data.keywords?.total,'百度 · 电脑 · 当前筛选','数据','keywords')}${metric('网站页面',data.pages?.total,'当前网站登记页面','数据','pages')}${metric('待处理页面',site.pages_with_issues,'来自网站检查汇总','数据','pages')}${metric('发布记录',data.publications?.total,'登记记录，不等于已核验','交付记录')}${metric('已核验发布',publication.verified_publications,'来自发布核验汇总','交付记录')}</section>
 <section class="home-block"><div class="section-head"><h3>任务与待办</h3><span class="counts">本次核对待确认 ${confirmed.length} · 顾问待处理 ${advisor.length}</span></div><p class="meaning-note">仅覆盖本次 ${data.deliveries.length} 篇；本次核对列表前 ${data.contents.items.length} 篇；${data.contents.total>data.contents.items.length?'还有稿件未核对，请进入内容列表查看。':'已覆盖当前列表。'}${data.failed?'有 '+data.failed+' 篇交付状态未读到。':''}</p>${confirmed.map(v=>`<div class="task-item"><div class="task-content"><b>${esc(v.content.title)}</b><p>等待确认 v${v.content.version_count} · 确认后仍需安排发布</p></div>${action('查看并确认','delivery',v.content.id)}</div>`).join('')||'<p>本次已核对稿件中，没有可由您确认的稿件。</p>'}${advisor.map(v=>`<div class="task-item"><div class="task-content"><b>${esc(v.content.title)}</b><p>顾问处理 · ${esc(statusLabel(v.workflow_status))}</p></div>${action('处理稿件','delivery',v.content.id)}</div>`).join('')}${link('查看全部稿件','内容')}</section>
 <section class="home-panels"><article class="home-block"><div class="section-head"><h3>关键词表现</h3>${link('全部关键词','数据','keywords')}</div><p class="meta">百度 · 电脑 · 本页 ${keywords.length} / ${esc(formatMetric(data.keywords?.total))} 词</p>${data.keywords?bars(bands):'<p class="empty">关键词数据未取得</p>'}<div class="home-keywords">${keywords.slice(0,5).map(v=>`<div><span>${esc(v.keyword)}</span><b>${validRank(v)?v.latest_rank+' 名':'待更新 / 无名次'}</b><small>${validRank(v)&&Number.isFinite(v.rank_delta)?v.rank_delta>0?'↑ '+v.rank_delta:v.rank_delta<0?'↓ '+Math.abs(v.rank_delta):'持平':'—'}</small></div>`).join('')}</div>${ask('关键词表现怎么样？')}</article><article class="home-block"><div class="section-head"><h3>内容制作</h3>${link('全部稿件','内容')}</div><p class="meta">本次列表 ${data.contents.items.length} / ${data.contents.total} 篇 · 非全量状态统计</p>${bars(contentBands)}<div class="home-flow"><span>制作</span><i>→</i><span>顾问复核</span><i>→</i><span>客户确认</span><i>→</i><span>安排发布</span></div><p class="meta">确认稿件与实际发布分别记录。</p></article></section>
 <section class="home-panels"><article class="home-block"><div class="section-head"><h3>最近进度</h3>${link('全部进度','进度')}</div><p class="meta">最近读取的 ${tasks.length} / ${esc(formatMetric(data.executions?.total))} 项</p>${tasks.map(t=>`<div class="task-item"><div class="task-content"><b>${esc(t.title)}</b><p>${esc(statusLabel(t.params?.phase,'phase'))}</p><small>${esc(formatTime(t.updated_at))}</small></div>${action('查看','execution-detail',t.id)}</div>`).join('')||'<p>尚无可展示的任务记录。</p>'}</article><article class="home-block"><div class="section-head"><h3>网站检查</h3>${link('页面明细','数据','pages')}</div><p class="meta">本页 ${pages.length} / ${esc(formatMetric(data.pages?.total))} 页</p>${pages.slice(0,4).map(p=>`<div class="home-page-row"><b>${esc(p.title||'未命名页面')}</b><span>${p.last_error?'检查未成功':({healthy:'检查正常',verified:'已复查',needs_fix:'需要修改',pending:'待检查'})[p.status]||'查看检查结果'}</span><small>${esc(formatTime(p.last_checked_at))}</small></div>`).join('')||'<p>尚无可展示的页面检查记录。</p>'}${link('发布与检查依据','交付记录')}</article></section>`;
}
