import {escapeText as esc,statusLabel,formatTime,formatMetric} from './customer-display.mjs';
const action=(text,kind,id)=>`<button data-action="${kind}" data-id="${id}">${text}</button>`;
export function homeView(data) {
  if(!data)return '<h2>首页</h2><p>正在读取当前网站的稿件与服务进度。</p>';
  const confirmed=data.deliveries.filter(v=>v.workflow_status==='awaiting_customer_confirmation'&&(v.allowed_actions.confirm_as_customer===true||v.allowed_actions.confirm_as_advisor_proxy===true));
  const advisor=data.deliveries.filter(v=>v.permission_basis?.active_site_advisor_assignment===true&&['edit_content','review','start_publication'].some(k=>v.allowed_actions[k]===true));
  const tasks=data.executions?.items??[];
  return `<h2>今天的服务概览</h2><p>先看需要您处理的稿件，再查看顾问的服务进度。</p><div class="summary-grid"><article><small>当前网站稿件</small><strong>${esc(formatMetric(data.contents.total))}</strong><span>全部状态</span></article><article><small>已核对稿件中的待确认</small><strong>${confirmed.length}</strong><span>仅覆盖本次 ${data.deliveries.length} 篇</span></article><article><small>已登记服务任务</small><strong>${esc(formatMetric(data.executions?.total))}</strong><span>${data.executions?'当前授权范围':'未取得进度读取权限'}</span></article></div><section><h3>需要我处理</h3><p class="meaning-note">本次核对列表前 ${data.contents.items.length} 篇交付状态；${data.contents.total>data.contents.items.length?'还有稿件未核对，请进入内容列表逐页查看。':'已覆盖当前列表中的全部稿件。'}${data.failed?'有 '+data.failed+' 篇读取失败，请重试后核对。':''}</p>${confirmed.map(v=>`<div class="task-item"><div><b>${esc(v.content.title)}</b><p>等待确认 v${v.content.version_count} · 确认后仍需安排发布</p></div>${action('查看并确认','delivery',v.content.id)}</div>`).join('')||'<p>本次已核对稿件中，没有可由您确认的稿件。</p>'}${advisor.length?`<h4>顾问待处理</h4>${advisor.map(v=>`<div class="task-item"><div><b>${esc(v.content.title)}</b><p>${esc(statusLabel(v.workflow_status))}</p></div>${action('处理稿件','delivery',v.content.id)}</div>`).join('')}`:''}</section><section><h3>最近进度</h3><p class="meaning-note">服务端当前返回的前 ${tasks.length} 条任务；完成以留存的任务证据为准。</p>${tasks.map(t=>`<div class="task-item"><div><b>${esc(t.title)}</b><p>${esc(statusLabel(t.params.phase,'phase'))} · ${esc(formatTime(t.updated_at))}</p></div>${action('查看进度','execution-detail',t.id)}</div>`).join('')||'<p>当前未读取到服务任务。</p>'}</section><div class="actions"><button data-action="page" data-page="内容">查看全部稿件</button><button data-action="refresh">刷新概览</button></div>`;
}
