"""Real PostgreSQL checks for content-generation reservation and recovery."""

import asyncio
import os
from datetime import datetime, timedelta
from types import SimpleNamespace as NS
from unittest.mock import patch
from uuid import uuid4

import pytest
from fastapi import BackgroundTasks, HTTPException
from sqlalchemy import func, select, text
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine

from app.geo.content.async_jobs import (
    KIND_GENERATE,
    create_job,
    reconcile_stale_job,
    request_cancel,
)
from app.geo.content.routes import generate_task_article
from app.models import GeoAsyncJob, GeoContentTask


pytestmark = pytest.mark.skipif(
    not os.getenv("GEO_TEST_POSTGRES_URL"),
    reason="requires isolated PostgreSQL",
)


async def _prepare_database():
    url = os.environ["GEO_TEST_POSTGRES_URL"]
    schema = "geo_generation_test_" + uuid4().hex
    admin = create_async_engine(url)
    tables = [
        "tenants",
        "geo_prompts",
        "geo_facts",
        "geo_content_tasks",
        "geo_task_facts",
        "geo_async_jobs",
    ]
    async with admin.begin() as connection:
        await connection.execute(text(f'CREATE SCHEMA "{schema}"'))
        for table in tables:
            await connection.execute(
                text(
                    f'CREATE TABLE "{schema}"."{table}" '
                    f'AS SELECT * FROM public."{table}" WITH NO DATA'
                )
            )
        await connection.execute(
            text(
                f'ALTER TABLE "{schema}".geo_async_jobs '
                "ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"
            )
        )
        await connection.execute(
            text(f'INSERT INTO "{schema}".tenants(id,name) VALUES (7,\'示例客户\')')
        )
        await connection.execute(
            text(
                f'INSERT INTO "{schema}".geo_prompts(id,tenant_id,question) '
                "VALUES (3,7,'产品特点是什么？')"
            )
        )
        await connection.execute(
            text(
                f'INSERT INTO "{schema}".geo_content_tasks'
                "(id,tenant_id,prompt_id,title,status,brief,updated_at) VALUES "
                "(12,7,3,'并发生成测试','editing',CAST(:brief AS jsonb),now())"
            ),
            {
                "brief": '{"industry":"工业传动","audience":"采购",'
                '"intent":"scenario","content_type":"thought_leadership",'
                '"cta":"咨询选型"}',
            },
        )
        for ident in (1, 2, 3):
            await connection.execute(
                text(
                    f'INSERT INTO "{schema}".geo_facts'
                    "(id,tenant_id,title,statement,fact_type,source_name,source_url,"
                    "trust_level,status,expires_at) VALUES "
                    "(:id,7,:title,:statement,'product','已核验资料',:url,"
                    "'verified','active','2099-01-01')"
                ),
                {
                    "id": ident,
                    "title": f"产品说明 {ident}",
                    "statement": f"示例产品特性 {ident} 已由资料确认。",
                    "url": f"https://example.invalid/source/{ident}",
                },
            )
            await connection.execute(
                text(
                    f'INSERT INTO "{schema}".geo_task_facts'
                    "(task_id,fact_id,sort_order) VALUES (12,:id,:id)"
                ),
                {"id": ident},
            )
    engine = create_async_engine(
        url,
        connect_args={
            "server_settings": {
                "search_path": schema,
                "statement_timeout": "15000",
            }
        },
    )
    return admin, engine, schema, tables


async def _cleanup(admin, engine, schema, tables):
    await engine.dispose()
    async with admin.begin() as connection:
        for table in reversed(tables):
            await connection.execute(text(f'DROP TABLE "{schema}"."{table}"'))
        await connection.execute(text(f'DROP SCHEMA "{schema}"'))
    await admin.dispose()


def _ctx():
    return NS(user_id=9, ensure_tenant=lambda _: None)


def test_concurrent_generate_requests_create_exactly_one_job():
    async def run():
        admin, engine, schema, tables = await _prepare_database()
        sessions = async_sessionmaker(engine, expire_on_commit=False)
        first_entered = asyncio.Event()
        release_first = asyncio.Event()
        pids = {}
        original_create_job = create_job

        async def delayed_create_job(session, **kwargs):
            if not first_entered.is_set():
                first_entered.set()
                await asyncio.wait_for(release_first.wait(), 10)
            return await original_create_job(session, **kwargs)

        async def call(label):
            async with sessions() as session:
                pids[label] = await session.scalar(text("SELECT pg_backend_pid()"))
                try:
                    return await generate_task_article(
                        12,
                        tenant_id=7,
                        run_async=True,
                        background_tasks=BackgroundTasks(),
                        ctx=_ctx(),
                        session=session,
                    )
                except HTTPException as exc:
                    return exc

        try:
            with patch(
                "app.geo.content.async_jobs.create_job",
                side_effect=delayed_create_job,
            ):
                first = asyncio.create_task(call("first"))
                await asyncio.wait_for(first_entered.wait(), 10)
                second = asyncio.create_task(call("second"))
                try:
                    for _ in range(100):
                        if "second" in pids:
                            async with admin.connect() as connection:
                                blockers = await connection.scalar(
                                    text("SELECT pg_blocking_pids(:pid)"),
                                    {"pid": pids["second"]},
                                )
                            if pids["first"] in blockers:
                                break
                        await asyncio.sleep(0.05)
                    else:
                        raise AssertionError("second generator did not wait on task row lock")
                    release_first.set()
                    results = await asyncio.wait_for(
                        asyncio.gather(first, second), 15
                    )
                finally:
                    release_first.set()
                    for worker in (first, second):
                        if not worker.done():
                            worker.cancel()
                    await asyncio.gather(first, second, return_exceptions=True)

            assert sum(isinstance(result, HTTPException) for result in results) == 1
            rejected = next(result for result in results if isinstance(result, HTTPException))
            assert rejected.status_code == 409
            async with sessions() as session:
                assert await session.scalar(select(func.count(GeoAsyncJob.id))) == 1
                assert (await session.get(GeoContentTask, 12)).status == "generating"
        finally:
            await _cleanup(admin, engine, schema, tables)

    asyncio.run(run())


def test_job_creation_failure_rolls_back_reservation_and_allows_retry():
    async def run():
        admin, engine, schema, tables = await _prepare_database()
        sessions = async_sessionmaker(engine, expire_on_commit=False)

        async def fail_after_flush(session, **kwargs):
            row = GeoAsyncJob(status="pending", **kwargs)
            session.add(row)
            await session.flush()
            raise RuntimeError("simulated job insert failure")

        try:
            with pytest.raises(RuntimeError, match="simulated job insert failure"):
                async with sessions() as session:
                    with patch(
                        "app.geo.content.async_jobs.create_job",
                        side_effect=fail_after_flush,
                    ):
                        await generate_task_article(
                            12,
                            tenant_id=7,
                            run_async=True,
                            background_tasks=BackgroundTasks(),
                            ctx=_ctx(),
                            session=session,
                        )

            async with sessions() as session:
                assert (await session.get(GeoContentTask, 12)).status == "editing"
                assert await session.scalar(select(func.count(GeoAsyncJob.id))) == 0

            async with sessions() as session:
                result = await generate_task_article(
                    12,
                    tenant_id=7,
                    run_async=True,
                    background_tasks=BackgroundTasks(),
                    ctx=_ctx(),
                    session=session,
                )
                assert result["job"]["status"] == "pending"
        finally:
            await _cleanup(admin, engine, schema, tables)

    asyncio.run(run())


@pytest.mark.parametrize("recovery", ["cancel", "stale"])
def test_generation_reservation_is_released_by_existing_recovery(recovery):
    async def run():
        admin, engine, schema, tables = await _prepare_database()
        sessions = async_sessionmaker(engine, expire_on_commit=False)
        try:
            async with sessions() as session:
                task = await session.get(GeoContentTask, 12)
                task.status = "generating"
                job = GeoAsyncJob(
                    tenant_id=7,
                    kind=KIND_GENERATE,
                    status="pending",
                    ref_type="content_task",
                    ref_id=12,
                    request_meta={},
                    created_by=9,
                    created_at=datetime.utcnow() - timedelta(days=1),
                )
                session.add(job)
                await session.commit()
                await session.refresh(job)
                if recovery == "cancel":
                    await request_cancel(session, job)
                else:
                    await reconcile_stale_job(session, job)

            async with sessions() as session:
                task = await session.get(GeoContentTask, 12)
                job = await session.scalar(select(GeoAsyncJob))
                assert task.status == "editing"
                assert job.status == ("cancelled" if recovery == "cancel" else "failed")
        finally:
            await _cleanup(admin, engine, schema, tables)

    asyncio.run(run())
