<script setup>
import { computed } from 'vue'
import brandLogo from '../../assets/g-snipers-purple-logo.png'
import { slideReportModel } from './diagnosticSlideModel.js'
import { reportDate } from './diagnosticReportModel.js'
import { statusLabel } from './diagnosticFindingState.js'
const props = defineProps({ audit: { type: Object, required: true }, brand: Object, pageSpeed: Object })
const report = computed(() => slideReportModel(props.audit, props.brand, props.pageSpeed))
const short = (value, length = 100) => { const s = String(value ?? ''); return s.length > length ? s.slice(0, length) + '…' : s }
const answerSegments = text => text.split(/(\*\*[^*]+\*\*)/g).filter(Boolean).map(part => ({ bold: part.startsWith('**') && part.endsWith('**'), text: part.startsWith('**') && part.endsWith('**') ? part.slice(2, -2) : part }))
const severity = value => ({ critical:'阻断', high:'高', medium:'中', low:'低' }[value] || '待核查')
const metric = index => report.value.external[index]?.value || '未检测'
const mention = row => row.explicitMention === true ? '出现明确品牌名' : row.explicitMention === false ? '未出现明确品牌名' : '品牌名称未确认'
const signalPoints = (radius = 150, values = null) => report.value.dimensions.map((d,i) => { const a = (-90 + i * 60) * Math.PI / 180; const r = radius * (values ? (d.score ?? 0) / 100 : 1); return `${200 + Math.cos(a) * r},${180 + Math.sin(a) * r}` }).join(' ')
const suggestionRank = code => ({ faq:0, freshness:1, robots:2, llms:3 }[code] ?? 4)
const priorities = computed(() => [...report.value.failed].sort((a,b) => suggestionRank(a.code) - suggestionRank(b.code)).slice(0,4))
</script>

<template>
  <article class="diagnostic-print-report" aria-label="网站诊断报告打印正文">
    <section v-for="(slide, pageIndex) in report.slides" :key="pageIndex" class="dp-slide" :class="`dp-page-${slide.kind}`" :data-page="pageIndex + 1">
      <template v-if="slide.kind === 'cover' || slide.kind === 'divider'">
        <div class="dp-brand"><img :src="brandLogo" alt=""><b>G-SNIPERS<span v-if="slide.kind === 'cover'"> 获客狙击手</span></b></div>
        <div v-if="slide.kind === 'cover'" class="dp-orbits" aria-hidden="true"></div><div v-else class="dp-chapter-number">{{ slide.number }}</div>
        <div class="dp-title-block">
          <p class="dp-kicker">{{ slide.kind === 'cover' ? 'WEBSITE DIAGNOSTIC REPORT' : `${slide.number} / ${slide.english}` }}</p>
          <h1 v-if="slide.kind === 'cover'">{{ short(report.name, 34) }}<br>网站诊断报告</h1>
          <h1 v-else>{{ slide.title }}</h1>
          <p class="dp-subtitle">{{ slide.kind === 'cover' ? 'SEO 技术基础与 GEO / AI 搜索诊断' : slide.subtitle }}</p>
          <p v-if="slide.kind === 'cover'" class="dp-url">{{ short(report.website, 160) }}</p>
        </div>
      </template>
      <template v-else>
        <header v-if="slide.title" class="dp-heading"><div><p class="dp-kicker">{{ slide.english }}</p><h2>{{ slide.title }}</h2></div><div class="dp-brand"><img :src="brandLogo" alt=""><b>获客狙击手<small>G-SNIPERS</small></b></div></header>
        <main :class="{ 'dp-with-heading': slide.title }">
          <div v-if="slide.kind === 'overview'" class="dp-overview">
            <aside class="dp-score-column"><p class="dp-kicker">AI 搜索准备度 · 基础规则</p><div class="dp-gauge"><svg viewBox="0 0 240 222"><defs><linearGradient id="dp-gauge-green" x1="0" y1="1" x2="1" y2="0"><stop stop-color="#06b587"/><stop offset="1" stop-color="#9de883"/></linearGradient></defs><circle class="dp-gauge-track" cx="120" cy="111" r="78" pathLength="100"/><circle v-if="report.score !== null" class="dp-gauge-value" cx="120" cy="111" r="78" pathLength="100" :stroke-dasharray="`${report.score * .75} 100`"/></svg><div><strong>{{ report.score ?? '—' }}</strong><small v-if="report.score !== null">/100</small></div></div><span class="dp-tag">{{ report.legacy ? '历史记录 · 建议复检' : report.score === null ? '未检测' : report.score >= 80 ? '基础较好' : '基础阶段' }}</span><p class="dp-muted">{{ report.evaluated.length }} 项已评估 · {{ report.unavailable.length }} 项未检测</p><div class="dp-composition"><div v-for="label in ['SEO 基础能力','GEO 理解能力','AI 引用准备度']" :key="label"><span>{{ label }}</span><b>未检测</b><i></i></div><small>三个分项暂无独立综合评分；总分基于本次基础规则。</small></div></aside>
            <div class="dp-overview-copy"><p class="dp-kicker">AI DIAGNOSTIC RESULT</p><h2>官网 AI 搜索诊断结果</h2><p class="dp-lead">已评估 {{ report.evaluated.length }} 项规则，{{ report.passed }} 项通过，{{ report.failed.length }} 项待完善。<br>根据本次检测证据，逐项完善网站技术基础与内容结构。</p><div class="dp-risk"><b>优先关注</b><span>{{ report.high ? `当前有 ${report.high} 项高优先级问题，建议先处理并复检。` : '优先核对未通过项与待补充检测，再确认下一步优化方向。' }}</span></div><b class="dp-muted">主要发现</b><div class="dp-grid dp-three dp-findings"><article v-for="item in report.failed.slice(0,3)" :key="item.code" class="dp-card dp-warm"><span class="dp-priority">{{ severity(item.severity) }}优先级</span><h3>{{ short(item.title, 30) }}</h3><p>{{ short(item.recommendation, 90) }}</p></article><p v-if="!report.failed.length">本次已评估规则未发现明确失败项；未检测项需补充验证。</p></div><div class="dp-proof"><div class="dp-brand"><img :src="brandLogo" alt=""><b><small>PROFESSIONAL TEAM REVIEW</small>G-Snipers 专业诊断报告</b></div><p>{{ report.scoreNote }}</p><div class="dp-proof-points"><span>✓ 基于本次网站检测证据</span><span>✓ 保留规则与来源</span><span>✓ 未检测不作确定结论</span></div></div></div>
          </div>

          <div v-else-if="slide.kind === 'foundation'" class="dp-grid dp-three dp-fill">
            <article class="dp-card"><h3>{{ report.findings.length }} 项基础规则</h3><small>FOUNDATION CHECKS</small><div class="dp-grid dp-two dp-stats"><div class="dp-stat"><label>通过项</label><strong>{{ report.passed }}</strong><small>已达到检测要求</small></div><div class="dp-stat dp-warm"><label>待优化项</label><strong>{{ report.failed.length }}</strong><small>按证据逐项完善</small></div></div><div class="dp-stat dp-rose"><label>高优先级问题</label><strong>{{ report.high }}</strong><small>建议优先处理</small></div><div class="dp-bar"><i :style="{width: `${report.passRate ?? 0}%`}"></i></div><p><b>{{ report.passRate === null ? '未检测' : `${report.passRate}%` }}</b> 的已评估规则通过</p><p class="dp-muted">{{ report.evaluated.length }} 项有明确结果；{{ report.unavailable.length }} 项未检测。评分口径详见附录。</p></article>
            <article class="dp-card"><h3>AI 搜索健康度雷达</h3><small>AI SEARCH HEALTH RADAR</small><svg class="dp-radar" viewBox="0 0 400 380"><polygon v-for="r in [40,80,120,150]" :key="r" :points="signalPoints(r)" fill="none" stroke="#cce6df" stroke-width="2"/><polygon v-if="report.dimensions.every(d => d.score !== null)" :points="signalPoints(150, true)" fill="#16b78e33" stroke="#10a887" stroke-width="3"/><text v-for="(d,i) in report.dimensions" :key="d.label" :x="200 + Math.cos((-90+i*60)*Math.PI/180)*175" :y="183 + Math.sin((-90+i*60)*Math.PI/180)*175" text-anchor="middle" font-size="12" fill="#777">{{ d.label }}</text></svg><p class="dp-muted">{{ report.dimensions.some(d => d.score === null) ? '部分维度未检测，暂不绘制完整雷达。' : '六维规则信号 · 非真实 AI 推荐率' }}</p></article>
            <article class="dp-card"><h3>核心指标</h3><small>KEY METRICS</small><div class="dp-grid dp-two dp-stats"><div class="dp-stat"><label>规则通过</label><strong>{{ report.passed }}<small>/{{ report.evaluated.length }}</small></strong></div><div class="dp-stat"><label>高优先问题</label><strong>{{ report.high }}</strong></div><div class="dp-stat"><label>{{ report.pages.length ? '抽样页面' : '内容单元' }}</label><strong>{{ report.pages.length ? report.pages.length : (report.snapshot.content_units ?? '未记录') }}</strong></div><div class="dp-stat"><label>待补充检测</label><strong>{{ report.unavailable.length }}</strong></div></div><div class="dp-stat"><label>百度收录量</label><strong class="dp-word">{{ metric(0) }}</strong><small>{{ short(report.external[0].note, 55) }}</small></div></article>
          </div>

          <div v-else-if="slide.kind === 'signals'" class="dp-signals-layout">
            <article class="dp-card"><h3>六维诊断信号</h3><small>READINESS SIGNALS</small><div class="dp-signal-grid"><div v-for="d in report.dimensions" :key="d.label"><span>{{ d.label }}</span><i class="dp-bar"><i :style="{ width: `${d.score ?? 0}%` }"></i></i><b>{{ d.score ?? '未检测' }}</b></div></div></article>
            <article class="dp-card"><h3>本次抽样页面</h3><small>CURRENT SAMPLE</small><div class="dp-current-sample"><i>✓</i><div><b>{{ short(audit.page_title || report.website, 50) }}</b><small>{{ report.scope }}</small></div><span>已完成</span></div><p v-if="report.pages.length" class="dp-muted">完整抽样页面及逐页证据见附录。</p></article>
            <article class="dp-card dp-suggestion-panel"><h3>本次优化建议</h3><small>CURRENT OPTIMIZATION SUGGESTIONS</small><div class="dp-suggestions"><div v-for="item in priorities" :key="item.code"><i>✓</i><section><b>{{ short(item.title, 30) }}</b><p>{{ short(item.recommendation, 95) }}</p></section></div><p v-if="!priorities.length">保持已通过设置，补充未检测项，并在网站更新后复检。</p></div></article>
          </div>

          <div v-else-if="slide.kind === 'seo'" class="dp-seo-panel"><div class="dp-seo-heading"><p class="dp-kicker">02 / SEO DIAGNOSIS</p><h2>SEO 诊断</h2><p>分析网站搜索基础能力、关键词覆盖、索引质量以及网站访问体验。</p></div><div class="dp-seo-hero"><aside><p class="dp-kicker">SEO HEALTH SCORE</p><h3>SEO 健康度</h3><strong>{{ report.seo.scoreText }}</strong><span class="dp-tag">{{ report.seo.scoreLabel }}</span><p class="dp-muted">{{ report.seo.scoreNote }}</p></aside><div class="dp-seo-copy"><p class="dp-kicker">SEO 健康总览</p><h2>{{ report.seo.headline[0] }}<br><em>{{ report.seo.headline[1] }}</em></h2><p>{{ report.seo.description }}</p><div class="dp-chips"><span v-for="tag in report.seo.tags" :key="tag">{{ tag }}</span></div></div><div class="dp-facts"><div v-for="fact in report.seo.facts" :key="fact.label"><span>{{ fact.label }}</span><strong>{{ fact.value }}<small v-if="fact.unit">{{ fact.unit }}</small></strong><small>{{ fact.note }}</small></div></div></div></div>

          <div v-else-if="slide.kind === 'metrics'" class="dp-metrics-panel"><div class="dp-section-top"><div><p class="dp-kicker">CORE SIGNALS</p><h2>搜索可见性核心指标</h2></div><p>判断官网是否能被搜索引擎发现、理解，并覆盖真实业务需求。</p></div><div class="dp-grid dp-four dp-core-cards"><article class="dp-card"><span class="dp-metric-icon">⌕</span><h3>搜索引擎索引规模</h3><strong class="dp-big-word">{{ metric(0) }}</strong><p>索引数量代表搜索引擎发现页面规模，不代表有效商业页面数量。</p><small>{{ short(report.external[0].note, 80) }}</small></article><article class="dp-card"><span class="dp-metric-icon">K</span><h3>关键词覆盖</h3><div class="dp-mini-facts"><div v-for="i in [1,2]" :key="i"><small>{{ report.external[i].label }}</small><b>{{ metric(i) }}</b></div></div><p>关键词结果来自对应终端数据。需取得真实词表后，再分析品牌词、产品词与行业词结构。</p><small>查询来源与时间见附录。</small></article><article class="dp-card"><span class="dp-metric-icon">W</span><h3>百度综合权重</h3><div class="dp-mini-facts"><div v-for="i in [4,5]" :key="i"><small>{{ report.external[i].label }}</small><b>{{ metric(i) }}</b></div></div><p>观察网站在百度 PC 与移动搜索中的表现。第三方权重不等于实际流量。</p><small>{{ short(report.external[4].note, 80) }}</small></article><article class="dp-card"><span class="dp-metric-icon">✓</span><h3>网站体验健康</h3><strong class="dp-big-word">{{ report.performanceRows[0].value }}</strong><small>Performance</small><div class="dp-cwv"><div v-for="m in report.performanceRows.slice(1)" :key="m.label"><b>{{ m.label }}</b><span>{{ m.value }}</span></div></div><small>{{ short(report.performance.methodology || report.performance.reason || '本次未取得可用性能数据', 90) }}</small></article></div></div>

          <div v-else-if="slide.kind === 'analysis'" class="dp-analysis-layout"><div class="dp-grid dp-two"><article class="dp-card"><p class="dp-kicker">INDEX QUALITY</p><h2>索引质量分析</h2><div class="dp-data-row"><span>百度索引</span><b>{{ metric(0) }}</b></div><div class="dp-data-row"><span>网站实际页面总量</span><b>未检测</b></div><div class="dp-explain"><b>分析</b><span>{{ report.seo.indexAnalysis }}</span></div><div class="dp-explain dp-rose"><b>待核查</b><span>参数页面、重复 URL、历史页面及低价值索引。</span></div><div class="dp-explain dp-mint"><b>优化建议</b><span>取得完整页面清单后，核对核心产品与解决方案页面。</span></div></article><article class="dp-card"><p class="dp-kicker">KEYWORD OPPORTUNITY</p><h2>关键词机会分析</h2><div v-for="label in ['品牌词覆盖','产品词覆盖','行业词覆盖']" :key="label" class="dp-data-row"><span>{{ label }}</span><b>未检测</b></div><div class="dp-explain"><b>诊断</b><span>{{ report.seo.keywordAnalysis }}</span></div><div class="dp-explain dp-mint"><b>优化方向</b><span>结合产品页面、行业方案、应用案例和专业知识制定内容计划。</span></div></article></div><article class="dp-roadmap"><p class="dp-kicker">PRIORITY ROADMAP</p><h2>SEO 优化优先级</h2><div class="dp-grid dp-three"><div v-for="(text,i) in ['核对技术检测问题','补充搜索表现数据','制定页面与内容计划']" :key="text"><b class="dp-step">{{ String(i+1).padStart(2,'0') }}</b><section><h3>{{ text }}</h3><p>{{ ['先处理明确未通过项，再复检页面基础设置。','取得索引记录、关键词样本和性能结果。','以检测证据和真实搜索需求确定投入顺序。'][i] }}</p></section></div></div></article></div>

          <template v-else-if="slide.kind === 'sample'"><div class="dp-grid dp-three dp-sample-stats"><div class="dp-stat"><label>明确品牌名提及率</label><strong>{{ report.explicitRate === null ? '未检测' : `${report.explicitRate}%` }}</strong><small>{{ short(report.names.join(' / ') || '品牌名称未确认', 70) }}</small></div><div class="dp-stat"><label>明确提及</label><strong>{{ report.explicitRate === null ? '未检测' : `${report.explicitCount} / ${report.samples.length}` }}</strong><small>仅本次保存回答</small></div><div class="dp-stat"><label>抽样平台</label><strong class="dp-word">{{ report.sample.platform || '未记录' }}</strong><small>{{ report.sample.model || '未记录' }}</small></div></div><div class="dp-grid dp-three dp-sample-cards"><article v-for="(row,i) in slide.rows" :key="i" class="dp-card"><h3>问题 {{ report.samples.indexOf(row)+1 }}</h3><span class="dp-tag">{{ mention(row) }}</span><h3 class="dp-question">{{ short(row.question, 70) }}</h3><p>{{ short(row.response, 100) }}</p><small>回答节选；完整原文见附录三。</small></article></div><p v-if="!slide.rows.length" class="dp-note">未检测：本次尚无可用的模型回答。</p><p class="dp-note">仅复核明确品牌名称，不将产品通用词视为品牌命中；不回写历史记录。仅代表本次抽样，不代表推荐率或所有 AI 平台表现。</p></template>

          <template v-else-if="slide.kind === 'issues'"><div class="dp-grid dp-three dp-issue-grid"><article v-for="item in slide.rows" :key="item.code" class="dp-card dp-warm"><span class="dp-tag">{{ severity(item.severity) }}优先级</span><h3>{{ short(item.title, 35) }}</h3><p>{{ short(item.recommendation, 90) }}</p><small>评分扣分 {{ item.deduction ? `−${item.deduction}` : '0' }} · {{ item.category }}</small></article></div><p v-if="!slide.rows.length" class="dp-note">本次已评估规则未发现明确失败项。</p><p class="dp-note">未检测项不作为确定问题；评分扣分不代表流量或业务损失。完整证据与建议见附录一、附录二。</p></template>

          <template v-else-if="slide.kind === 'rules'"><p class="dp-appendix-meta">{{ report.scope }} · 规则版本 {{ report.version }} · 检测时间 {{ report.date }}</p><div class="dp-grid dp-two dp-rule-grid"><article v-for="(entry,i) in slide.rows" :key="i" class="dp-card"><div class="dp-rule-status"><span class="dp-tag" :class="{ 'dp-passed': entry.item.passed === true }">{{ statusLabel(entry.item) }}</span><small>评分扣分 {{ entry.item.passed === false && entry.item.deduction ? `−${entry.item.deduction}` : '—' }}</small></div><h3>{{ short(entry.item.title, 60) }}{{ entry.part ? '（续）' : '' }}</h3><p class="dp-rule-text">{{ entry.text }}</p></article></div></template>
          <template v-else-if="slide.kind === 'answer'"><h3 class="dp-answer-question">{{ slide.question }}</h3><p class="dp-appendix-meta">{{ report.sample.platform || '平台未记录' }} · {{ report.sample.model || '模型未记录' }} · {{ reportDate(report.sample.executed_at) }}　<span class="dp-tag">{{ mention(slide.row) }}</span></p><div class="dp-full-text dp-answer-text"><template v-for="(part,i) in answerSegments(slide.text)" :key="i"><strong v-if="part.bold">{{ part.text }}</strong><template v-else>{{ part.text }}</template></template></div></template>
          <div v-else-if="slide.kind === 'text'" class="dp-full-text">{{ slide.text }}</div>
        </main>
      </template>
      <footer><span>{{ short(report.name, 40) }} · {{ report.scope }} · {{ report.date }}</span><span>{{ pageIndex + 1 }} / {{ report.slides.length }}</span></footer>
    </section>
  </article>
</template>

<style scoped>
.diagnostic-print-report{display:none;color:#282332;font:16px/1.6 "Avenir Next","PingFang SC","Microsoft YaHei",sans-serif;text-align:left;background:#faf9fc;--purple:#7945bf;--green:#0ba883;--muted:#85808f;--line:#e3deea}
.diagnostic-print-report *{box-sizing:border-box}.dp-slide{position:relative;width:1280px;height:720px;padding:30px 38px 42px;break-after:page;background:#faf9fc;overflow:hidden}.dp-slide:last-child{break-after:auto}.dp-slide main{height:648px}.dp-slide main.dp-with-heading{height:546px}.dp-slide footer{position:absolute;bottom:15px;left:38px;right:38px;display:flex;justify-content:space-between;color:#918799;font-size:10px}.dp-page-cover footer,.dp-page-divider footer{bottom:35px;left:72px;right:72px;border-top:1px solid var(--line);padding-top:15px;font-size:12px}
h1,h2,h3,p{margin:0}h1,h2{font-family:"Songti SC","Noto Serif SC",serif}h2{font-size:26px;line-height:1.45}h3{font-size:18px;line-height:1.5}p{margin:12px 0;overflow-wrap:anywhere}small,.dp-muted{font-size:12px;color:var(--muted)}b,strong{font-weight:700}.dp-kicker{font-size:11px;letter-spacing:2px;font-weight:800;color:var(--purple);margin:0 0 12px}.dp-brand{display:flex;align-items:center;gap:10px;font-size:20px}.dp-brand img{width:45px;height:45px;object-fit:contain}.dp-brand small{display:block;font-size:9px;letter-spacing:2px}.dp-heading{height:86px;display:flex;justify-content:space-between;align-items:flex-start;border-bottom:1px solid var(--line);margin-bottom:16px}.dp-heading h2{font-family:inherit;font-size:28px}.dp-heading .dp-kicker{margin-bottom:4px}.dp-heading .dp-brand{font-size:16px}.dp-heading .dp-brand img{width:36px;height:36px}
.dp-page-cover,.dp-page-divider{padding:62px 72px;background:radial-gradient(ellipse at 100% 0,#e5f5ef,transparent 52%),linear-gradient(120deg,#fff,#f6f0ff)}.dp-title-block{position:relative;z-index:1;margin-top:105px;max-width:760px}.dp-title-block h1{font-size:62px;line-height:1.3;margin:20px 0;overflow-wrap:anywhere;max-width:700px}.dp-page-cover h1{font-size:55px}.dp-subtitle{font-size:21px;color:#7b7189}.dp-url{font-size:14px;color:#91879c;margin-top:28px;overflow-wrap:anywhere}.dp-chapter-number{position:absolute;right:85px;top:95px;font:350px/1 Georgia,serif;color:#ece5f5}.dp-orbits{position:absolute;right:-160px;top:110px;width:560px;height:560px;border:1px solid #cbb5e9;border-radius:50%}.dp-orbits:after,.dp-orbits:before{content:"";position:absolute;inset:65px;border:1px solid #d9c9ed;border-radius:50%}.dp-orbits:before{inset:130px;border-color:#c4e1d7}
.dp-grid{display:grid;gap:18px}.dp-two{grid-template-columns:repeat(2,minmax(0,1fr))}.dp-three{grid-template-columns:repeat(3,minmax(0,1fr))}.dp-four{grid-template-columns:repeat(4,minmax(0,1fr))}.dp-fill{height:100%}.dp-card{min-width:0;padding:23px;border:1px solid var(--line);border-radius:21px;background:#fff}.dp-card>small{display:block;margin-top:5px}.dp-tag{display:inline-block;border-radius:20px;padding:5px 11px;background:#fff3d9;color:#a5731c;font-size:11px;font-weight:700}.dp-passed{color:#0a9675;background:#e9f8f2}.dp-warm{background:#fffbf4;border-color:#efdfbe}.dp-rose{background:#fff5f3!important;color:#c45449}.dp-mint{background:#eef9f5!important}.dp-stat{padding:17px;background:#f5f3f8;border-radius:16px;min-width:0}.dp-stat label{display:block;color:var(--muted);font-size:13px}.dp-stat strong{display:block;font-size:37px;line-height:1.35;margin:9px 0;color:#242331}.dp-stat strong small{display:inline;font-size:15px}.dp-stat small{display:block}.dp-stat .dp-word{font-size:25px;overflow-wrap:anywhere}.dp-stats{margin:22px 0 15px}.dp-bar{display:block;height:6px;background:#ecefed;border-radius:8px;overflow:hidden;margin:22px 0}.dp-bar>i{display:block;height:100%;background:linear-gradient(90deg,#11b987,#10a3a3 65%,#7940d5);border-radius:8px}.dp-radar{width:100%;height:355px;margin:16px 0}.dp-note{border-left:3px solid #b797d8;padding:10px 15px;background:#f4effa;color:#7e6a92;font-size:12px;margin:15px 0 0}
.dp-overview{height:100%;display:grid;grid-template-columns:235px 1fr;border:1px solid #ded0ef;border-radius:24px;background:linear-gradient(115deg,#fff,#f7f1fd 65%,#f1faf7);overflow:hidden}.dp-score-column{display:flex;flex-direction:column;align-items:center;justify-content:space-evenly;padding:30px 24px;border-right:1px solid var(--line);background:#ffffff80;text-align:center}.dp-score-column .dp-kicker{font-size:10px;letter-spacing:.5px}.dp-gauge{position:relative;width:200px;height:190px}.dp-gauge svg{width:100%;height:100%;overflow:visible}.dp-gauge circle{fill:none;stroke-width:12;stroke-linecap:round;transform:rotate(135deg);transform-origin:120px 111px}.dp-gauge-track{stroke:#e3ece7;stroke-dasharray:75 100}.dp-gauge-value{stroke:url(#dp-gauge-green)}.dp-gauge>div{position:absolute;inset:70px 0 auto;display:flex;justify-content:center;align-items:baseline}.dp-gauge strong{font:700 57px/1 Georgia,serif;letter-spacing:-3px}.dp-gauge small{font-size:15px}.dp-composition{width:100%;text-align:left;border-top:1px solid var(--line);padding-top:15px}.dp-composition>div{display:grid;grid-template-columns:1fr auto;gap:7px;font-size:10px;margin-bottom:12px}.dp-composition b{color:#94879e}.dp-composition i{grid-column:1/-1;height:4px;background:#eceaef;border-radius:3px}.dp-composition>small{font-size:9px;line-height:1.7;display:block}.dp-overview-copy{padding:30px 30px 28px;display:flex;flex-direction:column;justify-content:space-between}.dp-overview-copy>h2{font-size:31px}.dp-lead{font-size:16px;color:#7a7483;line-height:1.8}.dp-risk{display:flex;align-items:center;gap:12px;border:1px solid #f0d2ce;background:#fff7f5;border-radius:12px;padding:13px;font-size:11px;color:#90605a;margin:8px 0}.dp-risk b{padding:3px 7px;border-radius:8px;background:#d95e54;color:white;white-space:nowrap}.dp-findings{gap:10px}.dp-findings .dp-card{padding:17px 15px;border-radius:14px}.dp-findings h3{font-size:15px;margin:8px 0}.dp-findings p{font-size:12px;color:#88818c;line-height:1.7;margin:4px 0}.dp-priority{color:#b47c24;font-size:10px}.dp-proof{display:grid;grid-template-columns:270px 1fr;gap:15px;padding:20px;border:1px solid #dfd3ef;border-left:3px solid #9862d8;border-radius:16px;background:linear-gradient(110deg,#f8f3ff,#fff,#eef9f5);margin-top:16px}.dp-proof .dp-brand{font-size:14px}.dp-proof .dp-brand small{font-size:8px;color:#8b6caf}.dp-proof p{font-size:12px;color:#77707d;line-height:1.7;margin:0}.dp-proof-points{grid-column:1/-1;border-top:1px solid #e9e0f1;padding-top:13px;display:flex;gap:20px;font-size:11px;color:#73707b}
.dp-signals-layout{display:grid;grid-template-columns:2fr 1fr;grid-template-rows:340px 288px;gap:20px}.dp-suggestion-panel{grid-column:1/-1}.dp-signal-grid{display:grid;grid-template-columns:1fr 1fr;gap:25px;margin-top:42px}.dp-signal-grid>div{display:grid;grid-template-columns:85px 1fr 36px;align-items:center;gap:12px;font-size:12px;color:#83808b}.dp-signal-grid .dp-bar{margin:0}.dp-signal-grid b{text-align:right;color:#4f4958;font-size:11px}.dp-current-sample{display:flex;align-items:center;gap:12px;margin-top:38px;padding-bottom:14px;border-bottom:1px solid var(--line);font-size:11px}.dp-current-sample>div{flex:1;min-width:0}.dp-current-sample small{display:block;font-size:10px}.dp-current-sample>span{white-space:nowrap;font-size:10px}.dp-current-sample>i,.dp-suggestions i{display:grid;place-items:center;width:25px;height:25px;flex:none;border-radius:50%;background:#17b389;color:white;font-style:normal}.dp-suggestions{display:grid;grid-template-columns:repeat(4,1fr);margin-top:40px}.dp-suggestions>div{display:flex;gap:12px;padding:10px 16px;min-width:0}.dp-suggestions>div+div{border-left:1px solid var(--line)}.dp-suggestions b{font-size:13px}.dp-suggestions p{font-size:12px;color:#8d8693;line-height:1.7;margin:7px 0}
.dp-seo-panel{height:100%;border:1px solid var(--line);border-radius:24px;overflow:hidden;background:white}.dp-seo-heading{height:135px;padding:24px 28px;border-bottom:1px solid var(--line);background:linear-gradient(110deg,#fff,#f1f7f6)}.dp-seo-heading .dp-kicker{margin-bottom:6px}.dp-seo-heading p:last-child{font-size:14px;color:var(--muted)}.dp-seo-hero{height:calc(100% - 135px);display:grid;grid-template-columns:200px 1fr 365px;background:linear-gradient(105deg,#fcf8ff,#fff,#f5fcf8)}.dp-seo-hero aside{border-right:1px solid var(--line);padding:35px 15px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center}.dp-seo-hero aside strong{font-size:40px;margin:24px 0}.dp-seo-hero aside h3{font-size:13px}.dp-seo-hero .dp-kicker{font-size:9px}.dp-seo-copy{padding:28px;display:flex;flex-direction:column;justify-content:center}.dp-seo-copy h2{font-size:26px;line-height:1.6}.dp-seo-copy em{color:#7945bb;font-style:normal}.dp-seo-copy>p{font-size:14px;color:#807888;line-height:1.9}.dp-chips{display:flex;gap:7px;margin-top:14px}.dp-chips span{border-radius:14px;background:#eaf7f1;color:#098c70;padding:6px 8px;font-size:10px}.dp-facts{display:grid;grid-template-columns:1fr 1fr;align-self:center;margin:25px 25px 25px 0;border:1px solid var(--line);border-radius:19px;overflow:hidden;background:#fff}.dp-facts>div{padding:16px;border-bottom:1px solid var(--line)}.dp-facts>div:nth-child(odd){border-right:1px solid var(--line)}.dp-facts span,.dp-facts small{display:block;font-size:10px;color:var(--muted)}.dp-facts strong{font:700 27px/1.6 "Songti SC",serif;overflow-wrap:anywhere}.dp-facts small{font-size:9px}
.dp-section-top{display:flex;align-items:end;justify-content:space-between;height:78px;margin-bottom:18px}.dp-section-top p:not(.dp-kicker){font-size:12px;color:#8b8492}.dp-core-cards{height:552px}.dp-core-cards .dp-card{position:relative;padding:25px 22px;background:radial-gradient(circle at 100% 0,#f1eaf9,transparent 50%),#fff}.dp-core-cards .dp-card:nth-child(1),.dp-core-cards .dp-card:nth-child(4){background:radial-gradient(circle at 100% 0,#e9f8f2,transparent 50%),#fff}.dp-core-cards h3{font-size:16px;margin:14px 0 30px}.dp-core-cards p{font-size:14px;line-height:1.9;color:#8b8492;margin:23px 0 30px}.dp-metric-icon{float:right;color:#7950b7;font-weight:800}.dp-big-word{display:block;font:700 35px/1.5 "Songti SC",serif;margin:18px 0}.dp-mini-facts{display:grid;grid-template-columns:1fr 1fr;gap:8px}.dp-mini-facts>div{border:1px solid var(--line);border-radius:11px;padding:12px}.dp-mini-facts small,.dp-mini-facts b{display:block;font-size:12px}.dp-mini-facts b{font-size:22px;color:#7c52ad;margin-top:10px}.dp-cwv{display:grid;gap:12px;margin:25px 0}.dp-cwv>div{display:flex;justify-content:space-between;gap:7px;padding:16px 12px;background:#f8f7fa;border:1px solid var(--line);border-radius:11px;font-size:11px}
.dp-analysis-layout>.dp-grid{height:420px}.dp-analysis-layout .dp-card{padding:20px 24px}.dp-analysis-layout .dp-kicker{margin-bottom:6px}.dp-analysis-layout h2{font-size:23px;margin-bottom:15px}.dp-data-row{display:flex;justify-content:space-between;font-size:12px;color:#867e8e;padding:9px 0;border-bottom:5px solid #edf0ee;margin-bottom:12px}.dp-data-row b{color:#56505e}.dp-explain{display:grid;grid-template-columns:70px 1fr;gap:12px;border-radius:9px;padding:10px 12px;background:#faf8fb;font-size:12px;color:#756d7f;margin-top:10px}.dp-roadmap{border:1px solid #e1d5ee;border-radius:20px;background:linear-gradient(100deg,#f8f2fe,#fff,#e8f7f1);padding:18px 22px;margin-top:18px;height:210px}.dp-roadmap .dp-grid>div{display:flex;gap:13px;padding:15px;background:#ffffffce;border:1px solid #e6dcef;border-radius:14px}.dp-step{display:grid;place-items:center;width:40px;height:40px;flex:none;background:#8b44d0;color:white;border-radius:12px;font-size:12px}.dp-roadmap h3{font-size:15px}.dp-roadmap p{font-size:12px;color:var(--muted);margin:7px 0}
.dp-sample-stats .dp-stat{padding:12px 18px}.dp-sample-stats strong{font-size:34px;margin:5px 0}.dp-sample-cards{margin-top:15px}.dp-sample-cards .dp-card{padding:17px}.dp-sample-cards .dp-tag{margin:14px 0 5px}.dp-sample-cards .dp-question{font-size:15px;margin:10px 0}.dp-sample-cards p{font-size:13px;color:#827b8b;line-height:1.75}.dp-sample-cards small{font-size:12px}.dp-issue-grid{grid-auto-rows:225px;gap:15px}.dp-issue-grid .dp-card{padding:16px}.dp-issue-grid h3{font-size:16px;margin:10px 0}.dp-issue-grid p{font-size:13px;color:#7a7183;line-height:1.7}.dp-issue-grid small{font-size:11px}
.dp-appendix-meta{font-size:12px;color:#95849e;margin:0 0 15px}.dp-rule-grid{grid-auto-rows:245px;gap:16px}.dp-rule-grid .dp-card{padding:16px 18px}.dp-rule-status{display:flex;justify-content:space-between;align-items:center}.dp-rule-status small{font-size:10px}.dp-rule-grid h3{font-size:16px;margin:8px 0}.dp-rule-text{font-size:12px;line-height:1.55;white-space:pre-wrap;overflow-wrap:anywhere;margin:0}.dp-full-text{column-count:2;column-gap:32px;column-rule:1px solid var(--line);column-fill:auto;height:510px;font-size:14px;line-height:1.7;white-space:pre-wrap;overflow-wrap:anywhere;word-break:break-word}.dp-answer-text{height:432px}.dp-answer-question{font-size:18px;line-height:1.5;margin:0 0 12px;overflow-wrap:anywhere}.dp-page-answer .dp-appendix-meta{margin-bottom:15px}
@media print{.diagnostic-print-report{display:block!important;width:1280px!important;-webkit-print-color-adjust:exact;print-color-adjust:exact}.dp-slide{margin:0!important;box-shadow:none!important} @page{size:1280px 720px;margin:0;@top-left{content:""}@top-center{content:""}@top-right{content:""}@bottom-left{content:""}@bottom-center{content:""}@bottom-right{content:""}}}
.dp-facts>div:last-child{grid-column:1/-1;border-right:0;border-bottom:0}.dp-facts strong small{display:inline;margin-left:5px;font:600 10px sans-serif}
</style>
