const fs = require('fs'), path = require('path'), os = require('os'), assert = require('assert');
const {pathToFileURL} = require('url');
const puppeteer = require('puppeteer-core');
const profile = fs.mkdtempSync(path.join(os.tmpdir(),'client-workbench-'));
const edge = process.env.EDGE_BINARY || ['C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe','C:/Program Files/Microsoft/Edge/Application/msedge.exe'].find(fs.existsSync);
(async () => {
  const browser = await puppeteer.launch({executablePath:edge,headless:true,userDataDir:profile,defaultViewport:{width:1440,height:900},args:['--no-first-run']});
  try {
    const page = await browser.newPage(), errors = [], network = [];
    page.on('pageerror',e => errors.push(e.message));
    page.on('request',r => {if (/^https?:/.test(r.url())) network.push(r.url());});
    const url = pathToFileURL(path.join(__dirname,'index.html')).href;
    for (const combo of ['SEM','SEO','GEO','SEM,SEO','SEM,GEO','SEO,GEO','SEM,SEO,GEO']) {
      await page.goto(url+'?modules='+encodeURIComponent(combo));
      assert.deepEqual(await page.evaluate(() => DEV_ADAPTER.modules),combo.split(','));
      assert.equal(await page.$$eval('.module-card',nodes => nodes.length),combo.split(',').length);
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth),false);
      for (const module of combo.split(',')) {
        await page.click(`[data-action="module-data"][data-module="${module}"]`);
        for (const level of ['L1','L2','L3']) {
          await page.click(`[data-level="${level}"]`);
          assert((await page.$eval('#content',e => e.textContent)).includes(module+' / '+level));
        }
      }
      console.log('PASS combination '+combo);
    }
    await page.goto(url+'?modules=SEO');
    await page.click('[data-action="task"]');
    await page.click('[data-action="confirm"]');
    assert.equal(await page.evaluate(() => DEV_ADAPTER.tasks[0].state),'待我方发布');
    await page.$eval('#edit-body',e => e.value += '\n客户补充：保留已有型号。');
    await page.click('[data-action="edit"]');
    assert.deepEqual(await page.evaluate(() => ({version:DEV_ADAPTER.tasks[0].version,state:DEV_ADAPTER.tasks[0].state,confirmation:DEV_ADAPTER.tasks[0].confirmation})),{version:2,state:'顾问复核',confirmation:null});
    assert.equal(await page.$$eval('[data-action="confirm"]',nodes => nodes.length),0);
    assert.equal(await page.evaluate(() => {try{DEV_ADAPTER.confirm('local-SEO',1);return false}catch{return true}}),true);
    await page.click('.drawer .close');
    await page.click('[data-role="advisor"]'); await page.click('[data-action="task"]');
    await page.click('[data-action="review"]');
    await page.click('.drawer .close');
    await page.click('[data-role="customer"]'); await page.click('[data-action="task"]');
    await page.click('[data-action="return"]');
    assert((await page.$eval('.error',e=>e.textContent)).includes('退回依据'));
    await page.type('#reason','请核对参数来源');
    await page.click('[data-action="return"]');
    assert.equal(await page.evaluate(() => DEV_ADAPTER.tasks[0].state),'顾问复核');
    await page.click('.drawer .close');
    await page.click('[data-role="advisor"]'); await page.click('[data-action="task"]');
    await page.click('[data-action="review"]');
    await page.click('.drawer .close');
    await page.click('[data-role="customer"]'); await page.click('[data-action="task"]');
    await page.click('[data-action="confirm"]');
    assert.equal(await page.evaluate(() => DEV_ADAPTER.tasks[0].confirmation.version),2);
    await page.click('.drawer .close'); await page.click('[data-page="交付记录"]');
    assert((await page.$eval('#content',e=>e.textContent)).includes('本人确认'));
    assert((await page.$eval('#content',e=>e.textContent)).includes('v2'));
    await page.click('[data-page="首页"]'); await page.click('[data-action="task"]');
    await page.click('[data-action="request-advisor"]');
    assert.equal(await page.evaluate(() => DEV_ADAPTER.tasks[0].advisorRequested),true);
    await page.click('.drawer .close'); await page.click('[data-role="advisor"]');
    assert((await page.$eval('#summary',e=>e.textContent)).includes('需我介入：1'));
    await page.type('#input','这是内部消息'); await page.select('#message-visibility','internal'); await page.click('[data-action="chat"]');
    await page.type('#input','这是客户可见顾问消息'); await page.click('[data-action="chat"]');
    await page.click('[data-action="task"]');
    assert.equal(await page.$$eval('[data-action="confirm"]',nodes=>nodes.length),0);
    await page.type('#comment-text','内部核对参数'); await page.select('#comment-visibility','internal'); await page.click('[data-action="comment"]');
    await page.type('#comment-text','请客户提供型号依据'); await page.click('[data-action="comment"]');
    await page.click('[data-action="intervene"]');
    await page.click('[data-action="reject"]'); assert((await page.$eval('.error',e=>e.textContent)).includes('复核退回依据'));
    await page.type('#reason','参数来源不足'); await page.click('[data-action="reject"]');
    assert.equal(await page.evaluate(()=>DEV_ADAPTER.tasks[0].state),'待修改');
    await page.click('.drawer .close'); await page.click('[data-role="customer"]');
    assert(!(await page.$eval('#messages',e=>e.textContent)).includes('这是内部消息'));
    assert((await page.$eval('#messages',e=>e.textContent)).includes('这是客户可见顾问消息'));
    assert((await page.$eval('#messages',e=>e.textContent)).includes('顾问 · 模拟身份'));
    await page.click('[data-action="task"]');
    assert(!(await page.$eval('.comments',e=>e.textContent)).includes('内部核对参数'));
    assert((await page.$eval('.comments',e=>e.textContent)).includes('请客户提供型号依据'));
    assert.equal(await page.evaluate(()=>{try{DEV_ADAPTER.simulateReview('local-SEO',2);return false}catch{return true}}),true);
    await page.click('.drawer .close'); await page.click('#policy-controls summary');
    await page.select('#edit-policy','system_check'); await page.click('[data-action="task"]');
    await page.$eval('#edit-body',e=>e.value+='\n参数来源已补充（样例）。'); await page.click('[data-action="edit"]');
    assert.equal(await page.evaluate(()=>DEV_ADAPTER.tasks[0].state),'系统检查');
    assert.equal(await page.evaluate(()=>DEV_ADAPTER.tasks[0].confirmation),null);
    await page.click('.development-tools summary'); await page.click('[data-action="system-check"]');
    await page.click('[data-action="confirm"]'); assert.equal(await page.evaluate(()=>DEV_ADAPTER.tasks[0].confirmation.version),3);
    await page.click('.drawer .close');
    await page.goto(url+'?modules=SEM,GEO'); await page.click('[data-action="task"]');
    assert.equal(await page.$$eval('[data-action="edit"],[data-action="confirm"]',nodes=>nodes.length),0);
    await page.goto(url+'?modules=SEO'); await page.setViewport({width:390,height:844});
    await page.click('[data-page="首页"]');
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth),false);
    await page.reload(); assert.equal(await page.evaluate(() => DEV_ADAPTER.tasks[0].version),1);
    await page.click('[data-role="advisor"]');await page.click('[data-action="task"]');
    await page.click('[data-action="confirm-on-behalf"]');
    assert.deepEqual(await page.evaluate(()=>({role:DEV_ADAPTER.tasks[0].confirmation.actorRole,onBehalf:DEV_ADAPTER.tasks[0].confirmation.onBehalf,id:DEV_ADAPTER.tasks[0].confirmation.actor.id})),{role:'advisor',onBehalf:true,id:'local-advisor-1'});
    assert((await page.$eval('.confirmation-card',e=>e.textContent)).includes('代确认'));
    await page.$eval('#edit-body',e=>e.value+='\n修改业务事实');await page.click('[data-action="edit"]');
    assert.equal(await page.evaluate(()=>DEV_ADAPTER.confirmationHistory[0].valid),false);
    await page.click('.drawer .close'); await page.click('[data-page="服务设置"]');
    await page.$eval('#materials',e=>e.value='新资料（开发样例）');await page.click('[data-action="settings-save"]');
    assert.equal(await page.evaluate(()=>DEV_ADAPTER.settings.version),2);
    assert.equal(await page.evaluate(()=>DEV_ADAPTER.tasks.length),1);
    await page.click('[data-role="customer"]');
    assert.equal(await page.$$eval('[data-page="服务设置"]',nodes=>nodes.length),0);
    assert.equal(await page.evaluate(()=>{try{DEV_ADAPTER.saveSettings({materials:'x',direction:'y',keywords:'z'},2);return false}catch{return true}}),true);
    await page.click('[data-page="交付记录"]');
    assert((await page.$eval('#content',e=>e.textContent)).includes('已失效'));
    await page.click('[data-page="SEO工作"]');
    for(const area of ['网站检查','关键词与搜索','内容','发布核验','数据报告','异常进度']) {
      await page.click(`[data-area="${area}"]`);assert((await page.$eval('#content',e=>e.textContent)).includes('接口状态：未接通'));
      await page.click('[data-action="progress-detail"]');
      assert((await page.$eval('.drawer',e=>e.textContent)).includes('处理历史'));
      assert((await page.$eval('.drawer',e=>e.textContent)).includes('不是生产结果'));
      await page.click('.drawer .close');
    }
    await page.goto(url+'?modules=SEO');await page.click('[data-page="进度"]');
    assert.equal(await page.$$eval('[data-action="progress-detail"]',nodes=>nodes.length),6);
    assert.deepEqual(await page.evaluate(()=>DEV_ADAPTER.progressFor().map(p=>p.state).sort()),['程序处理中','失败待处理','客户待确认稿件','人工发布待回填','顾问待处理','已完成'].sort());
    await page.click('[data-progress-id="local-progress-4"]');
    assert((await page.$eval('.drawer',e=>e.textContent)).includes('回填准确版本、地址、发布时间'));
    await page.click('[data-action="progress-evidence"]');
    assert((await page.$eval('#content',e=>e.textContent)).includes('SEO / L3'));
    await page.click('[data-page="首页"]');await page.click('[data-role="advisor"]');await page.click('[data-action="task"]');await page.click('[data-action="confirm-on-behalf"]');
    await page.click('.drawer .close');await page.click('[data-page="进度"]');await page.click('[data-progress-id="local-progress-3"]');
    assert((await page.$eval('.drawer',e=>e.textContent)).includes('尚未发布'));
    assert((await page.$eval('.drawer',e=>e.textContent)).includes('顾问 · 模拟身份'));
    assert.deepEqual(network,[]); assert.deepEqual(errors,[]);
    console.log('PASS shared role views, version invalidation, review/return/reconfirm, advisor request, internal visibility, configurable continuation, readonly SEM/GEO, mobile, reset, no network');
    console.log('PASS UI-02 delegated actor/time/version, confirmation invalidation history, advisor-only settings, no customer config approvals, six SEO areas');
    console.log('PASS UI-03 six unified states, details/history/evidence, L3 navigation, delegated confirmation is not publication');
    console.log('ALL PASS');
  } finally {await browser.close(); fs.rmSync(profile,{recursive:true,force:true});}
})().catch(e => {console.error(e);process.exitCode=1;});
