'use strict';
// Local fixtures only: no business API, production rule, or execution adapter.
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number(v).toLocaleString('zh-CN',{maximumFractionDigits:1}),money=v=>'¥'+num(v),sum=a=>a.reduce((x,y)=>x+y,0);
const colors={sem:'#e9b56c',seo:'#6ed5b8',geo:'#b6a1ff'};
const dates=['08-31','09-01','09-02','09-03','09-04','09-05','09-06'];
const weekly={spend:[5800,6100,5750,6230,5990,6190,6050],topic:[1980,2130,1920,2210,1990,2010,2080],clicks:[105,120,115,130,122,125,120],conversions:[0,0,1,0,1,0,0],organic:[42,48,50,55,57,63,65],rank:[13,11,9,8,7,5,4]};
const samples=[
['G-01','09-01','真实引擎','智能仓储解决方案哪家好',true],['G-02','09-03','真实引擎','仓储自动化如何降低成本',false],['G-03','09-05','真实引擎','立体仓库设计需要注意什么',false],
['G-04','09-02','人工核实','工业货架安全标准是什么',true],['G-05','09-04','人工核实','重型货架厂家推荐',false],
['G-06','09-01','模拟人设','仓储自动化如何降低成本',true],['G-07','09-02','模拟人设','仓储自动化如何降低成本',false],['G-08','09-03','模拟人设','仓储自动化如何降低成本',true],['G-09','09-04','模拟人设','仓储自动化如何降低成本',false],['G-10','09-04','模拟人设','立体仓库设计需要注意什么',true],['G-11','09-05','模拟人设','立体仓库设计需要注意什么',false],['G-12','09-06','模拟人设','立体仓库设计需要注意什么',false]];
const issues={
allocation:{id:'allocation',no:'01',type:'跨模块观察',short:'花费集中，承接待验证',summary:'SEM × SEO · 优先核对',topic:'智能仓储 · 花费与承接',tag:'资源分配',status:'证据尚不足以调预算',title:'这批词花了 34% 的钱，先弄清它带来了什么。',body:'「智能仓储解决方案」本周花费 ¥14,320，报表转化 2 次。同时，相关内容获得 380 次自然点击。两者值得一起看，但还不能认定自然流量已能替代付费流量。',boundary:'SEM 是百度投放，内容点击来自 Google Search Console；搜索引擎与访客归因不同，不能直接相抵。GEO 混合样本不参与本项判断。',next:'让 SEM 与 SEO 联合核对词组、落地页及有效转化',owner:'SEM / SEO 联合运营',task:'核验智能仓储词组的付费与自然承接',criteria:['同一客户、同一周窗口、同一词组与落地页映射','提供付费有效转化和自然点击的来源记录，注明搜索引擎','形成基线后再讨论预算试验；不以点击替代有效转化'],evidence:[['sem','本周词组花费','¥14,320','占总花费 34% · 2 次转化','sem'],['seo','相关内容自然点击','380','GSC 口径 · 比上周 +25%','seo'],['geo','当前决策条件','未齐','有效转化与渠道映射待补','boundary']]},
images:{id:'images',no:'02',type:'可行动事项',short:'修复已做，结果没验完',summary:'SEO · 8 张仍需跟进',topic:'图片修复 · 效果验收',tag:'执行闭环',status:'可安排复查 · 问题范围明确',title:'“审核通过”之后，还有 8 张图片没有确认修复。',body:'这批 20 张图片已完成建议审核。重新抓取确认修复 12 张，3 张仍未通过，5 张等待复查。当前确认率 60%，这项工作还不能整体标记完成。',boundary:'SEO 的审核状态与重新抓取结果是两个阶段。只认每张图片的复查记录；这项修复对 GEO 可见度的影响尚无证据。',next:'复查剩余 8 张图片，按失败原因补齐修复证据',owner:'SEO 内容运营',task:'补齐图片修复批次的重新抓取验收',criteria:['覆盖同一批次的全部 20 张图片','逐张保留修复前后结果及重新抓取时间','未通过项保留失败原因；不能把审核通过当作确认修复'],evidence:[['seo','已确认修复','12 / 20','重新抓取通过 · 60%','images'],['sem','待复查','5 张','尚未有重新抓取结果','images'],['geo','复查未通过','3 张','已分离到人工复核队列','images']]},
visibility:{id:'visibility',no:'03',type:'数据质量',short:'可见度判断受样本限制',summary:'GEO · 模拟样本占 58%',topic:'AI 可见度 · 样本可信度',tag:'证据质量',status:'不能代表真实需求',title:'12 条样本里只有 3 条是真实探测，增长暂不下结论。',body:'本周示例样本包含 3 条真实引擎、2 条人工核实和 7 条模拟人设。合计 5 条提及品牌，但混合口径的 41.7% 不能等同于真实引擎可见度。',boundary:'真实引擎单独统计为 1/3，样本很小；人工核实与模拟人设应分别展示。没有可比的上周样本，不显示增长率。',next:'先隔离模拟样本，再补齐同引擎、同问题的可比探测',owner:'GEO 运营',task:'补齐 GEO 真实样本与可比基线',criteria:['明确每条样本的来源模式、问题、引擎和观测时间','模拟样本不进入真实可见度口径','同一问题与引擎建立前后期可比样本，样本不足时保留未知'],evidence:[['geo','真实引擎','3 条','占 25% · 1 条提及品牌','geo'],['seo','人工核实','2 条','占 16.7% · 1 条提及品牌','geo'],['sem','模拟人设','7 条','占 58.3% · 不纳入真实口径','geo']]}
};
const seedTasks=[
{id:'EX-104',title:'图片修复批次：确认实际修复结果',owner:'SEO 内容运营',due:'2026-09-08',status:'evidence',issue:'images',note:'审核结束，重新抓取尚未覆盖全部图片。',evidence:'已核对 15/20 张，其中 12 张修复通过、3 张未通过；另 5 张待复查。',observed:'2026-09-06 09:20',criterion:'同批 20 张图片均有重新抓取结果，并逐张判定。'},
{id:'EX-103',title:'补齐 GEO 真实引擎探测基线',owner:'GEO 运营',due:'2026-09-09',status:'active',issue:'visibility',note:'需补齐引擎与问题一致的前后期样本。',evidence:'本周已有 3 条真实探测；尚无可比上周样本，无法验收增长。',observed:'2026-09-06 08:45',criterion:'同引擎、同问题的可比样本与独立真实口径。'},
{id:'EX-101',title:'产品页标题缺失修复',owner:'SEO 内容运营',due:'2026-09-05',status:'verified',issue:'images',note:'修复与复查均结束。此记录演示如何用证据判断完成。',evidence:'示例批次 6 个产品页：缺失标题从 6 页降至 0 页；09-05 16:40 重新抓取，6/6 页具备非空标题。',observed:'2026-09-05 16:40',criterion:'6 个指定产品页重新抓取后均无标题缺失。'}];
const storageKey='snipers-cockpit-prototype-v2-drafts';
let localDrafts=[];
try{const parsed=JSON.parse(sessionStorage.getItem(storageKey)||'[]');if(Array.isArray(parsed))localDrafts=parsed.filter(t=>t&&typeof t.id==='string'&&t.id.startsWith('LOCAL-')&&Object.hasOwn(issues,t.issue)&&['draft','cancelled'].includes(t.status)&&typeof t.title==='string'&&typeof t.owner==='string').slice(0,100);}catch{}
const state={page:'overview',issue:'allocation',mode:innerWidth<=620?'fullscreen':'split',filter:'all',module:'sem',sampleFilter:'all',dialog:null,chartRange:7,chartMetric:'spend'};
let toastTimer;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000);}
function persist(){try{sessionStorage.setItem(storageKey,JSON.stringify(localDrafts));return true;}catch{toast('存储不可用，草稿仅保留到本次刷新前。');return false;}}
function allTasks(){return [...localDrafts,...seedTasks];}
function badge(status){const [c,t]=({draft:['purple','待确认方案 · 尚未交给负责人'],active:['purple','执行中 · 示例'],evidence:['amber','待检查结果 · 示例'],verified:['green','检查已通过 · 示例'],cancelled:['','已撤回']})[status]||['','未知'];return `<span class="badge ${c}">${t}</span>`;}
function table(headers,rows){return `<div class="data-table-wrap"><table class="data-table"><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function smallSpark(data,color){const low=Math.min(...data),span=Math.max(...data)-low||1;return `<svg class="mini-spark" viewBox="0 0 64 24" aria-hidden="true"><polyline points="${data.map((v,i)=>`${i*64/(data.length-1)},${22-(v-low)/span*20}`).join(' ')}" fill="none" stroke="${color}" stroke-width="1.6"/></svg>`;}
function renderMetrics(){$('#metricStrip').innerHTML=`<button class="metric-card" data-action="chart" data-key="spend"><span class="metric-label"><i></i>SEM · 本周投放花费 ↗</span><div class="metric-value">${money(sum(weekly.spend))}</div><div class="metric-sub"><em>↑ 7.9%</em>较上周 · 官方报表口径</div>${smallSpark(weekly.spend,colors.sem)}</button><button class="metric-card" data-action="chart" data-key="organic"><span class="metric-label seo"><i></i>SEO · 相关内容点击 ↗</span><div class="metric-value">380<small>次</small></div><div class="metric-sub"><span class="green-text">↑ 25%</span> 较上周 · GSC 口径</div>${smallSpark(weekly.organic,colors.seo)}</button><button class="metric-card" data-action="evidence" data-key="geo"><span class="metric-label geo"><i></i>GEO · 真实探测样本 ↗</span><div class="metric-value">3<small>/ 12 条</small></div><div class="metric-sub"><em>25% 覆盖</em>暂无可比历史</div></button>`;}
function renderIssues(){const s=issues[state.issue];$('#issueTabs').innerHTML=Object.values(issues).map(i=>`<button class="issue-tab ${state.issue===i.id?'active':''}" data-issue="${i.id}" role="tab" aria-selected="${state.issue===i.id}" aria-controls="decisionCard" id="issue-${i.id}"><div class="issue-type"><span>${i.no} / ${i.type}</span><span>↗</span></div><h3>${i.short}</h3><p>${i.summary}</p></button>`).join('');$('#decisionCard').setAttribute('role','tabpanel');$('#decisionCard').setAttribute('aria-labelledby','issue-'+state.issue);$('#decisionCard').innerHTML=`<div class="decision-main"><div class="decision-eyebrow"><span class="badge purple">${s.tag}</span><span class="badge amber">${s.status}</span><span class="muted" style="font-size:9px">${s.no} / 示例观察，非已验证规则</span></div><h2>${s.title}</h2><p class="decision-subtitle">${s.body}</p><div class="evidence-flow">${s.evidence.map(([c,l,v,n,k])=>`<button class="evidence-node ${c}" data-action="evidence" data-key="${k}"><span class="node-label">${l}<span>↗</span></span><div class="node-value">${v}</div><p class="node-note">${n}</p></button>`).join('')}</div><div class="boundary"><span class="symbol">◇</span><span>${s.boundary}</span></div></div><div class="decision-footer"><div class="next-step"><span class="small-label">建议下一步</span><strong>${s.next}</strong></div><div class="button-row"><button class="secondary-button" data-action="discuss">讨论依据</button><button class="primary-button" data-action="draft">拟定行动 →</button></div></div>`;$('#contextTitle').textContent=s.topic+' ↗';}
function renderFollowups(){$('#followups').innerHTML=[seedTasks[0],seedTasks[2]].map(t=>`<button class="followup" data-task="${t.id}"><i class="status-dot ${t.status==='verified'?'green':'amber'}"></i><div><div class="followup-name">${t.title}</div><div class="followup-sub">${t.status==='verified'?'6/6 页复查通过 · 已留存核验记录':'12/20 张确认修复 · 还有 8 张需跟进'}</div></div><span class="badge ${t.status==='verified'?'green':'amber'}">${t.status==='verified'?'已核验':'待验收'}</span></button>`).join('');$('#moduleLinks').innerHTML=[['sem','SEM · 投放经营','花费结构 / 转化 / 核验计划'],['seo','SEO · 内容与搜索','流量 / 排名 / 修复进度'],['geo','GEO · AI 可见度','样本 / 提及 / 引用来源']].map(([k,t,d])=>`<button class="module-link" data-module="${k}"><i class="arrow">↗</i><span style="color:${colors[k]}">${t}</span><small>${d}</small></button>`).join('');}
function navigate(page){if(!['dashboard','overview','tasks','quality','module'].includes(page))return;state.page=page;$$('.page').forEach(e=>e.classList.toggle('active',e.id==='page-'+page));$$('[data-page]').forEach(e=>e.classList.toggle('active',e.dataset.page===page));$('#pageScroll').scrollTop=0;if(page==='tasks')renderTasks();if(page==='quality')renderQuality();if(page==='module')renderModule();}
function setIssue(id){if(!Object.hasOwn(issues,id))return;state.issue=id;renderIssues();if(state.page!=='overview')navigate('overview');if(innerWidth<=620)$('#decisionCard').scrollIntoView({block:'start'});updateSuggestions();}
function setMode(mode){if(!['chat-focus','screen-focus','split','fullscreen'].includes(mode))return;state.mode=mode;$('#workspace').dataset.mode=mode;$$('button[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===mode);b.setAttribute('aria-pressed',String(b.dataset.mode===mode));});const mobile=innerWidth<=620;$('#assistant').inert=mode==='fullscreen'||(mobile&&mode!=='chat-focus');$('#main').inert=mobile&&mode==='chat-focus';$('.assistant-fab').innerHTML=mobile&&mode==='chat-focus'?'返回看板 ↗':'<span>打开分析</span>';}
function showChat(){setMode(innerWidth<=620?'chat-focus':state.mode==='chat-focus'?'chat-focus':'split');}
function renderTasks(){const tasks=allTasks();$('#taskCount').textContent=tasks.filter(t=>t.status!=='cancelled').length;$('#ledgerSummary').innerHTML=[['待确认方案','draft'],['执行中','active'],['待检查结果','evidence'],['检查已通过','verified']].map(([s,k])=>`<div class="summary-cell"><b>${tasks.filter(t=>t.status===k).length}</b><span>${s}</span></div>`).join('');const q=$('#taskSearch').value.trim().toLowerCase();const filtered=tasks.filter(t=>(state.filter==='all'||(state.filter==='active'?['active','evidence'].includes(t.status):t.status===state.filter))&&[t.title,t.owner,t.id].join(' ').toLowerCase().includes(q));$('#taskList').innerHTML=filtered.length?filtered.map(t=>`<button class="task-row" data-task="${esc(t.id)}"><div><span class="eyebrow">${esc(t.id)} · ${t.id.startsWith('LOCAL-')?'当前标签页':'历史流程示例'}</span><h3>${esc(t.title)}</h3><p class="task-meta">${esc(t.owner)} · ${esc(t.due)} 前检查</p></div><div class="task-right">${typeof pSyntheticTask==='function'&&pSyntheticTask(t)?'<span class="badge purple">独立演练</span>':''}${badge(t.status)}<small>查看详情与检查结果 ↗</small></div></button>`).join(''):`<div class="empty-state"><p>${q?'没有匹配的行动，试试其他关键词。':'当前分类还没有行动。'}</p><button class="text-button" data-action="resetTaskFilter">查看全部行动</button></div>`;$$('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===state.filter));}
function sampleBar(){return `<div class="stacked-bar" aria-label="真实引擎25%，人工核实16.7%，模拟人设58.3%"><span style="width:25%;background:${colors.geo}"></span><span style="width:16.6667%;background:${colors.seo}"></span><span style="width:58.3333%;background:${colors.sem}"></span></div><div class="sample-legend"><span><i style="background:${colors.geo}"></i>真实引擎 3 · 25%</span><span><i style="background:${colors.seo}"></i>人工核实 2 · 16.7%</span><span><i style="background:${colors.sem}"></i>模拟人设 7 · 58.3%</span></div>`;}
function sampleTable(){return table(['编号 / 日期','样本来源','问题','提及品牌'],samples.filter(r=>state.sampleFilter==='all'||r[2]===state.sampleFilter).map(r=>[`${r[0]} · ${r[1]}`,`<span class="badge ${r[2]==='模拟人设'?'amber':'purple'}">${r[2]}</span>`,r[3],r[4]?'是':'否']));}
function renderQuality(){$('#page-quality').innerHTML=`<div class="page-heading"><div><p class="eyebrow">DATA HEALTH / 数据健康</p><h1 id="qualityTitle">先知道数据能回答什么。</h1><p class="lead">当前处于演示环境。来源口径可查看，真实连接状态单独标注。</p></div></div><div class="quality-alert"><h2>GEO 样本构成会改变你对结果的理解。</h2><p>7/12 条样本为模拟人设。真实探测的品牌提及为 1/3，前期可比样本缺失，不能给出可信增长判断。</p></div><div class="quality-grid">${[['sem','SEM · 投放','百度官方报表','花费、点击、转化按同一账户与日期汇总。报表转化不代表已核实的有效商机。'],['seo','SEO · 内容','GSC + 排名 / 重抓记录','GSC 点击是 Google 口径，百度自然排名单独呈现；图片是否修复看重新抓取记录。'],['geo','GEO · 可见度','来源混合，需分别统计','真实引擎、人工核实、模拟人设各自保留。人工记录不自动等价于连续探测。']].map(([k,n,s,d])=>`<article class="quality-card"><span class="badge ${k==='geo'?'amber':'green'}">${s}</span><h2 style="color:${colors[k]}">${n}</h2><p>${d}</p><p>示例窗口：08.31 — 09.06</p><div class="connection">真实连接：未连接 · 最新拉取：暂无</div><button class="text-button" data-action="evidence" data-key="${k}">查看示例明细 ↗</button></article>`).join('')}</div><section class="surface" style="margin-top:20px"><div class="section-heading"><h2>GEO 的 12 条样本，逐条分清楚</h2><span>示例记录</span></div>${sampleBar()}<div class="filter-tabs" style="margin-top:18px">${[['all','全部 12'],['真实引擎','真实引擎 3'],['人工核实','人工核实 2'],['模拟人设','模拟人设 7']].map(([v,t])=>`<button class="${state.sampleFilter===v?'active':''}" data-sample="${v}">${t}</button>`).join('')}</div><div id="sampleTable">${sampleTable()}</div></section><details><summary>供接入方查看：数据契约与发现 / 解释边界</summary><p>驾驶舱仅通过模块接口取数，不直连数据库。跨模块判断由确定性、可测试的规则产出；对话解释已有信号。当前内容为固定演示场景，没有生产规则执行。<code>mock_persona</code> 不进入真实可见度；缺失历史时 <code>trend_7d = null</code>。</p></details>`;}
function showDialog(eyebrow,html){$('#dialogEyebrow').textContent=eyebrow;$('#dialogBody').innerHTML=html;const heading=$('#dialogBody h2');if(heading){heading.id='dialogTitle';$('#detailDialog').setAttribute('aria-labelledby','dialogTitle');}if(!$('#detailDialog').open)$('#detailDialog').showModal();$('#detailDialog').scrollTop=0;}
function closeDialog(){$('#detailDialog').close();state.dialog=null;}
function showEvidence(key){state.dialog={type:'evidence',key};let title,lead,facts,rows,headers,note;
if(key==='sem'){title='花费集中在哪里？';lead='示例词组：智能仓储解决方案 · 百度投放 · 08.31 — 09.06。逐日记录与简报使用同一份数据。';facts=[[money(sum(weekly.topic)),'词组花费'],['34%','占总花费 42,110 元'],['2 次','报表转化 · 有效性待核对']];headers=['日期','账户花费','词组花费','词组点击','报表转化'];rows=dates.map((d,i)=>[d,money(weekly.spend[i]),money(weekly.topic[i]),weekly.clicks[i],weekly.conversions[i]]);note='报表转化成本为 ¥7,160/次。仅 2 次转化，尚未核实有效商机，不能仅凭花费集中直接调预算。';}
else if(key==='seo'){title='自然点击来自哪里？';lead='示例内容《智能仓储如何降低人力成本》 · GSC 点击与百度排名分别呈现。';facts=[['380 次','本周 GSC 内容点击'],['304 次','前一周 GSC 内容点击'],['第 4 位','百度 PC 期末排名']];headers=['日期','内容 GSC 点击','百度 PC 排名','数据范围'];rows=dates.map((d,i)=>[d,weekly.organic[i],weekly.rank[i],'同一示例内容 / 词组']);note='GSC 点击不是百度自然点击。排名改善也不证明付费转化替代，需补充落地页与有效商机归因。';}
else if(key==='geo'){title='把模拟样本拿开后，还剩多少证据？';lead='所有记录均为示例。真实引擎 3 条中 1 条提及品牌；人工核实 2 条中 1 条提及；模拟 7 条中 3 条提及。';facts=[['1 / 3','真实引擎提及 · 33.3%'],['1 / 2','人工核实提及 · 50%'],['3 / 7','模拟人设提及 · 42.9%']];headers=['编号','日期','来源','品牌提及'];rows=samples.map(r=>[r[0],r[1],r[2],r[4]?'是':'否']);note='5/12 = 41.7% 只是混合样本描述，不作为真实可见度。前一周可比样本缺失，趋势未知。';}
else if(key==='images'){title='图片修复的 60%，是怎么验收的？';lead='示例批次 IMG-0901 · 总计 20 张。审核状态与重新抓取结果分开保存。';facts=[['12 张','复查确认修复'],['5 张','等待重新抓取'],['3 张','复查未通过']];headers=['图片编号','建议审核','重新抓取结果','最后复查'];rows=Array.from({length:20},(_,i)=>[`IMG-${String(i+1).padStart(2,'0')}`,'已通过',i<12?'<span class="green-text">确认修复</span>':i<17?'待复查':'<span class="amber-text">仍未通过</span>',i<12?'09-06 09:20':i<17?'暂无':'09-06 09:25']);note='12 / 20 = 60%。剩余 8 张需保留复查结果与未通过原因，整批任务当前待检查结果。';}
else if(key==='titles'){title='标题修复：6 个页面的前后对照';lead='历史示例 EX-101 · 对同一组页面重新抓取确认，而不是由操作人点击完成。';facts=[['6 → 0','缺失标题页面数'],['6 / 6','复查通过'],['09-05 16:40','示例观测时间']];headers=['页面','修复前','重新抓取','复查结果'];rows=Array.from({length:6},(_,i)=>['产品页 '+(i+1),'标题缺失','09-05 16:40','具备非空标题']);note='验收范围仅为这 6 个页面的标题缺失修复，不代表其排名或转化已改善。';}
else{title='调整预算之前，还缺什么？';lead='把观察变成决策，需要补齐可比性。';facts=[['同词组','确认查询词与内容映射'],['同窗口','固定周期与范围'],['有效转化','核对线索质量']];headers=['核验项','当前状态','需要的证据'];rows=[['账户 / 客户','示例已对齐','同一客户及授权范围'],['搜索引擎','尚未对齐','百度投放与 Google 点击分别分析'],['付费转化质量','待核对','2 次报表转化的有效性'],['内容承接','待核对','落地页与可归因线索记录']];note='不使用 GEO 混合样本证明需求。阶段2需由业务专家定义并验证规则后，才能产生正式信号。';}
showDialog('EVIDENCE / 依据明细',`<h2>${title}</h2><p class="dialog-lead">${lead}</p><div class="detail-facts">${facts.map(([v,l])=>`<div class="fact"><strong>${v}</strong><span>${l}</span></div>`).join('')}</div>${table(headers,rows)}<div class="evidence-note">${note}</div><div class="dialog-footer"><span class="footnote">本地示例 · 不是生产记录</span>${key==='titles'?'<button class="primary-button" data-task="EX-101">返回验收行动 →</button>':`<button class="primary-button" data-action="discussEvidence" data-key="${key}">围绕这些依据讨论 →</button>`}</div>`);}

const chartMeta={spend:{name:'SEM · 账户花费',color:colors.sem,unit:'元',source:'百度推广报表口径',base:5700},topic:{name:'SEM · 智能仓储词组花费',color:colors.sem,unit:'元',source:'百度推广词组报表口径',base:1900},organic:{name:'SEO · 相关内容自然点击',color:colors.seo,unit:'次',source:'Google Search Console 口径',base:40},rank:{name:'SEO · 百度 PC 排名',color:colors.geo,unit:'位',source:'百度排名快照，数值越小排名越好',base:15}};
function chartData(key,range){const m=chartMeta[key];const earlier=Array.from({length:83},(_,i)=>Math.max(1,Math.round(m.base*(.85+(i%7)*.025+i*.001))));if(key==='spend')earlier.splice(-7,7,5500,5550,5600,5650,5540,5600,5600);if(key==='organic')earlier.splice(-7,7,38,40,42,43,45,46,50);return [...earlier,...weekly[key]].slice(-range);}
function showChart(key=state.chartMetric,range=7){if(!chartMeta[key]||![7,30,90].includes(range))return;state.chartMetric=key;state.chartRange=range;state.dialog={type:'chart'};const meta=chartMeta[key],data=chartData(key,range),low=Math.max(0,Math.floor(Math.min(...data)*.9)),high=Math.ceil(Math.max(...data)*1.1),span=high-low||1;
const coords=data.map((v,i)=>[48+i*587/(data.length-1),15+155*(1-(v-low)/span)]),path=coords.map(([x,y],i)=>`${i?'L':'M'}${x.toFixed(1)} ${y.toFixed(1)}`).join(' ');
const ticks=Array.from({length:4},(_,i)=>{const y=15+i*155/3,v=high-i*span/3;return `<line x1="48" x2="635" y1="${y}" y2="${y}" stroke="#263243" stroke-dasharray="3 4"/><text x="40" y="${y+3}" text-anchor="end" class="chart-label">${Math.round(v)}</text>`;}).join('');
const dateFor=i=>{const d=new Date(Date.UTC(2026,8,6-range+1+i));return `${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(d.getUTCDate()).padStart(2,'0')}`;};
showDialog('TREND / 趋势与原始值',`<h2>${meta.name}</h2><p class="dialog-lead">${meta.source} · 示例序列 · ${dateFor(0)} — 09-06</p><div class="chart-tools"><div class="filter-tabs">${[7,30,90].map(r=>`<button data-chart-range="${r}" class="${range===r?'active':''}">近${r}天</button>`).join('')}</div><label class="muted" style="font-size:11px">指标 <select id="chartMetric" aria-label="选择趋势指标">${Object.entries(chartMeta).map(([k,m])=>`<option value="${k}" ${k===key?'selected':''}>${m.name}</option>`).join('')}</select></label></div><svg class="chart-svg" viewBox="0 0 650 200" role="img" aria-label="${meta.name}近${range}天趋势，单位${meta.unit}">${ticks}<path d="${path} L635 170 L48 170 Z" fill="${meta.color}" opacity=".07"/><path d="${path}" fill="none" stroke="${meta.color}" stroke-width="2"/>${range<=7?coords.map(([x,y],i)=>`<circle cx="${x}" cy="${y}" r="3" fill="${meta.color}"><title>${dateFor(i)}：${data[i]} ${meta.unit}</title></circle>`).join(''):''}<text x="48" y="192" class="chart-label">${dateFor(0)}</text><text x="635" y="192" text-anchor="end" class="chart-label">09-06</text></svg><div class="detail-facts"><div class="fact"><strong>${num(data.at(-1))}</strong><span>期末值 · ${meta.unit}</span></div><div class="fact"><strong>${num(key==='rank'?Math.min(...data):sum(data))}</strong><span>${key==='rank'?'期间最好排名':'期间合计'} · ${meta.unit}</span></div><div class="fact"><strong>${num(sum(data)/data.length)}</strong><span>期间均值 · ${meta.unit}</span></div></div><details><summary>展开逐日示例记录（${range} 条）</summary>${table(['日期',`${meta.name}（${meta.unit}）`],data.map((v,i)=>[dateFor(i),num(v)]))}</details><p class="footnote">7 / 30 / 90 天为同一套示例序列的切片。本周数据与简报一致；历史示例用于验证交互，不用于业务判断。</p>`);}
function showDraft(existingId){const existing=existingId?localDrafts.find(t=>t.id===existingId&&t.status==='draft'):null,issue=issues[existing?.issue||state.issue];state.dialog={type:'draft',id:existing?.id,issue:issue.id};
showDialog('ACTION / 拟定行动',`<h2>${existing?'编辑行动草稿':'把下一步说清楚，再交给执行方。'}</h2><p class="dialog-lead">关联：${issue.topic}。这里保存待确认方案，执行方不会收到派发；正式接入后仍需权限与确认。</p><form id="draftForm"><div class="choice-cards">${[['verify','先核验','补齐依据再决定，适合当前证据不足的情况。'],['observe','继续观察','保留当前做法，约定复核日期与关注指标。'],...(issue.id==='allocation'?[['experiment','规划小范围试验','只拟方案和预算上限，不直接执行调价。']]:[])].map(([k,t,d])=>`<label class="choice-card"><input type="radio" name="plan" value="${k}" ${(existing?.plan||'verify')===k?'checked':''}>${t}<p>${d}</p></label>`).join('')}</div><div id="budgetPlan" class="budget-plan" ${existing?.plan==='experiment'?'':'hidden'}><label for="budgetReduction">试验账户日预算上限 · 当前示例 ¥7,000</label><input id="budgetReduction" name="reduction" type="range" min="0" max="20" step="5" value="${esc(existing?.reduction??10)}"><div class="budget-values" id="budgetValues"></div><p class="footnote">仅为预算上限的算术测算，不是实际节省或效果预测。执行前需复核转化、审批与回滚条件。</p></div><div class="form-grid"><label class="form-field full">行动标题<input name="title" required maxlength="100" value="${esc(existing?.title||issue.task)}"></label><label class="form-field">执行方<select name="owner">${['SEM / SEO 联合运营','SEM 运营','SEO 内容运营','GEO 运营'].map(o=>`<option ${(existing?.owner||issue.owner)===o?'selected':''}>${o}</option>`).join('')}</select></label><label class="form-field">复核日期<input name="due" type="date" required min="2026-09-06" value="${esc(existing?.due||'2026-09-09')}"></label><label class="form-field full">决策备注<textarea name="note" maxlength="1000" placeholder="为什么这样做？哪些边界需要执行方注意？">${esc(existing?.note||'')}</textarea></label></div><h3 style="margin-top:20px">需要回来的证据</h3><ul class="acceptance-list" id="planCriteria">${criteriaFor(issue,existing?.plan||'verify').map(c=>`<li>${c}</li>`).join('')}</ul><div class="dialog-footer"><span class="footnote">${existing?'修改同一份草稿':'同事项、同方案只保留一份未撤回方案'} · 刷新保留，关闭标签页后清除</span><button class="primary-button" type="submit">保存行动草稿</button></div></form>`);updateBudget();}
function criteriaFor(issue,plan){
 if(plan==='experiment')return [...issue.criteria.slice(0,2),'试验前确认有效转化基线、7天观察窗与参与范围','执行前由负责人确认停止阈值与回滚方案；记录每次变更','对照原始指标评估效果，预算上限差额不等于节省金额'];
 if(plan==='observe')return ['复核日期前保留当前策略，不安排预算或内容变更',...issue.criteria.slice(0,2),'复核时对照同口径数据决定继续观察或进入核验'];
 return issue.criteria;
}
function updateBudget(){const r=$('#budgetReduction');if(!r)return;const reduction=Number(r.value),cap=7000*(1-reduction/100);$('#budgetValues').innerHTML=`<span>下调 ${reduction}%</span><strong>${money(cap)} / 日</strong><span>7 天上限减少 ${money((7000-cap)*7)}</span>`;}
function saveDraft(form){if(!form.reportValidity())return;const data=new FormData(form),issue=state.dialog.issue,id=state.dialog.id,plan=data.get('plan'),title=data.get('title').trim();if(!title){toast('请输入行动标题。');return;}const duplicate=localDrafts.find(t=>!t.sourceObject&&t.issue===issue&&t.plan===plan&&t.status==='draft'&&t.id!==id);if(duplicate){closeDialog();navigate('tasks');toast('已有相同事项的草稿，可直接编辑。');showTask(duplicate.id);return;}const task={id:id||'LOCAL-'+Date.now().toString(36).toUpperCase(),title,issue,plan,reduction:Number(data.get('reduction')),owner:data.get('owner'),due:data.get('due'),note:data.get('note').trim(),status:'draft',criterion:criteriaFor(issues[issue],plan).join('；')};if(id)localDrafts=localDrafts.map(t=>t.id===id?task:t);else localDrafts.unshift(task);const saved=persist();closeDialog();state.filter='all';$('#taskSearch').value='';navigate('tasks');if(saved)toast(id?'草稿已更新，尚未交给负责人。':'草稿已保存至当前标签页，尚未交给负责人。');addMessage('assistant',`行动草稿已${id?'更新':'保存'}：<strong>${esc(title)}</strong>。执行方为 ${esc(task.owner)}，约定 ${esc(task.due)} 复核。当前没有真实派发。`,[{label:'查看这项行动',task:task.id}]);}
function showTask(id){const t=allTasks().find(t=>t.id===id);if(!t)return;state.dialog={type:'task',id};const local=id.startsWith('LOCAL-'),stage=({draft:0,cancelled:0,active:1,evidence:2,verified:3})[t.status];showDialog('ACTION DETAIL / 行动详情',`<span class="eyebrow">${esc(t.id)}</span><h2>${esc(t.title)}</h2>${badge(t.status)}<div class="step-line">${['拟定行动','执行处理中','核对结果证据','效果验收'].map((s,i)=>`<div class="step ${i<stage?'done':i===stage?'current':''}">${String(i+1).padStart(2,'0')} / ${s}</div>`).join('')}</div><div class="detail-facts"><div class="fact"><span>执行方</span><p>${esc(t.owner)}</p></div><div class="fact"><span>复核日期</span><p>${esc(t.due)}</p></div><div class="fact"><span>关联事项</span><p>${esc(issues[t.issue].tag)}</p></div></div><h3>决策记录</h3><p class="dialog-lead">${esc(t.note||'未填写备注。')}</p>${t.plan==='experiment'?`<div class="evidence-note">试验草稿：日预算上限 ${money(7000*(1-t.reduction/100))}，相对示例 ¥7,000 下调 ${num(t.reduction)}%。仅规划，未执行。</div>`:''}<h3>完成标准</h3><p class="dialog-lead">${esc(t.criterion)}</p><h3>${local?'执行与证据':'当前证据 · 演示记录'}</h3><div class="evidence-note">${local?'尚未交给负责人，暂无执行记录及效果证据。保存草稿不等于任务执行或完成。':esc(t.evidence)}</div>${!local?`<p class="footnote">示例观测时间：${esc(t.observed)} · 未连接真实模块</p>`:''}<div class="dialog-footer">${t.id==='EX-101'?'<button class="text-button" data-action="evidence" data-key="titles">查看标题复查记录 ↗</button>':`<button class="text-button" data-action="taskContext" data-key="${t.issue}">回到关联事项 ↗</button>`}<div class="button-row">${local&&t.status==='draft'?`<button class="secondary-button" data-action="withdraw" data-key="${esc(t.id)}">撤回方案</button><button class="primary-button" data-action="editDraft" data-key="${esc(t.id)}">修改方案</button>`:local&&t.status==='cancelled'?`<button class="secondary-button" data-action="restoreDraft" data-key="${esc(t.id)}">恢复方案</button>`:`<button class="primary-button" data-action="discussTask" data-key="${esc(t.id)}">请助手解释进度</button>`}</div></div>`);}
function renderModule(){const k=state.module,info=({sem:['SEM · 投放经营','钱花到哪里，带回了什么？'],seo:['SEO · 内容与搜索','从内容产出，看到流量与验收。'],geo:['GEO · AI 可见度','先分清来源，再看品牌被怎样提及。']})[k];let metrics,content,insight;
if(k==='sem'){metrics=[[money(sum(weekly.spend)),'账户本周花费'],[money(sum(weekly.topic)),'智能仓储词组花费'],['837','词组点击'],['2','词组报表转化']];insight='智能仓储词组占 34% 花费，报表转化成本 ¥7,160。转化有效性待核对。';content=`<div class="section-heading"><h2>花费结构</h2><button class="text-button" data-action="chart" data-key="spend">查看账户趋势 ↗</button></div>${table(['词组 / 范围','本周花费','占比','查看'],[['智能仓储解决方案','¥14,320','34%','<button class="table-action" data-action="evidence" data-key="sem">逐日记录 ↗</button>'],['其他词组（合计）','¥27,790','66%','<span class="muted">本次示例未拆分</span>'],['账户合计','¥42,110','100%','<button class="table-action" data-action="chart" data-key="spend">趋势 ↗</button>']])}<div class="section-heading" style="margin-top:24px"><h2>执行前需核对</h2></div><div class="surface"><p class="muted">转化质量、预算上限与操作审批相互独立。当前示例不提供真实账户调价入口。</p><button class="text-button" data-action="draft" data-key="allocation">拟定联合核验行动 ↗</button></div>`;}
else if(k==='seo'){metrics=[['380','相关内容本周 GSC 点击'],['+25%','较前一周 304 次'],['4','百度 PC 期末排名'],['60%','图片复查确认修复率']];insight='内容自然点击增长，但与百度付费流量不同口径。这批图片还有 8 张待完成核验。';content=`<div class="section-heading"><h2>内容与排名</h2><button class="text-button" data-action="chart" data-key="organic">查看点击趋势 ↗</button></div>${table(['示例内容 / 词组','GSC 本周点击','百度 PC 排名','查看'],[['智能仓储如何降低人力成本','380','13 → 4','<button class="table-action" data-action="evidence" data-key="seo">逐日依据 ↗</button>']])}<div class="section-heading" style="margin-top:24px"><h2>图片修复：审核之后，复查之前</h2><button class="text-button" data-task="EX-104">跟进行动 ↗</button></div><div class="surface"><div class="stacked-bar"><span style="width:60%;background:${colors.seo}"></span><span style="width:25%;background:${colors.sem}"></span><span style="width:15%;background:#b18bad"></span></div><div class="sample-legend"><span>12 张确认修复</span><span>5 张待复查</span><span>3 张未通过</span></div><button class="text-button" data-action="evidence" data-key="images" style="margin-top:14px">查看 20 张图片检查详情 ↗</button></div>`;}
else{metrics=[['12','全部示例样本'],['3','真实引擎探测'],['1 / 3','真实引擎品牌提及'],['未知','与上周的可比趋势']];insight='混合提及率 41.7% 不等于真实可见度。真实引擎、人工核实与模拟人设必须单独统计。';content=`<section class="surface"><div class="section-heading"><h2>样本构成</h2><button class="text-button" data-page="quality">逐条检查来源 ↗</button></div>${sampleBar()}</section><div class="section-heading" style="margin-top:24px"><h2>品牌提及口径</h2></div>${table(['来源','样本数','提及数','提及率'],[['真实引擎','3','1','33.3%'],['人工核实','2','1','50%'],['模拟人设','7','3','42.9%'],['混合描述（不用于真实结论）','12','5','41.7%']])}<p class="footnote">真实引擎仅 3 条。没有同引擎、同问题的前期可比样本，趋势保持未知。</p>`;}
$('#page-module').innerHTML=`<div class="page-heading"><div><p class="eyebrow">MODULE EXPLORER / 模块经营</p><h1 id="moduleTitle">${info[0]}</h1><p class="lead">${info[1]} · 08.31 — 09.06 · 示例口径</p></div><button class="text-button" data-page="overview">← 返回经营简报</button></div><div class="module-tabs">${['sem','seo','geo'].map(m=>`<button class="${k===m?'active':''}" data-module="${m}">${m.toUpperCase()}</button>`).join('')}</div><div class="module-kpis">${metrics.map(([v,l])=>`<div class="summary-cell"><b>${v}</b><span>${l}</span></div>`).join('')}</div><div class="module-insight"><span>${insight}</span><button class="text-button" data-action="moduleDiscuss" data-key="${k}">和助手讨论 ↗</button></div>${content}<details><summary>数据口径与接入说明</summary><p>${k==='sem'?'示例映射百度关键词报表；花费与报表转化不构成有效商机证明。':k==='seo'?'GSC 点击、百度排名及图片重新抓取各有独立来源，不能混同口径。':'GEO 默认 mock_persona 属于模拟样本。实际接入需保留 sample_mode、simulated 和观测时间。'} 本页不查询数据库或模块接口。</p></details>`;}
function addMessage(role,html,actions=[]){const item=document.createElement('div');item.className='message '+(role==='user'?'user':'assistant-message');if(role==='user')item.textContent=html;else item.innerHTML=`<div class="speaker">获客推广AI智能体 <span>· 示例解释</span></div><div>${html}</div>${actions.length?`<div class="message-actions">${actions.map(a=>`<button ${a.task?`data-task="${esc(a.task)}"`:`data-action="${esc(a.action)}" ${a.key?`data-key="${esc(a.key)}"`:''}`}>${esc(a.label)}</button>`).join('')}</div>`:''}`;$('#chatStream').append(item);$('#chatStream').scrollTop=$('#chatStream').scrollHeight;}
function updateSuggestions(){$('#chatSuggestions').innerHTML=['依据够不够？','还有哪些选择？','上次的事做完了吗？'].map(q=>`<button data-question="${q}">${q}</button>`).join('');}
function resetChat(){$('#chatStream').replaceChildren();if(state.issue!=='allocation'){const i=issues[state.issue];addMessage('assistant',`<p>现在关注：<strong>${i.topic}</strong>。</p><p>${i.body}</p>`,[{label:'查看依据',action:'evidence',key:state.issue==='images'?'images':'geo'},{label:'拟定下一步',action:'draft',key:state.issue}]);updateSuggestions();return;}addMessage('assistant','<p>本周先看<strong>一项资源分配判断</strong>，再跟进执行。</p><p>智能仓储词组占了 34% 的投放花费。相关内容也有自然点击，但<strong>现在还不能直接说该减预算</strong>。</p><p>右侧把依据与缺口放在一起。我们可以先看明细，再把要核验的事交代清楚。</p>',[{label:'看花费依据',action:'evidence',key:'sem'},{label:'看行动进度',action:'tasks'}]);updateSuggestions();}
function reply(question){addMessage('user',question);const i=issues[state.issue];if(/上次|进度|做完|任务|待办|台账/.test(question)){addMessage('assistant','这批图片<strong>尚未整体验收</strong>：20 张中 12 张确认修复，5 张待复查、3 张未通过。另一项产品页标题修复已有 6/6 页重新抓取通过的示例证据。<p>“有人处理了”与“实际效果已验证”要分开看。</p>',[{label:'这批图片验收',task:'EX-104'},{label:'已核验的标题修复',task:'EX-101'}]);}
else if(/选择|方案|减|预算|调整|试验/.test(question)){addMessage('assistant',state.issue==='allocation'?'<p>有三种路径：<strong>先核验</strong>，补齐词组与有效转化；<strong>继续观察</strong>，约定复核日期；或<strong>规划小范围试验</strong>，明确预算上限与回滚条件。</p><p>当前更适合先核验。试验测算只计算预算上限，不预测真实节省。</p>':'可以先补齐验收依据，或保留观察并约定复核日期。当前最明确的下一步是：<strong>'+i.next+'</strong>。',[{label:'比较并拟定行动',action:'draft',key:state.issue}]);}
else if(/GEO|geo|样本|真实|模拟|可见度/.test(question)){addMessage('assistant','本周 12 条示例样本中，<strong>真实引擎 3 条、人工核实 2 条、模拟人设 7 条</strong>。真实引擎单独统计为 1/3 提及品牌。<p>没有可比前期样本，不能给出增长结论，也不能证明行业需求。</p>',[{label:'逐条看样本',action:'evidence',key:'geo'},{label:'检查数据健康',action:'quality'}]);}
else if(/依据|为什么|解释|风险|判断|证据|点击|花费|修复/.test(question)){addMessage('assistant',`<p><strong>${i.title}</strong></p><p>${i.body}</p><p>${i.boundary}</p>`,[{label:'查看原始示例记录',action:'evidence',key:state.issue==='allocation'?'sem':state.issue==='images'?'images':'geo'},{label:'拟定下一步',action:'draft',key:state.issue}]);}
else addMessage('assistant','当前原型能讨论<strong>本周三个事项的依据、可选待办与结果进度</strong>。这个问题尚不在示例回答范围内，我不会补造数据。<p>可以从下方选一个方向继续。</p>',[{label:'解释当前依据',action:'discuss'},{label:'查看待办与进度',action:'tasks'}]);updateSuggestions();}

document.addEventListener('click',e=>{const b=e.target.closest('button,a.brand');if(!b)return;
if(b.matches('a.brand')){e.preventDefault();navigate('overview');return;}
if(b.dataset.page){navigate(b.dataset.page);return;}if(b.dataset.mode){setMode(b.dataset.mode);return;}if(b.dataset.issue){setIssue(b.dataset.issue);return;}if(b.dataset.module){state.module=b.dataset.module;navigate('module');return;}if(b.dataset.task){showTask(b.dataset.task);return;}
if(b.dataset.filter){state.filter=b.dataset.filter;renderTasks();return;}if(b.dataset.sample){state.sampleFilter=b.dataset.sample;$('#sampleTable').innerHTML=sampleTable();$$('[data-sample]').forEach(x=>x.classList.toggle('active',x.dataset.sample===state.sampleFilter));return;}if(b.dataset.chartRange){showChart(state.chartMetric,Number(b.dataset.chartRange));return;}if(b.dataset.question){reply(b.dataset.question);return;}
const a=b.dataset.action,k=b.dataset.key;
if(a==='closeDialog')closeDialog();else if(a==='evidence')showEvidence(k);else if(a==='chart')showChart(k);else if(a==='draft'){if(issues[k]){state.issue=k;renderIssues();}showDraft();}
else if(a==='discuss'){showChat();reply('解释当前事项的依据');}
else if(a==='discussEvidence'){closeDialog();setIssue(k==='geo'?'visibility':k==='images'?'images':'allocation');showChat();reply(k==='geo'?'GEO 样本可靠吗？':k==='images'?'图片修复依据是什么？':'当前依据够不够？');}
else if(a==='quality')navigate('quality');else if(a==='tasks')navigate('tasks');else if(a==='focusCurrent')navigate('overview');else if(a==='newChat')resetChat();
else if(a==='showChat'){if(innerWidth<=620&&state.mode==='chat-focus')setMode('fullscreen');else showChat();}
else if(a==='editDraft')showDraft(k);else if(a==='taskContext'){closeDialog();setIssue(k);}
else if(a==='moduleDiscuss'){setIssue(k==='geo'?'visibility':k==='seo'?'images':'allocation');showChat();reply('解释当前事项的依据');}
else if(a==='discussTask'){const t=allTasks().find(t=>t.id===k);closeDialog();showChat();addMessage('user','这项行动做到哪一步了？');addMessage('assistant',`<strong>${esc(t.title)}</strong><p>${esc(t.evidence)}</p><p>完成标准：${esc(t.criterion)}</p>`,[{label:'查看行动记录',task:k}]);}
else if(a==='resetTaskFilter'){state.filter='all';$('#taskSearch').value='';renderTasks();}
else if(a==='withdraw'||a==='restoreDraft'){const t=localDrafts.find(t=>t.id===k);if(!t)return;if(a==='restoreDraft'&&localDrafts.some(x=>x.id!==k&&x.status==='draft'&&(t.sourceObject ? x.sourceObject?.key===t.sourceObject.key&&x.sourceObject?.row===t.sourceObject.row : !x.sourceObject&&x.issue===t.issue&&x.plan===t.plan))){toast('已有同方案草稿，请先编辑或撤回现有草稿。');return;}t.status=a==='withdraw'?'cancelled':'draft';persist();renderTasks();showTask(k);toast(a==='withdraw'?'草稿已撤回，可随时恢复。':'草稿已恢复，尚未交给负责人。');}
});
document.addEventListener('submit',e=>{if(e.target.id==='draftForm'){e.preventDefault();saveDraft(e.target);}if(e.target.id==='chatForm'){e.preventDefault();const v=$('#chatInput').value.trim();if(v){$('#chatInput').value='';reply(v);}}});
document.addEventListener('change',e=>{if(e.target.id==='chartMetric')showChart(e.target.value,state.chartRange);if(e.target.name==='plan'){$('#budgetPlan').hidden=e.target.value!=='experiment';const issue=issues[state.dialog.issue];$('#planCriteria').innerHTML=criteriaFor(issue,e.target.value).map(c=>`<li>${c}</li>`).join('');$('#draftForm input[name="title"]').value=e.target.value==='observe'?'观察并复核：'+issue.topic:e.target.value==='experiment'?'规划智能仓储词组小范围预算试验':issue.task;}});
$('#taskSearch').addEventListener('input',renderTasks);document.addEventListener('input',e=>{if(e.target.id==='budgetReduction')updateBudget();});
$('#issueTabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const ids=Object.keys(issues),index=ids.indexOf(state.issue);const next=e.key==='Home'?0:e.key==='End'?ids.length-1:(index+(e.key==='ArrowRight'?1:-1)+ids.length)%ids.length;setIssue(ids[next]);$('#issue-'+ids[next]).focus();});
$('#chatInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('#chatForm').requestSubmit();}});
$('#detailDialog').addEventListener('cancel',()=>{state.dialog=null;});$('#detailDialog').addEventListener('click',e=>{if(e.target!==$('#detailDialog'))return;const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();});
const handle=$('#resizeHandle');let resizing=false;
function resizeTo(width){const v=Math.min(500,Math.max(260,width));document.documentElement.style.setProperty('--chat-width',v+'px');handle.setAttribute('aria-valuenow',String(Math.round(v)));}
handle.addEventListener('pointerdown',e=>{if(state.mode!=='split')return;resizing=true;handle.setPointerCapture(e.pointerId);e.preventDefault();});handle.addEventListener('pointermove',e=>{if(resizing)resizeTo(e.clientX);});handle.addEventListener('pointerup',()=>{resizing=false;});handle.addEventListener('pointercancel',()=>{resizing=false;});handle.addEventListener('keydown',e=>{if(state.mode==='split'&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();resizeTo(Number(handle.getAttribute('aria-valuenow'))+(e.key==='ArrowRight'?20:-20));}});
window.addEventListener('resize',()=>setMode(state.mode));
renderMetrics();renderIssues();renderFollowups();renderTasks();resetChat();setMode(state.mode);
