/* Conversation is the default workspace; data supplies the supporting context. */
const contextualBusinessReply=reply;
const conversationPrompts=['现在整体情况怎么样？','投放的钱花在哪里？','SEO 内容进展怎么样？','GEO 品牌表现可靠吗？','上次安排的事完成了吗？'];
function conversationSuggestions(){ $('#chatSuggestions').innerHTML=conversationPrompts.map(q=>`<button data-question="${q}">${q}</button>`).join(''); }
function conversationOverview(){panels.forEach(p=>p.el.hidden=true);dock();focusedPanel=null;$('#contextTitle').textContent='诺德新材料 · 本周经营';navigate('dashboard');addMessage('assistant','<p>本周先看三件事：</p><p><strong>投放：</strong>账户花费 ¥42,110，较前周增加 7.9%。智能仓储词组花费占 34%，需要结合有效线索判断。</p><p><strong>搜索与内容：</strong>相关内容 GSC 点击 380，较前周增加 25%；这批图片还有 5 张待复查、3 张未通过。</p><p><strong>AI 品牌：</strong>原始样本混有模拟与人工来源，当前没有正式可见度结论。</p><p>右侧展示对应数据。你可以接着问原因、查明细，或讨论下一步。</p>',[{label:'核对投放明细',action:'conversation',key:'spend'},{label:'跟进图片修复',action:'conversation',key:'health'},{label:'查看行动进度',action:'conversation',key:'execution'}]);}
function conversationEvidence(key){navigate('dashboard');openPanel(key,boardScope);const prior=boardScope==='prior';const answers={spend:prior?'前一周账户花费为 ¥39,040；该周缺少逐日明细，不能进一步拆解。':'本周账户花费 ¥42,110，其中智能仓储词组 ¥14,320，占约 34%。词组记录 837 次点击、2 次转化。先核对这两次转化的业务有效性，再决定是否调整预算。',organic:prior?'前一周相关内容 GSC 点击为 304；该周没有逐日明细示例。':'相关内容本周 GSC 点击 380，较前周增加 25%。百度 PC 期末排名为 4。点击和排名来自不同搜索引擎，应分别核对。',visibility:'正式 GEO 指标采用 08.24—08.30 完整自然周，目前未接入。本周 12 条原始样本包含 3 条真实引擎标签、2 条人工和 7 条模拟记录；这不是正式可见度，也不能证明增长。',health:prior?'此前一周没有这批图片的复查演示记录。':'这批图片共 20 张：12 张复查通过，5 张待复查，3 张未通过。应先处理剩余 8 张，再核对整个批次是否满足验收条件。',execution:'图片修复批次尚未整体验收，GEO 基线仍在准备。产品页标题修复有 6/6 页复查通过的示例记录。当前状态与业务日期筛选分开记录。'};addMessage('assistant',`<p>${answers[key]}</p><p>对应依据已在右侧打开，你可以边看边继续问我。</p>`,key==='spend'?[{label:'讨论预算方案',action:'conversation',key:'plan'}]:key==='health'?[{label:'查看批次行动',task:'EX-104'}]:key==='execution'?[{label:'进入待办与进度',action:'tasks'}]:key==='organic'?[{label:'查看内容对象',action:'conversation',key:'content'}]:[{label:'查看基线行动',task:'EX-103'}]);}
function conversationPlan(){state.issue='allocation';renderIssues();addMessage('assistant','<p>可以先核验有效线索、继续观察，或拟定小范围预算试验。当前证据更适合先核验，不能直接从花费增加推断应减预算。</p><p>拟定时明确范围、负责人、复核日期和验收条件。保存草稿后仍需客户确认，当前原型不会实际执行。</p>',[{label:'拟定预算核验 / 试验草稿',action:'draft',key:'allocation'},{label:'再看花费依据',action:'conversation',key:'spend'}]);}
function routeConversation(key){showChat();if(key==='overview'){boardScope='week';boardModule='all';renderDashboard();conversationOverview();}else if(key==='plan')conversationPlan();else if(key==='content'){navigate('dashboard');openPanel('seo:6',boardScope);addMessage('assistant','<p>内容列表已在右侧打开。选择文章可以核对审核状态、目标主题和发布证据，并拟定关联行动。列表是独立流程演示，不计入首页指标。</p>');}else conversationEvidence(key);conversationSuggestions();$('#chatInput').focus();}
reply=function(question){let key=null;if(/整体|全局|总体|现在情况|本周情况/.test(question))key='overview';else if(/预算|减.*投放|试验方案/.test(question))key='plan';else if(/上次|安排的事|行动进度/.test(question))key='execution';else if(/GEO|geo|AI.*品牌|品牌表现/.test(question))key='visibility';else if(/SEO|seo|自然搜索/.test(question))key='organic';else if(/投放.*钱|花费|花在哪里|SEM|sem/.test(question))key='spend';else if(/图片.*修复|图片.*进度/.test(question))key='health';if(key){addMessage('user',question);routeConversation(key);return;}contextualBusinessReply(question);};
document.addEventListener('click',e=>{const b=e.target.closest('[data-action="conversation"]');if(!b)return;addMessage('user',b.textContent);routeConversation(b.dataset.key);});
resetChat=function(){focusedPanel=null;$('#contextTitle').textContent='诺德新材料 · 经营对话';$('#chatStream').replaceChildren();addMessage('assistant','<p>我们从你关心的业务开始。</p><p>你可以问我<strong>整体情况、投放效果、内容进展</strong>，也可以直接说要处理什么。讨论到具体问题时，我会把对应数据和记录放在右侧，与你一起核对。</p><p>当前示例里，值得先跟进的是<strong>智能仓储投放的转化质量</strong>和<strong>图片修复的剩余验收</strong>。</p>',[{label:'先看整体情况',action:'conversation',key:'overview'},{label:'跟进上次的行动',action:'conversation',key:'execution'}]);conversationSuggestions();};
/* Keep supporting windows on the data side, unless the user explicitly maximizes. */
const supportingOpenPanel=openPanel;
openPanel=function(key,scope=boardScope){supportingOpenPanel(key,scope);const p=[...panels.values()].find(x=>x.key===key&&x.scope===scope);if(!p)return;if(innerWidth<=620&&state.mode==='chat-focus'){p.el.hidden=true;dock();}if(innerWidth>620&&state.mode!=='fullscreen'&&!p.el.classList.contains('maximized')){const r=$('#main').getBoundingClientRect();p.el.style.left=(r.left+8)+'px';p.el.style.top='152px';p.el.style.width=Math.max(320,r.width-16)+'px';p.el.style.height=Math.max(240,innerHeight-205)+'px';}const footer=p.el.querySelector('[data-win="explain"]');footer.textContent='带入对话继续讨论';};
const conversationSetMode=setMode;
setMode=function(mode){conversationSetMode(mode);if(innerWidth<=620){if(mode==='chat-focus')panels.forEach(p=>p.el.hidden=true);else if(focusedPanel)focusedPanel.el.hidden=false;dock();}$('.assistant-fab').innerHTML=innerWidth<=620&&mode==='chat-focus'?'查看数据 ↗':'返回对话';};
$('.assistant-head b').textContent='获客推广AI智能体';$('.assistant-head small').textContent='与你一起看数据、做决策';$('#assistant').setAttribute('aria-label','获客推广AI智能体对话');$('#chatInput').placeholder='问一个问题，或直接下指令…';$('#chatInput').rows=2;
document.documentElement.style.setProperty('--chat-width','48vw');
$('#resizeHandle').setAttribute('aria-valuemax','720');$('#resizeHandle').setAttribute('aria-valuenow',String(Math.round(innerWidth*.48)));
resizeTo=function(width){const max=Math.min(720,innerWidth-340),v=Math.max(300,Math.min(max,width));document.documentElement.style.setProperty('--chat-width',v+'px');$('#resizeHandle').setAttribute('aria-valuenow',String(Math.round(v)));};
setMode(innerWidth<=620?'chat-focus':'split');resetChat();

const supportingPanelResize=new ResizeObserver(()=>{if(innerWidth<=620||state.mode==='fullscreen')return;const r=$('#main').getBoundingClientRect();panels.forEach(p=>{if(p.el.classList.contains('maximized'))return;p.el.style.left=(r.left+8)+'px';p.el.style.width=Math.max(320,r.width-16)+'px';});});
supportingPanelResize.observe($('#main'));

// Dismiss optional guidance after selection, outside click, or Escape.
document.addEventListener('click',e=>{const more=document.querySelector('.chat-more[open]');if(more&&(!more.contains(e.target)||e.target.closest('[data-question]')))more.open=false;});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const more=document.querySelector('.chat-more[open]');if(more){more.open=false;more.querySelector('summary').focus();}}});
