/* Business exploration layer. Fixtures only; no business API or write operation. */
const capabilities={
sem:['授权与同步','经营指标与趋势','预算管理','计划与地域时段','单元与创意','关键词资产','搜索词与否定词','拓词机会','智能出价','异常与预警','调整与回写验收','线索与成交跟进','洞察与经营报告'],
seo:['站点与品牌','关键词资产','排名追踪','搜索经营概览','网站诊断','图片修复与验收','原创内容','改写与质量检查','内容分发','外链建设','竞争对手','自动任务与预警','统一指标与任务验收'],
geo:['AI 品牌概览','品牌可见度','采集与巡检快照','问题库','竞争对手','引用与信源','文章与编辑','媒体投放','发布渠道','结构诊断与行动','品牌知识与模型','周期与周报','基线、发布与复测验收']};
const guidance={
sem:['检查账户身份、授权状态和最近报表日期，再核对缺报范围。','按日期、设备和计划查看变化，再核对同长度前期。','核对预算消耗和可用上限，再制定范围与停止条件。','先定位计划，再比较地域、时段与设备分布。','从计划下钻到单元和创意，核对承接页面。','查看关键词花费、点击、转化及匹配方式。','先核对原始搜索词相关性，再审阅否定词建议。','审阅拓词来源、相关性与拟投范围。','核对转化回传与出价策略，再讨论调整。','按异常影响定位账户与对象，确认是否仍在发生。','先看审批与回写记录，再核对平台实际状态。','沿来源、计划、关键词追踪意向和成交记录；区分累计与期间。','查看日报、月报及支撑记录，明确统计周期。'],
seo:['确认站点归属、品牌资料与采集范围。','按业务优先级查看关键词与目标页面。','先选搜索引擎、设备与地区，再比较排名。','分别看搜索点击、排名与内容产出，保留各自口径。','按影响和页面范围排查诊断项。','检查审核记录，再以重新抓取结果验收。','从选题、草稿、审核到发布逐步检查。','核对改写内容与质量检查，人工确认关键事实。','确认发布渠道、文章地址及可访问状态。','检查外链目标、落地地址与核验记录。','比较同关键词、同搜索环境下的竞争页面。','核对任务触发、执行进度和阻塞原因。','查看服务端计算的验收结果，区分净增长与单次发布。'],
geo:['分别看提及、引用和竞争表现，先核对样本来源。','检查有效回答、问题与引擎覆盖，再看正式指标。','逐条查看原始回答、巡检来源、模型与判读状态。','选择非点名业务问题，保持前后问题集合可比。','比较相同问题和引擎中的品牌表现。','追踪回答引用的网站及自有域名。','从文章任务进入编辑和事实核对。','核对媒体资源、发布要求与投放记录。','确认渠道授权、发布地址和当前可访问性。','从诊断定位行动票据，再核对执行准备。','核对品牌资料、知识来源与模型配置。','明确完整周期、异步任务进度和周报边界。','按基线准备、发布核实、复测计划、证据验收依次推进。']};
let boardModule='all',boardScope='week',windowZ=100,windowCounter=0,focusedPanel=null;
const panels=new Map();
const scopes={week:'2026.08.31 — 09.06 · 示例周',prior:'2026.08.24 — 08.30 · 前一周'};
const miniLine=(values,color)=>{const lo=Math.min(...values),hi=Math.max(...values);return `<svg viewBox="0 0 400 80" role="img" aria-label="七日趋势，逐日数据可打开详情查看"><path d="M0 70H400 M0 40H400 M0 10H400" stroke="#29374b" fill="none"/><polyline points="${values.map((v,i)=>`${i*400/(values.length-1)},${70-(v-lo)/(hi-lo||1)*58}`).join(' ')}" fill="none" stroke="${color}" stroke-width="2.5"/><text x="0" y="79" fill="#92a3bc" font-size="9">08.31</text><text x="370" y="79" fill="#92a3bc" font-size="9">09.06</text></svg>`;};
const openButton=(key,label)=>`<button data-panel="${key}">${label} ↗</button>`;
function card(key,title,modules,html){return `<article class="dash-card" data-card="${key}" data-modules="${modules}"><header><h2>${title}</h2><div class="card-tools"><button data-size="compact" aria-label="收起${title}">−</button><button data-size="expanded" aria-label="放大${title}">⛶</button><button data-panel="${key}" aria-label="弹出${title}">↗</button></div></header><div class="card-content">${html}</div></article>`;}
function renderDashboard(){const prev=boardScope==='prior',missing=prev?'<p class="narrative">此前一周暂无该区域演示明细。打开详情可查看当前选择的数据覆盖与下一步。</p>':null;
$('#page-dashboard').innerHTML=`<div class="dashboard-header"><div><p class="eyebrow">BUSINESS COMMAND CENTER / 综合经营</p><h1>看清全局，也看透每个细节。</h1><p>投放 · 搜索 · AI 品牌 · 内容 · 执行，一个工作台贯通。</p></div><button class="secondary-button" data-arrange>并排整理详情</button></div><div class="dashboard-scope"><label>时间 <select id="boardScope"><option value="week" ${!prev?'selected':''}>本周 · 08.31 — 09.06</option><option value="prior" ${prev?'selected':''}>前一周 · 08.24 — 08.30</option></select></label><label>业务 <select id="boardModule">${[['all','所有模块'],['sem','SEM · 投放'],['seo','SEO · 搜索'],['geo','GEO · AI 品牌']].map(([v,n])=>`<option value="${v}" ${boardModule===v?'selected':''}>${n}</option>`).join('')}</select></label><small>示例数据 · 卡片可收起、放大、弹出 · 详情固定打开时的时间</small></div><div class="dash-grid">
${card('results','01 / 经营结果','sem seo geo',`<small>${scopes[boardScope]} · 渠道指标分别统计</small><div class="dash-values"><button data-panel="spend"><strong>${prev?'¥39,040':'¥42,110'}</strong><span>SEM 账户花费 ${prev?'':'↑ 7.9%'}</span></button><button data-panel="organic"><strong>${prev?'304':'380'}</strong><span>相关内容 GSC 点击 ${prev?'':'↑ 25%'}</span></button><button data-panel="leads"><strong class="empty-number">待接入</strong><span>有效商机 / 成交</span></button></div><p class="narrative">流量、线索与成交逐层核对。连接有效线索后，才能进一步判断投入带来的业务结果。</p><div class="dash-links">${openButton('leads','线索与成交链路')}${openButton('results','经营口径')}</div>`)}
${card('spend','02 / 投放结构','sem',missing||`<small>百度账户 · 本周报表演示</small><div class="dash-values"><button data-panel="spend"><strong>34%</strong><span>智能仓储花费占比</span></button><button data-panel="spend"><strong>837</strong><span>词组点击</span></button><button data-panel="spend"><strong>2</strong><span>报表记录转化</span></button></div>${miniLine(weekly.spend,colors.sem)}<div class="dash-links">${openButton('sem:3','计划 / 地域 / 时段')}${openButton('sem:6','搜索词 / 否定词')}${openButton('sem:8','出价策略')}</div>`)}
${card('organic','03 / 搜索与内容','seo',missing||`<small>GSC 点击与百度 PC 排名 · 独立来源</small><div class="dash-values"><button data-panel="organic"><strong>380</strong><span>本周相关内容点击</span></button><button data-panel="organic"><strong>4</strong><span>百度 PC 期末排名</span></button><button data-panel="seo:6"><strong class="empty-number">待接入</strong><span>内容生产与发布量</span></button></div>${miniLine(weekly.organic,colors.seo)}<div class="dash-links">${openButton('seo:1','关键词资产')}${openButton('seo:6','内容生产')}${openButton('seo:9','外链建设')}</div>`)}
${card('visibility','04 / AI 可见度与竞争','geo',`<small>正式指标使用完整自然周：08.24 — 08.30</small><div class="dash-values"><button data-panel="visibility"><strong class="empty-number">待接入</strong><span>正式品牌可见度</span></button><button data-panel="geo:4"><strong class="empty-number">待接入</strong><span>同口径竞品表现</span></button><button data-panel="visibility"><strong>${prev?'—':'12'}</strong><span>${prev?'该周无样本演示':'本周原始样本'}</span></button></div>${prev?'':`<div class="dash-meter"><i style="width:25%;background:${colors.geo}"></i><i style="width:16.67%;background:${colors.seo}"></i><i style="width:58.33%;background:#526079"></i></div><small>3 真实引擎 / 2 人工 / 7 模拟 · 不代表正式有效样本</small>`}<div class="dash-links">${openButton('visibility','来源与统计资格')}${openButton('geo:3','问题覆盖')}${openButton('geo:5','引用信源')}</div>`)}
${card('health','05 / 网站与内容健康','seo geo',missing||`<small>这批图片示例 · 按重新抓取结果验收</small><div class="dash-values"><button data-panel="health"><strong>12 / 20</strong><span>图片已确认修复</span></button><button data-panel="health"><strong>5</strong><span>等待复查</span></button><button data-panel="health"><strong>3</strong><span>复查未通过</span></button></div><div class="dash-meter"><i style="width:60%;background:${colors.seo}"></i><i style="width:25%;background:${colors.sem}"></i><i style="width:15%;background:#c67c94"></i></div><div class="dash-links">${openButton('health','图片检查详情')}${openButton('seo:4','网站诊断')}${openButton('geo:9','结构诊断')}</div>`)}
${card('execution','06 / 执行与阻塞','sem seo geo',`<small>当前状态 · 不随经营日期切换</small>${seedTasks.map(t=>`<div class="health-row"><button data-task="${t.id}">${esc(t.title)} ↗</button>${badge(t.status)}</div>`).join('')}<p class="narrative">进度与结果分开记录。点击行动检查证据、负责人和复核日期。</p><div class="dash-links"><button data-page="tasks">进入待办与进度 ↗</button>${openButton('geo:12','基线 → 发布 → 复测')}</div>`)}
${card('relations','07 / 跨模块关系','sem seo geo',`<small>主题：智能仓储 · 关联线索，不代表因果归因</small><div class="health-row"><span>SEM 付费关键词</span><span>→ 智能仓储主题 ←</span><span>SEO 内容页面</span></div><p class="narrative">${prev?'前一周缺少主题级花费与排名明细。':'词组花费 ¥14,320；相关内容 GSC 点击 380。'} 下一步核对用户意图、承接页面与有效转化，再判断是否适合联合试验。</p><div class="dash-links">${openButton('relations','打开关系与核验路径')}<button data-issue="allocation">进入经营研判 ↗</button></div>`)}
${card('connections','08 / 数据与接入健康','sem seo geo',`<small>当前原型：三个模块都未连接真实数据</small><div class="health-row"><span>SEM · 指标契约已有</span><span>任务契约待实现</span></div><div class="health-row"><span>SEO · 指标 / 任务代码已有</span><span>环境与权限待验收</span></div><div class="health-row"><span>GEO · 严格周指标 / 验收代码已有</span><span>来源与基线待验收</span></div><div class="dash-links">${openButton('connections','查看接入与时间口径')}<button data-page="quality">原始示例数据健康 ↗</button></div>`)}
</div><section class="cap-explorer"><header><div><h2>业务全景 · 39 个能力入口</h2><p class="scope-label">模块源码能力索引。入口提供查看路径与操作指导，业务明细尚未接入。</p></div><input class="cap-search" id="capSearch" type="search" placeholder="查找预算、发布、复测…" aria-label="搜索模块能力"></header><div class="cap-grid" id="capGrid"></div></section>`;
$$('.dash-card').forEach(c=>c.hidden=boardModule!=='all'&&!c.dataset.modules.split(' ').includes(boardModule));renderCapabilities();}
function renderCapabilities(){const q=($('#capSearch')?.value||'').trim();let count=0;$('#capGrid').innerHTML=Object.entries(capabilities).filter(([m])=>boardModule==='all'||boardModule===m).map(([m,items])=>{const buttons=items.map((n,i)=>({n,i})).filter(({n})=>!q||n.includes(q)||m.includes(q.toLowerCase())).map(({n,i})=>{count++;return openButton(m+':'+i,`${String(i+1).padStart(2,'0')} · ${n}`);}).join('');return buttons?`<div class="cap-column"><h3 style="color:${colors[m]}">${m.toUpperCase()}</h3>${buttons}</div>`:'';}).join('');if(!count)$('#capGrid').innerHTML='<p class="muted">没有匹配的能力，请尝试“内容”“预算”或清空搜索。</p>';}
const titles={results:'经营结果与统计口径',spend:'SEM · 花费与转化',organic:'SEO · 点击与排名',visibility:'GEO · 样本与正式指标',health:'图片修复与验收',execution:'执行与阻塞',relations:'智能仓储 · 跨模块关系',connections:'数据接入与统计周期',leads:'线索与成交链路'};
function panelTitle(key){if(key.includes(':')){const [m,i]=key.split(':');return `${m.toUpperCase()} · ${capabilities[m][i]}`;}return titles[key];}
function panelContent(key,scope){const prev=scope==='prior';if(key.includes(':')){const [m,i]=key.split(':');return `<h2>${esc(capabilities[m][i])}</h2><p>${esc(guidance[m][i])}</p><h3>按这条路径查看</h3><ol class="steps"><li>选择客户及${m==='sem'?'账户与计划':m==='seo'?'站点与页面':'品牌、问题与引擎'}，确认数据范围。</li><li>查看对象明细、时间和来源，定位影响业务的具体问题。</li><li>核对${m==='geo'?'基线、发布核实与复测证据':m==='seo'?'发布、重新抓取或排名观测记录':'平台审批、回写和有效转化记录'}。</li><li>确认负责人、验收条件和复核时间，再制定行动。</li></ol><h3>当前接入状态</h3><p>源码已发现对应模块能力，原型尚未连接对象数据。此处不显示虚构的任务、账号或业务结果。</p><div class="dash-links">${openButton(m==='sem'?'spend':m==='seo'?'organic':'visibility','查看该模块示例数据')}${openButton('connections','查看接入条件')}</div>`;}
if(key==='spend'||key==='organic'){const isSem=key==='spend';return `<h2>${panelTitle(key)}</h2>${prev?`<p>前一周${isSem?'账户花费 ¥39,040':'相关内容 GSC 点击 304'}。此前一周仅有汇总示例，没有逐日原始明细。</p>`:table(isSem?['日期','账户花费','词组花费','词组点击','记录转化']:['日期','GSC 点击','百度 PC 排名'],dates.map((d,i)=>isSem?[d,money(weekly.spend[i]),money(weekly.topic[i]),weekly.clicks[i],weekly.conversions[i]]:[d,weekly.organic[i],weekly.rank[i]]))}<p>${isSem?'记录转化不等于有效商机；需核对线索质量。词组和账户范围不同，不混用转化成本。':'点击与排名来自不同搜索引擎。排名数字越小越靠前，不能与点击相加。'}</p><div class="dash-links">${openButton('relations','查看关联主题')}${openButton(isSem?'sem:11':'seo:6',isSem?'线索跟进':'内容生产路径')}</div>`;}
if(key==='visibility')return `<h2>先看样本，再判断指标能否成立。</h2><p>正式周指标窗口固定为 08.24 — 08.30。${prev?'该周没有演示回答记录。':'当前选择周的 12 条记录只是原始来源构成，不属于该正式指标窗口。'}</p>${prev?'':table(['编号','日期','来源','问题','提及'],samples.map(s=>s.map((v,i)=>i===4?(v?'是':'否'):esc(String(v)))))}<p>正式指标还要求真实 v2 API、原始巡检可追溯、非点名题、判读与引用有效，并满足至少 8 条回答、3 个问题、2 个引擎。当前不能给出正式可见度或增长结论。</p><div class="dash-links">${openButton('geo:12','查看基线与复测路径')}</div>`;
if(key==='health')return `<h2>审核完成之后，继续核对实际页面。</h2>${prev?'<p>前一周没有这批图片演示记录。</p>':`<p>本周 20 张：12 张确认修复，5 张待复查，3 张未通过。整体确认修复率 60%。</p><button class="secondary-button" data-action="evidence" data-key="images">逐张查看 20 条验收记录</button>`}<ol class="steps"><li>核对已审核图片与目标页面。</li><li>重新抓取，匹配图片和批准的替代文本。</li><li>处理失败项并再次复查。</li></ol>`;
if(key==='relations')return `<h2>同一个业务主题，三条独立证据链。</h2><p>付费关键词 → 智能仓储 ← 自然搜索内容。AI 问题与该主题的稳定映射尚未接入。</p><ol class="steps"><li>核对关键词与页面是否解决同一种需求。</li><li>区分百度投放与 GSC 点击的来源和人群。</li><li>补齐有效转化、承接页面和前后可比基线。</li><li>再规划小范围试验，定义停止阈值及回滚条件。</li></ol><div class="dash-links">${openButton('spend','并排看投放')}${openButton('organic','并排看搜索')}<button data-issue="allocation">研判与行动草稿 ↗</button></div>`;
if(key==='execution')return `<h2>执行完成与效果验收分开。</h2>${seedTasks.map(t=>`<div class="health-row"><button data-task="${t.id}">${esc(t.title)} ↗</button>${badge(t.status)}</div>`).join('')}<p>任务采用当前状态快照，不按经营窗口推算历史状态。</p>`;
if(key==='connections')return `<h2>每张数据卡，都应说明从哪里来。</h2>${table(['模块','已有源码','接入前需核对'],[['SEM','5 项指标快照；通用任务待实现','授权身份、月份累计与所选周期'],['SEO','6 项指标；4 类统一任务','站点权限、Schema、服务器验收'],['GEO','严格周指标与任务验收','完整自然周、有效来源、可比基线']])}<p>本原型没有连接业务 API。普通 GEO 默认 14 天与驾驶舱完整周指标是不同口径。缺数据保持未知，不能记为零。</p>`;
return `<h2>${panelTitle(key)}</h2><p>${key==='leads'?'沿来源 → 计划 → 关键词 → 线索意向 → 成交记录逐层核对。目前未接入线索与成交数据。':'SEM 账户花费与 SEO 相关内容点击可各自观察；跨渠道去重、有效商机与成交尚未接入。'}</p><p>累计成交金额不能除以本周花费来计算回报。需要匹配时间、范围、归因规则和有效性后再计算。</p><div class="dash-links">${openButton('sem:11','线索模块查看路径')}${openButton('spend','花费明细')}${openButton('organic','搜索明细')}</div>`;
}
function dock(){ $('#panelDock').innerHTML=[...panels.values()].map(p=>`<button data-restore="${p.id}" aria-label="恢复${esc(panelTitle(p.key))}">${p.el.hidden?'▣':'▤'} ${esc(panelTitle(p.key))}</button>`).join('');}
function focusPanel(p){focusedPanel=p;p.el.style.zIndex=++windowZ;$('#contextTitle').textContent=panelTitle(p.key)+' · '+scopes[p.scope];}
function openPanel(key,scope=boardScope){if(!panelTitle(key))return;const existing=[...panels.values()].find(p=>p.key===key&&p.scope===scope);if(existing){existing.el.hidden=false;focusPanel(existing);dock();return;}const id='window-'+(++windowCounter),el=document.createElement('section');el.className='detail-window';el.id=id;el.setAttribute('role','region');el.setAttribute('aria-label',panelTitle(key));el.style.left=Math.min(360+(panels.size%3)*36,Math.max(8,innerWidth-550))+'px';el.style.top=100+(panels.size%3)*28+'px';el.innerHTML=`<header class="window-head" tabindex="0" aria-label="移动${esc(panelTitle(key))}，方向键调整位置"><b>${esc(panelTitle(key))}</b><button data-win="min" aria-label="最小化详情">−</button><button data-win="max" aria-label="最大化或还原详情">⛶</button><button data-win="close" aria-label="关闭此详情">×</button></header><div class="window-body"><span class="scope-chip">${key.includes(':')?'演示配置与流程 · 当前状态':'固定范围：'+scopes[scope]}${key==='execution'?' · 任务为当前状态':''}</span>${panelContent(key,scope)}</div><footer class="window-footer"><span>独立详情 · 可拖动 / 右下角缩放</span><button class="text-button" data-win="explain">解读这个对象</button></footer>`;$('#panelLayer').append(el);const p={id,key,scope,el};panels.set(id,p);el.addEventListener('pointerdown',()=>focusPanel(p));const head=el.querySelector('.window-head');let drag=null;head.addEventListener('pointerdown',e=>{if(e.target.closest('button')||el.classList.contains('maximized'))return;const r=el.getBoundingClientRect();drag={x:e.clientX-r.x,y:e.clientY-r.y};head.setPointerCapture(e.pointerId);});head.addEventListener('pointermove',e=>{if(drag){el.style.left=Math.max(0,Math.min(innerWidth-100,e.clientX-drag.x))+'px';el.style.top=Math.max(65,Math.min(innerHeight-90,e.clientY-drag.y))+'px';}});['pointerup','pointercancel'].forEach(n=>head.addEventListener(n,()=>drag=null));head.addEventListener('keydown',e=>{if(e.target!==head||!e.key.startsWith('Arrow'))return;e.preventDefault();const r=el.getBoundingClientRect();el.style.left=Math.max(0,Math.min(innerWidth-100,r.x+(e.key==='ArrowLeft'?-20:e.key==='ArrowRight'?20:0)))+'px';el.style.top=Math.max(65,Math.min(innerHeight-90,r.y+(e.key==='ArrowUp'?-20:e.key==='ArrowDown'?20:0)))+'px';});focusPanel(p);dock();head.focus();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.panel){const parent=panels.get(b.closest('.detail-window')?.id);openPanel(b.dataset.panel,parent?.scope||boardScope);}if(b.dataset.size){const c=b.closest('.dash-card');c.classList.toggle(b.dataset.size);if(b.dataset.size==='expanded')c.classList.remove('compact');}if(b.dataset.restore){const p=panels.get(b.dataset.restore);p.el.hidden=false;focusPanel(p);dock();}if(b.dataset.win){const p=panels.get(b.closest('.detail-window').id);if(b.dataset.win==='close'){p.el.remove();panels.delete(p.id);if(focusedPanel===p)focusedPanel=null;}if(b.dataset.win==='min')p.el.hidden=true;if(b.dataset.win==='max')p.el.classList.toggle('maximized');if(b.dataset.win==='explain'){p.el.hidden=innerWidth<=620;showChat();addMessage('user',`请解读 ${panelTitle(p.key)}，范围 ${scopes[p.scope]}`);addMessage('assistant',`<p>当前对象：<strong>${esc(panelTitle(p.key))}</strong>。固定范围：${scopes[p.scope]}。</p><p>${p.key.includes(':')?esc(guidance[p.key.split(':')[0]][p.key.split(':')[1]]):'详情列出了当前示例证据与缺失信息。先核对对象和统计窗口，再决定补数据、观察或拟定行动。'}</p><p>这是固定规则演示解读，尚未连接智能模型。可从下方恢复该对象继续核对。</p>`);}dock();}if(b.hasAttribute('data-arrange')){const visible=[...panels.values()].filter(p=>!p.el.hidden);visible.forEach((p,i)=>{p.el.classList.remove('maximized');const cols=innerWidth>=900?2:1,w=Math.floor((innerWidth-24)/cols);p.el.style.cssText=`left:${8+(i%cols)*(w+8)}px;top:${80+Math.floor(i/cols)*35}px;width:${w}px;height:${Math.max(260,innerHeight-160)}px;z-index:${++windowZ}`;});if(!visible.length)toast('先弹出两个详情，即可并排比较。');}});
document.addEventListener('change',e=>{if(e.target.id==='boardScope'){boardScope=e.target.value;renderDashboard();}if(e.target.id==='boardModule'){boardModule=e.target.value;renderDashboard();}});
document.addEventListener('input',e=>{if(e.target.id==='capSearch')renderCapabilities();});
const briefReply=reply;
reply=function(question){if(state.page!=='dashboard'||!focusedPanel){briefReply(question);return;}const p=focusedPanel;addMessage('user',question);addMessage('assistant',`<p>当前查看的是 <strong>${esc(panelTitle(p.key))}</strong>，范围 ${scopes[p.scope]}。</p><p>${p.key.includes(':')?esc(guidance[p.key.split(':')[0]][p.key.split(':')[1]]):p.key==='visibility'?'先核对完整周及有效样本条件；原始来源构成不能替代正式可见度。':p.key==='spend'?'先逐日核对账户与词组花费，再核对记录转化是否为有效商机。':p.key==='organic'?'先分别核对 GSC 点击和百度 PC 排名，再检查相关内容的发布与承接情况。':'先核对详情中的对象、来源和时间，再明确缺失证据、负责人及复核日期。'}</p><p>当前仅提供固定规则引导，无法对自由问题作模型分析。详情可从底部恢复查看。</p>`);};
document.addEventListener('click',e=>{if(e.target.closest('#contextTitle')&&focusedPanel){e.stopImmediatePropagation();navigate('dashboard');focusedPanel.el.hidden=false;focusPanel(focusedPanel);dock();}},true);
renderDashboard();navigate('dashboard');
