/* Unified local search and explicit demo reset. No remote writes. */
let unifiedQuery='';
function unifiedRows(){const scope={topic:'all',start:0,end:6};return [...panoramaData.all.map(r=>({id:r.id,label:r.title||r.question||r.plan||r.topic,group:r.id.startsWith('CT-')?'文章':r.id.startsWith('KW-')?'搜索关键词':'其他数据',kind:'record',meta:[r.topic,r.engine,r.status,r.owner,r.date].filter(Boolean).join(' · ')})),...semDepthKeywords(scope).map(r=>({id:r.id,label:r.title,group:'广告关键词',kind:'sem',meta:r.topic})),...allTasks().map(r=>({id:r.id,label:r.title,group:'待办',kind:'task',meta:[r.owner,r.due,r.status==='draft'?'待确认':r.status==='cancelled'?'已撤回':'跟进记录'].join(' · ')}))];}
pSearch=function(query=unifiedQuery){unifiedQuery=query;showDialog('搜索 / 全部内容',`<h2>找关键词、文章或待办</h2><input id="unifiedSearch" type="search" aria-label="搜索关键词、文章或待办" placeholder="输入名称、负责人或编号" value="${esc(query)}"><p>搜索全部演示日期与业务，不受当前看板筛选影响。</p><div id="unifiedResults"></div>`);unifiedResults();$('#unifiedSearch').focus();};
function unifiedResults(){const q=unifiedQuery.trim().toLowerCase(),rows=unifiedRows().filter(r=>(r.id+' '+r.label+' '+r.meta+' '+r.group).toLowerCase().includes(q));$('#unifiedResults').innerHTML=`<p>${rows.length} 条匹配结果</p>`+['广告关键词','文章','待办','搜索关键词','其他数据'].map(group=>{const list=rows.filter(r=>r.group===group);return list.length?`<section><h3>${group} · ${list.length}</h3>${list.slice(0,8).map(r=>`<button class="p-result-row" data-unified-open="${esc(r.id)}" data-unified-kind="${r.kind}">${esc(r.label)}<small>${esc(r.id)} · ${esc(r.meta)}</small></button>`).join('')}${list.length>8?'<p>本类先展示 8 条，请输入更具体的名称。</p>':''}</section>`:'';}).join('')+(!rows.length?'<p>没有找到。试试业务名称、文章标题或负责人。</p>':'');}
function demoResetDialog(){showDialog('重置演示',`<h2>重新开始这次演示？</h2><p>将清除当前标签页的 <strong>${localDrafts.length} 份方案</strong>、<strong>${rehearsals.length} 项手动演练</strong>及本次对话，关闭详情窗口并恢复默认筛选。</p><p>原有示例数据与示例待办会保留。不会影响真实业务或其他标签页。清除后无法从本页面恢复。</p><form id="demoResetForm"><label><input type="checkbox" name="confirmed" required> 我确认清除上述演示记录</label><div class="seo-actions"><button type="button" data-action="closeDialog">保留记录，返回</button><button type="submit">清除并重新开始</button></div></form>`);}
const demoRender=renderPanorama;renderPanorama=function(){demoRender();const controls=panoPage.querySelector('.p-controls');controls?.insertAdjacentHTML('beforeend','<button data-demo-reset>重置演示</button>');panoPage.querySelectorAll('[data-precision-plan]').forEach(b=>{const k=b.dataset.precisionPlan;b.textContent=['trend','mix','device','funnel','semkeywords'].includes(k)?'安排核实转化':['content','organic','ranking'].includes(k)?'安排内容检查':['heatmap','citations','competition'].includes(k)?'安排检查 AI 回答':'安排下一步';});};
document.addEventListener('input',e=>{if(e.target.id==='unifiedSearch'){unifiedQuery=e.target.value;unifiedResults();}});
window.addEventListener('click',e=>{const b=e.target.closest('[data-unified-open],[data-unified-return],[data-demo-reset]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(b.hasAttribute('data-demo-reset'))return demoResetDialog();if(b.hasAttribute('data-unified-return'))return pSearch();const id=b.dataset.unifiedOpen;if(b.dataset.unifiedKind==='task')showTask(id);else if(b.dataset.unifiedKind==='sem')semDepthOpen(id,{topic:'all',start:0,end:6});else{const r=panoramaData.all.find(x=>x.id===id);if(id.startsWith('CT-'))seoOpen(id,{topic:r.topic,start:0,end:6});else pObject(id);}$('#dialogBody').insertAdjacentHTML('beforeend','<button class="seo-entry" data-unified-return>返回搜索结果</button>');},true);
document.addEventListener('submit',e=>{if(e.target.id!=='demoResetForm')return;e.preventDefault();if(!e.target.reportValidity()||!e.target.elements.confirmed.checked)return;const keys=[storageKey,'cockpit-rehearsals-v1'];let saved;try{saved=keys.map(k=>sessionStorage.getItem(k));keys.forEach(k=>sessionStorage.removeItem(k));}catch{if(saved)keys.forEach((k,i)=>{try{if(saved[i]!==null)sessionStorage.setItem(k,saved[i]);}catch{}});toast('未能清除浏览器记录，请稍后重试。');return;}location.reload();});
renderPanorama();
