/* Navigation history stores view context only; it does not assert business causality. */
const exploration={items:[],index:-1,replaying:false};
function explorationRemember(item){if(exploration.replaying)return;const entry={...item,scope:item.scope||pSnapshot(),scroll:$('#pageScroll').scrollTop};const last=exploration.items[exploration.index];if(last&&last.kind===entry.kind&&last.key===entry.key&&pScope(last.scope)===pScope(entry.scope)&&last.subset===entry.subset)return;exploration.items.splice(exploration.index+1);exploration.items.push(entry);if(exploration.items.length>8)exploration.items.shift();exploration.index=exploration.items.length-1;explorationRender();}
function explorationRender(){let strip=$('#explorationPath');if(!strip){strip=document.createElement('nav');strip.id='explorationPath';strip.className='exploration-path';strip.setAttribute('aria-label','查看路径');const bar=panoPage.querySelector('.command-strip');if(bar)bar.after(strip);else return;}strip.innerHTML=`<button data-exploration="back" ${exploration.index<=0?'disabled':''} aria-label="返回上一个查看位置">←</button><button data-exploration="forward" ${exploration.index>=exploration.items.length-1?'disabled':''} aria-label="前进到下一个查看位置">→</button><span>查看路径</span><div>${exploration.items.slice(Math.max(0,exploration.index-2),exploration.index+1).map((x,i)=>{const index=Math.max(0,exploration.index-2)+i;return `<button data-exploration="go" data-index="${index}" ${index===exploration.index?'aria-current="location"':''} title="${esc(x.label)} · ${pScope(x.scope)}">${esc(x.label)}</button>`;}).join('<i>›</i>')}</div>`;}
function explorationGo(index){const item=exploration.items[index];if(!item)return;exploration.index=index;exploration.replaying=true;try{closeDialog();if(fluidOpen)fluidCollapse(false);panels.forEach(p=>p.el.hidden=true);dock();Object.assign(pano,item.scope);navigate('panorama');$('#pageScroll').scrollTop=item.scroll;if(item.kind==='panel')pOpen(item.key,item.subset,item.scope);if(item.kind==='object')pObject(item.key);if(item.kind==='task')showTask(item.key);if(item.kind==='evidence')showEvidence(item.key);}finally{exploration.replaying=false;explorationRender();}}
function explorationBackButton(){const body=$('#dialogBody');if(exploration.index>0&&!body.querySelector('.exploration-return'))body.insertAdjacentHTML('beforeend',`<div class="exploration-return"><button data-exploration="back">← 返回上一步：${esc(exploration.items[exploration.index-1].label)}</button><small>恢复当时的主题和日期</small></div>`);}
const explorationPanel=pOpen;pOpen=function(key,subset='',scope=pSnapshot()){explorationRemember({kind:'panel',key,subset,scope,label:panoCards[key]?.[1]||key});explorationPanel(key,subset,scope);};
let explorationObjectScope=null;
window.addEventListener('click',e=>{if(!e.target.closest('[data-pano="object"]'))return;const windowEl=e.target.closest('.detail-window');const panel=windowEl&&[...panels.values()].find(p=>p.el===windowEl);explorationObjectScope=panel&&panoSnapshots.has(panel.key)?{...panoSnapshots.get(panel.key)}:null;},true);
const explorationObject=pObject;pObject=function(id){const r=panoramaData.all.find(x=>x.id===id);const scope=explorationObjectScope;explorationObjectScope=null;explorationRemember({kind:'object',key:id,scope,label:r?.title||r?.question||id});explorationObject(id);explorationBackButton();};
const explorationTask=showTask;showTask=function(id){const task=allTasks().find(t=>t.id===id);explorationRemember({kind:'task',key:id,label:task?.title||id});explorationTask(id);if(id==='EX-104'){$('#dialogBody').insertAdjacentHTML('afterbegin',`<section class="deadline-context"><header><span>需要跟进 · 示例批次</span><strong>距复核 2 天</strong></header><div class="deadline-numbers"><div><b>12<small>/20</small></b><span>已确认修复</span></div><div><b>5</b><span>待重新抓取</span></div><div><b>3</b><span>复查未通过</span></div></div><div class="deadline-track" aria-label="12 张通过，5 张待复查，3 张未通过"><i style="width:60%"></i><i style="width:25%"></i><i style="width:15%"></i></div><p><b>负责人：</b>SEO 内容运营　<b>复核：</b>09.08<br><b>下一步：</b>先补齐 5 张复查，再按失败原因处理 3 张未通过项。</p><button data-action="evidence" data-key="images">查看 20 张图片的验收依据 ↗</button><small>全局行动 · 到期天数以演示日期 09.06 计算；不推测业务损失。</small></section>`);}explorationBackButton();};
const explorationBaseRender=renderPanorama;renderPanorama=function(){explorationBaseRender();explorationRender();};
const explorationChange=pChange;pChange=function(update){explorationChange(update);const current=exploration.items[exploration.index];if(current?.kind==='home'){current.scope=pSnapshot();current.scroll=$('#pageScroll').scrollTop;explorationRender();}};
window.addEventListener('click',e=>{const b=e.target.closest('[data-exploration]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();const action=b.dataset.exploration;explorationGo(action==='back'?exploration.index-1:action==='forward'?exploration.index+1:Number(b.dataset.index));},true);
explorationRemember({kind:'home',key:'home',label:'经营全景'});

const explorationEvidence=showEvidence;showEvidence=function(key){explorationRemember({kind:'evidence',key,label:({images:'图片逐张验收依据',titles:'标题修复依据',sem:'投放依据',seo:'搜索依据',geo:'回答样本依据'})[key]||'核验依据'});explorationEvidence(key);explorationBackButton();};
