/* Question / engine exploration. Simulated observations never become formal scores. */
const geoQuestions=[...new Set(panoramaData.answers.map(r=>r.question))];
const geoEngines=['DeepSeek','豆包','通义千问'];
function geoStatus(r){return !r?'暂无回答':r.cited?'引用官网':r.mentioned?'仅提及':r.competitor?'仅竞品标记':'未提及';}
function geoCell(q,engine,scope){return pRows('answers',scope).find(r=>r.question===q&&r.engine===engine);}
function geoAttrs(q,engine,scope){return `data-geo-question="${geoQuestions.indexOf(q)}" data-geo-engine="${engine}" data-geo-scope="${esc(JSON.stringify(scope))}"`;}
function geoMatrix(scope){const rows=pRows('answers',scope),qs=geoQuestions.filter(q=>scope.topic==='all'||q.startsWith(scope.topic+'：'));
 return `<div class="geo-workbench"><div class="seo-stages">${[[rows.length,'模拟回答'],[rows.filter(r=>r.cited).length,'官网引用'],[qs.length*3-rows.length,'缺少样本的格子']].map(([n,l])=>`<div><b>${n}</b><span>${l}</span></div>`).join('')}</div><p>${pScope(scope)} · ${qs.length} 个问题 / 3 个引擎。按回答获取日期筛选；没有获取到回答，不代表 AI 没有提到品牌。</p><div class="geo-grid"><span>问题 / 引擎</span>${geoEngines.map(e=>`<b>${e}</b>`).join('')}${qs.map(q=>`<span>${esc(q)}</span>${geoEngines.map(engine=>{const r=geoCell(q,engine,scope);return `<button ${geoAttrs(q,engine,scope)} class="${r?.cited?'cited':r?.mentioned?'mentioned':!r?'missing':''}" aria-label="${esc(q)} ${engine} ${geoStatus(r)}">${geoStatus(r)}<small>${r?r.date:'待获取回答'}</small></button>`;}).join('')}`).join('')}</div><p>全部为模拟样本，正式有效样本为 0；不计算正式得分。竞品状态来自演示结构字段，需与原文另行核实。</p></div>`;
}
const geoDetails=pDetails;pDetails=function(key,scope,subset=''){return key==='heatmap'?`<h2>品牌回答与再次检查工作台</h2>${geoMatrix(scope)}`:geoDetails(key,scope,subset);};
let geoView=null;
function geoOpen(q,engine,scope=pSnapshot()){
 if(!geoQuestions.includes(q)||!geoEngines.includes(engine))return;geoView={q,engine,scope:{topic:scope.topic,start:scope.start,end:scope.end}};const r=geoCell(q,engine,scope),status=geoStatus(r);
 showDialog('AI 品牌表现 / 回答与依据',`<div class="geo-depth"><small>示例回答 · ${r?r.id:'当前范围无记录'}</small><h2>${esc(q)}</h2><p>${pScope(scope)} · 保留打开时的日期范围</p><div class="geo-engine-switch" aria-label="切换回答引擎">${geoEngines.map(en=>`<button ${geoAttrs(q,en,scope)} aria-pressed="${en===engine}">${en}</button>`).join('')}</div><div class="seo-stages"><div><b>${r?(r.mentioned?'是':'否'):'—'}</b><span>品牌提及</span></div><div><b>${r?(r.cited?'是':'否'):'—'}</b><span>官网引用</span></div><div><b>—</b><span>正式品牌表现评分</span></div></div><h3>${engine} · ${status}</h3>${r?`<blockquote>${esc(r.answer)}</blockquote><dl class="seo-facts"><dt>回答获取日期</dt><dd>${r.date} · 时刻未记录</dd><dt>引用来源</dt><dd>${esc(r.citation)}${r.cited?' · 占位示例，未核实真实页面':''}</dd><dt>竞争品牌记录</dt><dd>${r.competitor?'存在竞品标记':'无竞品标记'} · 这段回答不足以确认具体的竞争品牌</dd><dt>数据类型</dt><dd>模拟 · 不进入正式指标</dd></dl>`:'<div class="geo-empty">这个问题在所选日期内没有该引擎回答。先获取回答，再判断品牌是否出现。</div>'}<div class="geo-next"><h3>下一步核实什么</h3><p>${!r?'固定问题与引擎，采集真实回答并保留时间、模型与来源。':!r.mentioned?'先检查真实回答是否遗漏品牌，再核对官网是否有可引用的相关内容；本例不能证明内容不足。':!r.cited?'已提及品牌，但没有官网引用。核对回答是否存在其他来源，以及官网页面能否访问、内容是否支持回答。':'核实引用页面是否属于品牌、能否访问、是否真正支持回答，再安排同条件再次检查。'}</p></div><details><summary>再次检查与完成标准</summary><p>保留原问题、引擎、AI 模型版本、回答获取时间、回答原文与引用。前后使用的条件不同，要说明不能直接比较；操作完成与提及/引用变化分别验收。再次检查时，应与首次获取的真实回答比较，不能与模拟回答比较。</p></details><div class="seo-actions"><button data-geo-discuss>带着问题继续讨论</button><button data-geo-plan>安排获取真实回答</button><button data-geo-back>返回问题总览</button></div></div>`);
}
const geoObject=pObject;pObject=function(id){const r=panoramaData.answers.find(x=>x.id===id);if(r){const s=pSnapshot();if(r.day<s.start||r.day>s.end||(s.topic!=='all'&&s.topic!==r.topic)){s.topic=r.topic;s.start=r.day;s.end=r.day;}return geoOpen(r.question,r.engine,s);}return geoObject(id);};
window.addEventListener('click',e=>{const b=e.target.closest('[data-geo-question],[data-geo-discuss],[data-geo-plan],[data-geo-back]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();
 if(b.hasAttribute('data-geo-question')){geoOpen(geoQuestions[Number(b.dataset.geoQuestion)],b.dataset.geoEngine,JSON.parse(b.dataset.geoScope));return;}
 const {q,engine,scope}=geoView,r=geoCell(q,engine,scope);if(b.hasAttribute('data-geo-back')){showDialog('GEO / 问题矩阵',geoMatrix(scope));return;}closeDialog();
 if(b.hasAttribute('data-geo-discuss')){showChat();addMessage('user',`分析这个问题：${q} / ${engine}`);addMessage('assistant',`<p><strong>${esc(q)}</strong> · ${engine}</p><p>${pScope(scope)}：${geoStatus(r)}。${r?'该回答是模拟样本，不能作为正式品牌表现结论。':'当前没有回答，不能据此认定品牌未被提及。'}</p><p>先固定这个问题与引擎，收集真实回答、引用与模型信息，再比较后续变化。内容不足或页面不可访问目前只是待验证方向。</p><button class="seo-entry" ${geoAttrs(q,engine,scope)}>返回问题并安排再次检查 ↗</button>`);return;}
 pChange(scope);pPlan('geo',`GQ-${geoQuestions.indexOf(q)+1}-${geoEngines.indexOf(engine)+1}`);const f=$('#pPlanForm');f.elements.title.value=`收集回答并再次检查：${q} / ${engine}`;f.elements.owner.value='品牌运营负责人';f.elements.note.value=`${pScope(scope)}。问题：${q}；引擎：${engine}。当前：${geoStatus(r)}。先采集首次真实记录，再按同一问题和可比条件再次检查；记录模型、时间、回答、引用和任务结果记录。当前模拟样本不充当首次真实记录。`;f.elements.criterion.value='收集真实回答来源可追查；前后问题、引擎及模型条件可比，差异单独注明。回答收集完成与品牌提及/引用变化分别验收，不承诺排名、线索或成交增长。';
},true);
renderPanorama();
