/* Complete client-facing interaction scenario; no network/model side effects. */
const pano = {topic:'all',start:0,end:6,focus:'trend',history:[],compact:false,expanded:new Set(),tour:0,compare:null};
const panoSnapshots = new Map();
const panoCards = {
  trend:['SEM','投放节奏与主题贡献','按日看变化，拖动图表选择日期'],
  mix:['SEM','钱花在哪些业务上','点击主题，联动整个工作台'],
  funnel:['SEM','从点击到报表转化','报表转化仍需核验业务有效性'],
  device:['SEM','投放终端结构','按演示计划的终端分类'],
  organic:['SEO','自然搜索表现','整站示例 · 不分摊到业务主题或文章'],
  ranking:['SEO','搜索排名覆盖','期末快照 · 百度 PC / 全国'],
  content:['SEO','内容生产与发布','点击阶段查看文章和完成标准'],
  heatmap:['GEO','客户问题 × AI 引擎','点格子阅读原始回答与引用'],
  citations:['GEO','品牌提及与引用','模拟回答覆盖，不是正式可见度'],
  competition:['GEO','品牌与竞品同场出现','允许同时出现，不等同市场份额'],
  journey:['CROSS CHANNEL','同一主题，三条经营链路','主题关联不代表跨渠道归因'],
  execution:['OPERATIONS','行动进度与验收','任务当前状态，不按观测日期过滤'],
  health:['TRUST','这些数据能说明什么','先分清事实，再讨论原因']
};
function pScope(s=pano){return `${s.topic==='all'?'全部业务':s.topic} · ${dates[s.start]}—${dates[s.end]}`;}
function pRows(kind,s=pano){if(kind==='search'&&s.topic!=='all')return [];return panoramaData[kind].filter(r=>(s.topic==='all'||r.topic===s.topic)&&r.day>=s.start&&r.day<=s.end);}
function pSum(rows,field){return rows.reduce((n,r)=>n+(Number(r[field])||0),0);}
function pPct(a,b){return b?`${(a/b*100).toFixed(1)}%`:'—';}
function pStats(s=pano){const paid=pRows('paid',s),seo=pRows('search',s),a=pRows('answers',s);return {paid,seo,a,cost:pSum(paid,'cost'),clicks:pSum(paid,'clicks'),conv:pSum(paid,'conversions'),organic:s.topic==='all'?pSum(seo,'clicks'):null,mentions:a.filter(x=>x.mentioned).length,citations:a.filter(x=>x.cited).length};}
function pOrganic(value){return value===null?'未提供':num(value);}
function pSnapshot(){return {topic:pano.topic,start:pano.start,end:pano.end};}
function pChange(update){pano.history.push(pSnapshot());Object.assign(pano,update);renderPanorama();}
function pContext(){if(state.page==='panorama')$('#contextTitle').textContent=`${pScope()} · ${panoCards[pano.focus][1]}`;}
function pButton(label,action,value=''){return `<button data-pano="${action}" data-value="${esc(String(value))}">${label}</button>`;}
function pBars(items,action='topic'){const max=Math.max(1,...items.map(x=>x[1]));return `<div class="p-bars">${items.map(([name,value,key,color],i)=>`<button class="p-bar" data-pano="${action}" data-value="${esc(key||name)}"><span>${esc(name)}<b>${num(value)}</b></span><i><em style="width:${value/max*100}%;--bar:${color||panoramaData.palette[i%3]}"></em></i></button>`).join('')}</div>`;}
function pTrend(kind,s=pano){const paid=kind==='paid';const rows=pRows(kind,s);const max=Math.max(1,...rows.map(r=>r[paid?'cost':'clicks']));const selected=Array.from({length:s.end-s.start+1},(_,i)=>s.start+i);const x=d=>35+(d-s.start)*250/Math.max(1,selected.length-1),y=v=>116-v/max*91;
  return `<svg class="p-chart" data-p-chart="${kind}" viewBox="0 0 310 145" role="img" aria-label="${paid?'每日花费':'每日搜索点击'}，下方有可访问的日期筛选和明细按钮">${[0,.5,1].map(v=>`<line class="gridline" x1="35" x2="285" y1="${y(max*v)}" y2="${y(max*v)}"/><text x="0" y="${y(max*v)+3}">${Math.round(max*v)}</text>`).join('')}${panoramaData.topics.filter(t=>s.topic==='all'||t===s.topic).map(t=>{const c=panoramaData.palette[panoramaData.topics.indexOf(t)];return `<polyline class="series" stroke="${c}" points="${selected.map(d=>`${x(d)},${y(pSum(rows.filter(r=>r.day===d&&r.topic===t),paid?'cost':'clicks'))}`).join(' ')}"/>${selected.map(d=>{const v=pSum(rows.filter(r=>r.day===d&&r.topic===t),paid?'cost':'clicks');return `<circle cx="${x(d)}" cy="${y(v)}" r="4" fill="${c}"><title>${dates[d]} ${esc(t)} ${paid?'¥':''}${v}</title></circle>`;}).join('')}`;}).join('')}${selected.map(d=>`<text x="${x(d)}" y="139" text-anchor="middle">${dates[d]}</text>`).join('')}</svg><div class="p-hover">悬停读数 · 拖动选择日期 · 双击恢复整周</div><div class="p-legend">${panoramaData.topics.map((t,i)=>`<span><i style="background:${panoramaData.palette[i]}"></i>${t}</span>`).join('')}</div>`;
}
function pCardBody(key,s=pano){const v=pStats(s),a=v.a,content=pRows('content',s),kw=pRows('keywords',s);
  if(key==='trend')return pTrend('paid',s);
  if(key==='organic')return `<div class="p-mini-grid"><button data-pano="subset" data-value="ranking|Top 10"><b>${kw.filter(r=>r.rank<=10).length}</b>前十名关键词</button><button data-pano="detail" data-value="content"><b>${content.filter(r=>r.status==='已发布').length}</b>已发布内容</button></div><p>搜索点击 <b>${pOrganic(v.organic)}</b> · ${s.topic==='all'?'所选期间整站演示合计':'当前不支持按业务主题统计'}</p><p>每日走势与文章点击暂未提供。可点击查看关键词和内容记录。</p>`;
  if(key==='mix')return pBars(panoramaData.topics.map((t,i)=>[t,pSum(v.paid.filter(r=>r.topic===t),'cost'),t,panoramaData.palette[i]]))+`<p>当前范围花费 <b>${money(v.cost)}</b> · 主题选择同时作用于 SEO 和 GEO。</p>`;
  if(key==='funnel')return `<div class="p-flow">${[['展现',pSum(v.paid,'impressions')],['点击',v.clicks],['报表转化',v.conv]].map(([l,n])=>`<button data-pano="detail" data-value="funnel"><b>${num(n)}</b><small>${l}</small></button>`).join('<span>›</span>')}</div><p>点击率 ${pPct(v.clicks,pSum(v.paid,'impressions'))} · 报表转化率 ${pPct(v.conv,v.clicks)}</p><p>仅统计可记录的转化；追踪覆盖率未知。有效线索与成交金额尚未确认。</p>`;
  if(key==='device'){const mobile=pSum(v.paid.filter(r=>r.device==='移动端'),'cost');return `<div class="p-orbit"><div class="p-donut" style="background:conic-gradient(#65baff ${v.cost?mobile/v.cost*360:0}deg,#ad93ff 0)"><b>${pPct(mobile,v.cost)}<small>移动端花费</small></b></div><div style="flex:1">${pBars(['移动端','桌面端'].map(d=>[d,pSum(v.paid.filter(r=>r.device===d),'cost'),`device|${d}`]),'subset')}</div></div>`;}
  if(key==='ranking'&&!kw.length)return '<div class="p-empty">当前范围无排名快照<br>选择包含 09.06 的日期查看</div>';
  if(key==='ranking')return `<div class="p-mini-grid">${[['Top 3',r=>r.rank<=3],['Top 10',r=>r.rank<=10],['11—30',r=>r.rank>10]].map(([l,f])=>`<button data-pano="subset" data-value="ranking|${l}"><b>${kw.filter(f).length}</b>${l}</button>`).join('')}</div><p>${kw.length?`${kw.filter(r=>r.rank<r.previous).length} 个词较前次上升 · Top 3 包含于 Top 10。`:'当前日期内无排名快照，选择 09.06 查看。'}</p>`;
  if(key==='content')return `<div class="p-mini-grid">${['草稿','待审核','已审核待发布','已发布'].map((st,i)=>`<button data-pano="subset" data-value="content|${st}"><b style="color:${panoramaData.palette[i % panoramaData.palette.length]}">${content.filter(r=>r.status===st).length}</b>${st}</button>`).join('')}</div><p>审核、发布和页面检查分别确认。点击阶段查看文章、负责角色与下一步。</p>`;
  if(key==='heatmap'){const questions=[...new Set(a.map(r=>r.question))];return questions.length?`<div class="p-matrix"><span>问题 / 引擎</span>${['DeepSeek','豆包','通义'].map(x=>`<span>${x}</span>`).join('')}${questions.slice(0,4).map(q=>`<span title="${esc(q)}">${esc(q.split('：')[1])}</span>${['DeepSeek','豆包','通义千问'].map(en=>{const row=a.find(r=>r.question===q&&r.engine===en);return row?`<button data-pano="object" data-value="${row.id}" class="${row.cited?'cited':row.mentioned?'hit':''}" aria-label="${esc(q)} ${en} ${row.cited?'引用':row.mentioned?'提及':'未提及'}">${row.cited?'引用':row.mentioned?'提及':'—'}</button>`:'<span>无样本</span>';}).join('')}`).join('')}</div><p>${questions.length>4?`展示前 4 个问题，全部 ${questions.length} 个问题可展开查看。`:'蓝：自有域引用 · 绿：仅提及 · 灰：未提及。'}</p>`:'<div class="p-empty">当前筛选没有回答样本</div>';}
  if(key==='citations')return `<div class="p-orbit"><div class="p-donut" style="background:conic-gradient(#4bd9bd ${a.length?v.mentions/a.length*360:0}deg,#24364d 0)"><b>${v.mentions}/${a.length}<small>原始回答提及</small></b></div><div><p>品牌提及覆盖 <b>${pPct(v.mentions,a.length)}</b></p><p>自有域引用 <b>${v.citations} 条</b></p><p>正式 GEO 分数 <b>—</b></p></div></div><p>所有回答为模拟样本，不进入正式得分或趋势。</p>`;
  if(key==='competition')return pBars([['诺德新材料',v.mentions,'competition|brand'],['示例竞品',a.filter(r=>r.competitor).length,'competition|peer'],['两者同时出现',a.filter(r=>r.competitor&&r.mentioned).length,'competition|both']],'subset')+`<p>统计同一批 ${a.length} 条回答中的出现次数，可重叠。</p>`;
  if(key==='journey')return `<div class="p-flow"><button data-pano="detail" data-value="trend"><b>${money(v.cost)}</b><small>付费触达 / SEM</small></button><span>↔</span><button data-pano="detail" data-value="organic"><b>${pOrganic(v.organic)}</b><small>搜索点击 / SEO</small></button><span>↔</span><button data-pano="detail" data-value="heatmap"><b>${v.mentions}/${a.length}</b><small>回答提及 / GEO</small></button></div><p>以「${s.topic==='all'?'业务主题':esc(s.topic)}」对齐客户关注点。三者各有独立来源，按主题对照；不合计为线索，不计算获客贡献占比。</p>`;
  if(key==='execution')return `<div class="p-timeline">${allTasks().filter(t=>t.status!=='cancelled').slice(0,4).map(t=>`<button data-task="${esc(t.id)}"><i></i><span>${esc(t.title)}</span><small>${pSyntheticTask(t)?'演练 · ':''}${t.status==='draft'?'待确认':t.status==='verified'?(t.id.startsWith('DRILL-')?'本轮确认':'已验收'):'跟进中'} ›</small></button>`).join('')}</div>${pButton('查看全部行动 →','tasks')}`;
  if(key==='health')return `<div class="p-health">${['SEM','SEO','GEO'].map(m=>`<button data-pano="detail" data-value="health">${m}<b>演示</b>可追溯</button>`).join('')}</div><p>发现：按记录计算。解释：保留证据边界。执行：先形成方案和完成标准。</p>`;
  return '';
}
const panoPage=document.createElement('section');panoPage.id='page-panorama';panoPage.className='page';panoPage.setAttribute('aria-label','客户全景工作台');$('#pageScroll').prepend(panoPage);
const panoNav=document.createElement('button');panoNav.dataset.page='panorama';panoNav.textContent='全景工作台';$('.page-tabs').prepend(panoNav);
document.querySelector('[data-page="acquisition"]').textContent='预算试算';
document.querySelector('[data-page="dashboard"]').textContent='全部功能';
const panoNavigate=navigate;navigate=function(page){if(page==='panorama'){state.page=page;$$('.page').forEach(el=>el.classList.toggle('active',el===panoPage));$$('.page-tabs button').forEach(el=>el.classList.toggle('active',el.dataset.page===page));renderPanorama();return;}panoNavigate(page);};
function renderPanorama(){const v=pStats();panoPage.classList.toggle('compact',pano.compact);panoPage.innerHTML=`<div class="p-heading"><div><span class="p-eyebrow">NORD / GROWTH INTELLIGENCE</span><h1>每一份增长，都有迹可循。</h1><p>诺德新材料 · 获客、内容、品牌与执行，全景协同</p></div>${pButton('交互导览 ↗','tour')}</div><div class="p-controls"><button data-pano="topic" data-value="all" class="${pano.topic==='all'?'active':''}">全部业务</button>${panoramaData.topics.map(t=>`<button data-pano="topic" data-value="${t}" class="${pano.topic===t?'active':''}">${t}</button>`).join('')}</div><div class="p-controls"><label>从 <select id="pStart" aria-label="全景开始日期">${dates.map((d,i)=>`<option value="${i}" ${i===pano.start?'selected':''}>${d}</option>`).join('')}</select></label><label>至 <select id="pEnd" aria-label="全景结束日期">${dates.map((d,i)=>`<option value="${i}" ${i===pano.end?'selected':''}>${d}</option>`).join('')}</select></label>${pButton('↶ 撤销筛选','undo')}${pButton('重置','reset')}${pButton(pano.compact?'舒展视图':'紧凑视图','density')}<button data-pano="search">⌕ 搜索全部记录</button></div><div class="p-scope"><span><b>●</b> ${pScope()} · 图表与对话共用范围</span>${pButton(pano.compare?'与已保存的范围比较':'保存当前范围，稍后比较','compare')}</div><div id="pTour"></div><div class="p-kpis">${[['投放花费',money(v.cost),'当前范围合计','trend'],['投放点击',num(v.clicks),`报表转化 ${v.conv} 次`,'funnel'],['自然搜索点击',pOrganic(v.organic),'整站示例 · 主题点击未提供','organic'],['发布文章',pRows('content').filter(r=>r.status==='已发布').length,'点击查看页面与验收','content'],['AI 回答提到品牌',`${v.mentions} / ${v.a.length}`,'模拟样本 · 非正式得分','heatmap'],['待确认方案',localDrafts.filter(t=>t.status==='draft'&&!pSyntheticTask(t)).length,'保存在当前标签页','execution']].map(([l,n,sub,k])=>`<button class="p-kpi" data-pano="detail" data-value="${k}"><span>${l} ↗</span><b>${n}</b><small>${sub}</small></button>`).join('')}</div><div class="p-grid">${['trend','organic','heatmap','mix','content','citations','funnel','ranking','competition','device','journey','execution','health'].map(k=>[k,panoCards[k]]).map(([k,[m,title,sub]])=>`<article class="p-card ${k==='journey'?'wide':''} ${pano.expanded.has(k)?'expanded':''}" data-card="${k}"><header><div><small>${m}</small><h2>${title}</h2></div><div><button data-pano="expand" data-value="${k}" aria-label="${pano.expanded.has(k)?'缩小':'放大'}${title}" title="放大 / 缩小">⛶</button><button data-pano="detail" data-value="${k}" aria-label="弹出${title}" title="独立详情窗口">↗</button></div></header><div class="p-body">${pCardBody(k)}</div><footer><span>${sub}</span><button data-pano="discuss" data-value="${k}">和助手讨论 →</button></footer></article>`).join('')}</div><p class="p-caption">完整演示场景 · 21 条投放记录 / 整站搜索合计示例 / 18 篇内容 / 24 个关键词 / 36 条模拟回答。全部数字由同一组场景记录计算；全部功能中的独立业务演练不计入本场景。旧版预算试算保留原始词组口径。</p>`;pContext();pBindCharts();pTourRender();}
function pBindCharts(){panoPage.querySelectorAll('[data-p-chart]').forEach(svg=>{let start=null;const idx=e=>{const r=svg.getBoundingClientRect();return Math.max(pano.start,Math.min(pano.end,Math.round(pano.start+((e.clientX-r.left)/r.width*310-35)/250*(pano.end-pano.start))));};svg.addEventListener('pointermove',e=>{const d=idx(e),rows=pRows(svg.dataset.pChart).filter(r=>r.day===d);svg.nextElementSibling.textContent=`${dates[d]} · ${rows.map(r=>`${r.topic} ${svg.dataset.pChart==='paid'?money(r.cost):r.clicks+' 点击'}`).join(' / ')}`;});svg.addEventListener('pointerdown',e=>{start=idx(e);svg.setPointerCapture(e.pointerId);});svg.addEventListener('pointerup',e=>{if(start!==null){const end=idx(e);if(end!==start)pChange({start:Math.min(start,end),end:Math.max(start,end)});start=null;}});svg.addEventListener('dblclick',()=>pChange({start:0,end:6}));});}
function pTourRender(){const el=$('#pTour');if(!el||!pano.tour)return;const steps=[['1 / 4 · 先说你关心的业务','左侧对话贯穿全过程。可问整体情况、具体模块、证据与下一步。'],['2 / 4 · 从全景缩到具体范围','点业务主题或修改日期，观察所有图表联动；支持撤销和范围比较。'],['3 / 4 · 让每个判断有依据','图卡右上角放大或弹出，格子、柱条和文章阶段都可点到原始对象。'],['4 / 4 · 把讨论变成可跟进的行动','选择建议方案，填写负责人和完成标准；存入台账后可编辑、撤回、返回上下文。']];const [title,body]=steps[pano.tour-1];el.innerHTML=`<div class="p-tour"><div><b>${title}</b>${body}<div class="p-stepper">${steps.map((_,i)=>`<span class="${i<pano.tour?'on':''}"></span>`).join('')}</div></div>${pButton(pano.tour===4?'开始体验':'下一步','tourNext')}${pButton('×','tourClose')}</div>`;}
function pRecordRows(key,s,subset=''){
  let rows=['trend','mix','funnel','device'].includes(key)?pRows('paid',s):key==='organic'?pRows('search',s):key==='content'?pRows('content',s):key==='ranking'?pRows('keywords',s):pRows('answers',s);
  if(key==='device'&&subset)rows=rows.filter(r=>r.device===subset);
  if(key==='content'&&subset)rows=rows.filter(r=>r.status===subset);
  if(key==='ranking'&&subset)rows=rows.filter(r=>subset==='Top 3'?r.rank<=3:subset==='Top 10'?r.rank<=10:r.rank>10);
  if(key==='competition'&&subset)rows=rows.filter(r=>subset==='brand'?r.mentioned:subset==='peer'?r.competitor:r.mentioned&&r.competitor);
  return rows;
}
function pDetails(key,s,subset=''){
  const rows=pRecordRows(key,s,subset),paid=['trend','mix','funnel','device'].includes(key),ai=['heatmap','citations','competition'].includes(key);
  let body='';
  if(key==='health')body=`<h3>本场景的事实范围</h3>${table(['模块','可解释内容','不能推断'],[['SEM','花费、点击、展现、报表转化、主题与终端','有效商机、成交、真实投资回报'],['SEO','搜索点击、关键词快照、内容工作流','付费替代效果、内容带来多少成交'],['GEO','模拟回答、提及、引用和同场竞品','正式可见度、行业份额、同比增长']])}<h3>发现与解释分开</h3><p>图表直接从场景记录汇总；原因仅作为待核验假设。模拟回答不能进入正式 GEO 得分。数据为空时显示空状态，不把缺数补成业务为零。</p><p>本场景使用演示主题映射串联模块，日期指观测或事件日期；关键词为 09.06 快照，任务为当前状态。</p>`;
  else if(key==='organic')body=pCardBody(key,s)+`<h3>查看范围说明</h3><p>站点搜索点击目前不能拆到业务主题或单篇文章。排名和内容记录可分别查看；未提供不代表没有效果。</p>`;
  else if(key==='execution')body=pCardBody(key,s);
  else if(key==='journey')body=pCardBody(key,s)+`<h3>可沿着同一主题继续查看</h3>${['trend','organic','heatmap'].map(k=>pButton(panoCards[k][1],'detail',k)).join(' ')}`;
  else if(!rows.length)body='<div class="p-empty">这个范围没有记录。可返回全景调整日期或清除主题筛选。</div>';
  else body=`<p>${rows.length} 条匹配记录${subset?' · '+esc(subset):''}。点击记录编号查看字段、出处和后续动作。</p><div class="p-table-scroll">${paid?table(['记录','日期 / 主题','花费','点击','转化','终端'],rows.map(r=>[pButton(r.id,'object',r.id),`${r.date}<br>${r.topic}`,money(r.cost),r.clicks,r.conversions,r.device])):ai?table(['记录','问题 / 引擎','日期','提及','引用'],rows.map(r=>[pButton(r.id,'object',r.id),`${esc(r.question)}<br>${r.engine}`,r.date,r.mentioned?'是':'否',r.cited?'自有域':'无'])):key==='organic'?table(['记录','日期','主题','点击'],rows.map(r=>[pButton(r.id,'object',r.id),r.date,r.topic,r.clicks])):key==='ranking'?table(['记录','关键词','本次排名','前次排名'],rows.map(r=>[pButton(r.id,'object',r.id),esc(r.title),r.rank,r.previous])):table(['记录','文章','状态','负责人'],rows.map(r=>[pButton(r.id,'object',r.id),esc(r.title),r.status,r.owner]))}</div>`;
  return `<div class="p-detail"><h2>${panoCards[key][1]}</h2><p>${pScope(s)} · 固定快照${subset?' · '+esc(subset):''}</p>${body}<p class="p-statusline">场景模拟数据 · 与全景使用同一记录集 · 详情窗口保留打开时的范围。</p>${pButton('讨论这一范围','snapshotDiscuss',s.snapshotKey||'')}${pButton('安排下一步','plan',key)}</div>`;
}
const pOldTitle=panelTitle,pOldContent=panelContent;
panelTitle=function(key){return panoSnapshots.has(key)?panoCards[panoSnapshots.get(key).card][1]:pOldTitle(key);};
panelContent=function(key,scope){if(!panoSnapshots.has(key))return pOldContent(key,scope);const s=panoSnapshots.get(key);return pDetails(s.card,s,s.subset);};
function pOpen(key,subset='',scope=pSnapshot()){
  pano.focus=key;pContext();const id=`pano_${key}_${scope.topic}_${scope.start}_${scope.end}_${subset}`;panoSnapshots.set(id,{...scope,card:key,subset,snapshotKey:id});openPanel(id,'week');const win=[...panels.values()].find(p=>p.key===id);if(win){const label=win.el.querySelector('.scope-chip');if(label)label.textContent=pScope(scope);}if(innerWidth<=620)setMode('split');
}
function pObject(id){const r=panoramaData.all.find(x=>x.id===id);if(!r)return;const labels={id:'记录编号',date:'观测 / 事件日期',topic:'业务主题',cost:'花费（元）',clicks:'点击',impressions:'展现',conversions:'报表转化',device:'终端',plan:'投放计划',source:'来源',title:'对象',status:'状态',owner:'负责人',url:'页面路径',criterion:'完成标准',rank:'本次排名',previous:'前次排名',question:'问题',engine:'回答引擎',mentioned:'品牌提及',cited:'自有域引用',competitor:'示例竞品出现',simulated:'模拟样本'};showDialog('OBJECT / 原始对象',`<div class="p-detail"><h2>${esc(r.title||r.question||r.topic)}</h2><p>${r.id} · ${r.date} · ${esc(r.source)}</p>${r.answer?`<h3>回答原文 · 演示</h3><blockquote>${esc(r.answer)}</blockquote><p>引用：${esc(r.citation)}</p>`:''}${table(['字段','值'],Object.entries(r).filter(([k])=>labels[k]).map(([k,v])=>[labels[k],esc(typeof v==='boolean'?(v?'是':'否'):String(v))]))}<h3>与这个对象继续工作</h3><p>回到所属主题对比三条业务链路，或将本条记录作为核验依据。</p>${pButton('带入对话','objectDiscuss',r.id)} ${pButton('按所属主题查看全景','objectTopic',r.id)} ${pButton('拟定核验行动','objectPlan',r.id)}</div>`);}
function pCompare(){if(!pano.compare){pano.compare=pSnapshot();renderPanorama();toast('已固定当前范围。切换主题或日期后，再点比较。');return;}const a=pStats(pano.compare),b=pStats();showDialog('COMPARE / 范围比较',`<div class="p-detail"><h2>两个范围，并排看清楚</h2><div class="p-comparison">${[[pano.compare,a],[pano,b]].map(([s,v])=>`<div><b>${pScope(s)}</b><p>花费 ${money(v.cost)}</p><p>投放点击 ${num(v.clicks)}</p><p>报表转化 ${v.conv}</p><p>自然搜索点击 ${pOrganic(v.organic)}</p><p>原始回答提及 ${v.mentions}/${v.a.length}</p></div>`).join('')}</div><p>绝对花费差 ${money(b.cost-a.cost)}。范围长度或主题不同，不能仅凭差值判断效率变好；模拟回答比例不代表品牌增长。</p>${pButton('重新固定当前范围','compareReset')} ${pButton('回到全景','close')}</div>`);}
function pSearch(query=''){showDialog('SEARCH / 全部业务对象',`<div class="p-detail"><h2>找到记录，直接继续工作</h2><input id="pObjectSearch" type="search" aria-label="搜索全景对象" placeholder="输入主题、文章、引擎、记录编号…" value="${esc(query)}"><p>搜索完整场景的 ${panoramaData.all.length} 条对象；不受看板筛选限制。</p><div id="pSearchResults"></div></div>`);pSearchResults(query);$('#pObjectSearch').focus();}
function pSearchResults(q){const rows=panoramaData.all.filter(r=>[r.id,r.topic,r.title,r.question,r.engine,r.plan,r.status].filter(Boolean).join(' ').toLowerCase().includes(q.toLowerCase()));$('#pSearchResults').innerHTML=`<p>${rows.length} 条匹配${rows.length>30?' · 展示前 30 条，请输入更具体的条件':''}</p>`+rows.slice(0,30).map(r=>`<button class="p-result-row" data-pano="object" data-value="${r.id}">${esc(r.title||r.question||r.plan||r.topic)}<small>${r.id} · ${r.date} · ${esc(r.source)}</small></button>`).join('')+(!rows.length?'<div class="p-empty">没有找到匹配对象，请试试“智能仓储”“待审核”或“DeepSeek”。</div>':'');}
const pPlans={verify:['确认广告带来的咨询是否有效','核对当前范围内平台记录的每次转化，确认是否有效、客户想了解什么，以及是否重复。','每条转化均有有效性结论和核验记录；再讨论预算调整。'],content:['推动内容审核与发布','逐篇检查待审核文章的事实、页面和发布条件，安排审核负责人。','待审核文章逐篇有审核结论；通过者保留发布与重抓证据。'],geo:['获取真实 AI 回答，方便以后比较','选定问题和 AI 平台，保存真实回答及引用来源，作为以后比较的依据。','真实样本满足正式指标要求，排除模拟数据；两期口径一致后才比较。']};
function pSyntheticTask(t){return t?.scenarioKind==='synthetic'||t?.sourcePano?.scenarioKind==='synthetic'||String(t?.sourcePano?.object||'').startsWith('GEO-DEMO-');}
function pPlan(type='verify',objectId='',existingId=''){if(!pPlans[type])type=['organic','ranking','content'].includes(type)?'content':['heatmap','citations','competition'].includes(type)?'geo':'verify';const existing=localDrafts.find(t=>t.id===existingId),[title,note,criterion]=pPlans[type];showDialog('ACTION / 方案确认',`<div class="p-detail"><h2>${existing?'修改':'安排'}下一步</h2><p>${pScope()}${objectId?' · 依据 '+esc(objectId):''}</p><form id="pPlanForm" data-scenario-kind="${pSyntheticTask(existing)||String(objectId).startsWith('GEO-DEMO-')?'synthetic':'prototype'}" data-type="${type}" data-object="${esc(objectId)}" data-existing="${esc(existingId)}" data-decision-choice="${esc(existing?.sourcePano?.decisionChoice||'')}"><label>行动名称<input name="title" required maxlength="120" value="${esc(existing?.title||title)}"></label><label>负责人<input name="owner" required maxlength="60" placeholder="例如：客户运营负责人" value="${esc(existing?.owner||'客户运营负责人')}"></label><label>检查日期<input type="date" name="due" required value="${esc(existing?.due||'2026-09-13')}"></label><label>执行说明<textarea name="note" rows="3" required maxlength="1200">${esc(existing?.note||note)}</textarea></label><label>完成标准<textarea name="criterion" rows="3" required maxlength="1200">${esc(existing?.criterion||criterion)}</textarea></label><p>保存到当前标签页的待办与进度。此处完成原型中的确认流程，不向外部模块发出任务。</p><button class="primary-button" type="submit">${existing?'保存修改':'确认并保存方案'}</button></form></div>`);}
function pSuggestions(){$('#chatSuggestions').innerHTML=['整体情况怎么样？','优先处理什么？'].map(q=>`<button data-question="${q}">${q}</button>`).join('')+`<details class="chat-more"><summary>更多指引</summary><div>${['为什么会这样？','看看内容进度','品牌被怎样提及？','启动转化核验演练','启动内容审核演练'].map(q=>`<button data-question="${q}">${q}</button>`).join('')}</div></details>`;}
function pTalk(key='overview',question='',scope=pSnapshot()){
  if(question)addMessage('user',question);showChat();const v=pStats(scope);let html='',actions=[];
  const detailKey=panoCards[key]?key:pano.focus;const replySnapshot='reply_'+Date.now()+'_'+panoSnapshots.size;panoSnapshots.set(replySnapshot,{...scope,card:detailKey});const action=(label,k)=>({label,action:'panoTalk',key:k==='evidence'?'evidence~'+replySnapshot:k});
  if(key==='overview')html=`<p>我们把 <strong>${pScope(scope)}</strong> 放在一起看。</p><div class="p-chat-summary"><div><b>${money(v.cost)}</b>投放花费</div><div><b>${pOrganic(v.organic)}</b>搜索点击</div><div><b>${v.mentions}/${v.a.length}</b>回答提及</div></div><p><strong>获客：</strong>${v.clicks} 次点击、${v.conv} 次报表转化。应先确认转化质量，再判断预算效率。</p><p><strong>内容：</strong>${pRows('content',scope).filter(r=>r.status==='待审核').length} 篇待审核；发布与后续搜索表现分开跟进。</p><p><strong>品牌：</strong>这里能逐条看回答和引用，当前都是模拟样本，正式可见度保持空缺。</p><p>我建议先选择一个业务主题，沿着“发生了什么、依据是什么、接下来做什么”继续。</p>`;
  else if(key==='plan'){html=`<p>当前范围：<strong>${pScope(scope)}</strong>。有三条可直接推进的路径，先处理会影响决策的证据缺口。</p>${Object.entries(pPlans).map(([k,[title,note]])=>`<div class="p-plan-card"><span>${k==='verify'?'01 · 先确认':k==='content'?'02 · 处理文章':'03 · 记录当前表现'}</span><b>${title}</b><p>${note}</p>${pButton('查看并确认方案','plan',k)}</div>`).join('')}<p>可以分别确认，也可以先讨论。方案会记录业务范围、负责人、检查日期和完成标准。</p>${pButton('打开交互式预算试算','budget')}`;}
  else if(key==='why')html=`<p>先把<strong>已经观察到的事实</strong>与<strong>尚待验证的原因</strong>分开。</p><p>当前 ${pScope(scope)}：花费 ${money(v.cost)}，报表转化 ${v.conv} 次，搜索点击 ${v.organic===null?'未提供':pOrganic(v.organic)+' 次'}。</p><p>转化质量、词包结构、落地页匹配都可能影响投放表现，但现有记录没有证明哪一个是原因。可以先确认转化，再对照关键词和页面。</p><p>搜索点击和 AI 回答来自不同渠道，不能直接说明它们让付费成本下降。</p>`;
  else if(key==='execution'){html=`<p>目前有 <strong>${localDrafts.filter(t=>t.status==='draft'&&!pSyntheticTask(t)).length} 份本地待确认草稿</strong>，以及 ${seedTasks.length} 项示例跟进行动。</p><p>这批图片还需完成剩余验收；标题修复有复查通过记录；GEO 基线仍待准备。执行完成与效果验收是两个状态。</p>`;actions=[{label:'打开待办与进度',action:'panoTalk',key:'tasks'}];}
  else if(['content','ranking','organic'].includes(key))html=`<p><strong>${pScope(scope)} · 搜索与内容</strong></p><p>搜索点击 ${v.organic===null?'未提供':pOrganic(v.organic)+' 次'}。内容记录 ${pRows('content',scope).length} 篇，其中已发布 ${pRows('content',scope).filter(r=>r.status==='已发布').length} 篇、待审核 ${pRows('content',scope).filter(r=>r.status==='待审核').length} 篇。</p><p>你可以从待审核文章入手，逐篇确认事实与发布条件；排名是 09.06 的独立快照，不等于文章带来的流量。</p>`;
  else if(['heatmap','citations','competition'].includes(key))html=`<p><strong>${pScope(scope)} · 品牌回答覆盖</strong></p><p>${v.a.length} 条模拟回答中，${v.mentions} 条提及品牌，${v.citations} 条引用品牌自有域名。回答原文、问题与引擎都可以逐条查看。</p><p>这些值只描述当前演示样本，不能作为正式 GEO 分数或品牌增长证明。下一步可固定问题集和引擎，设计真实观测基线。</p>`;
  else if(key==='health')html='<p>数据层负责发现并计算；对话层负责解释、提出待验证假设并指导下一步。本场景所有记录均可追查，但均为演示。</p><p>投放报表转化不等于有效商机；SEO 不支持主题或单篇点击归因；模拟 GEO 回答不进入正式指标。缺失信息明确保留为空。</p>';
  else html=`<p><strong>${pScope(scope)} · 获客分析</strong></p><p>花费 ${money(v.cost)}，${num(v.clicks)} 次点击，${v.conv} 次报表转化。报表转化成本 ${v.conv?money(v.cost/v.conv):'—'}，业务有效性仍需核对。</p><p>右侧可按主题、终端和日期拆开查看。我建议先看明细中的转化记录，再考虑预算方案；仅凭点击或花费不能断定获客好坏。</p>`;
  if(!actions.length)actions=key==='plan'?[action('先看证据','why')]:[action('查看对应明细','evidence'),action('讨论下一步','plan'),action('回到全景','home')];
  addMessage('assistant',html,actions);if(!['execution','health'].includes(key)&&typeof chatReplyScope==='function')chatReplyScope(replySnapshot);pSuggestions();if(state.page==='panorama'&&panoCards[key]){pano.focus=key;pContext();panoPage.querySelectorAll('.p-card').forEach(c=>c.classList.toggle('is-focused',c.dataset.card===key));panoPage.querySelector('[data-card="'+key+'"]')?.scrollIntoView({block:'nearest',behavior:'smooth'});}
}
const pPreviousReply=reply;
reply=function(q){if(state.page!=='panorama'){pPreviousReply(q);return;}const topic=panoramaData.topics.find(t=>q.includes(t));if(topic)pChange({topic});let key=/方案|优先|下一步|怎么办|如何做|怎么做/.test(q)?'plan':/为什么|原因|风险|依据/.test(q)?'why':/进度|上次|任务|待办|台账/.test(q)?'execution':/品牌|GEO|geo|AI|提及|引用/.test(q)?'heatmap':/内容|SEO|seo|自然|文章/.test(q)?'content':/排名/.test(q)?'ranking':/花费|投放|SEM|sem|预算|转化/.test(q)?'trend':/整体|情况|总览|全景/.test(q)?'overview':null;if(!key){addMessage('user',q);addMessage('assistant','<p>这个自由问题尚未编排进原型演示。我可以结合当前筛选范围解释获客、内容、品牌回答和行动进度，也可以带你逐条核对记录。</p>',[{label:'解释当前图表',action:'panoTalk',key:pano.focus},{label:'给出下一步方案',action:'panoTalk',key:'plan'}]);return;}if(panoCards[key])pano.focus=key;pContext();pTalk(key,q);};
resetChat=function(){$('#chatStream').replaceChildren();navigate('panorama');pano.focus='trend';pContext();addMessage('assistant',`<h2>诺德的增长，我们一起看清。</h2><p>我会结合<strong>投放、内容和品牌表现</strong>，帮你核对依据、比较方案，并跟进每一项行动。右侧图表可以直接点开讨论。</p><div class="p-chat-summary"><div><b>3</b>业务主题</div><div><b>13</b>全景视角</div><div><b>120</b>可追查对象</div></div>`,[{label:'带我看整体情况',action:'panoTalk',key:'overview'},{label:'告诉我优先做什么',action:'panoTalk',key:'plan'},{label:'跟进已有行动',action:'panoTalk',key:'execution'}]);pSuggestions();$('#chatStream').scrollTop=0;};
document.addEventListener('click',e=>{
  const ledger=e.target.closest('[data-action="withdraw"],[data-action="restoreDraft"]');
  if(ledger){const t=localDrafts.find(x=>x.id===ledger.dataset.key);if(t?.sourcePano){e.preventDefault();e.stopImmediatePropagation();const restore=ledger.dataset.action==='restoreDraft';if(restore&&localDrafts.some(x=>x.id!==t.id&&x.status==='draft'&&x.sourcePano&&x.sourcePano.type===t.sourcePano.type&&(x.sourcePano.decisionChoice||'')===(t.sourcePano.decisionChoice||'')&&x.sourcePano.object===t.sourcePano.object&&pScope(x.sourcePano.scope)===pScope(t.sourcePano.scope))){toast('相同范围已有方案，不能重复恢复。');return;}t.status=restore?'draft':'cancelled';persist();renderTasks();renderPanorama();showTask(t.id);toast(restore?'方案已恢复。':'方案已撤回，记录保留。');return;}}
  const explain=e.target.closest('[data-win="explain"]');
  if(explain){const win=[...panels.values()].find(p=>p.el===explain.closest('.detail-window'));if(win&&panoSnapshots.has(win.key)){e.preventDefault();e.stopImmediatePropagation();const s=panoSnapshots.get(win.key);pano.focus=s.card;pTalk(s.card,`解释这份明细：${pScope(s)}`,s);return;}}
  const b=e.target.closest('[data-pano],[data-action="panoTalk"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();const action=b.dataset.pano,k=b.dataset.value||'';
  if(b.dataset.action==='panoTalk'){const key=b.dataset.key;if(key.startsWith('evidence~')){const s=panoSnapshots.get(key.slice(9));if(s)pOpen(s.card,'',s);return;}if(key==='tasks'){navigate('tasks');return;}if(key==='home'){navigate('panorama');panels.forEach(p=>p.el.hidden=true);dock();return;}if(key==='evidence'){pOpen(pano.focus);return;}pTalk(key,b.textContent);return;}
  if(action==='topic'){pChange({topic:k});return;}
  if(action==='undo'){if(pano.history.length){Object.assign(pano,pano.history.pop());renderPanorama();}else toast('已经是最初的筛选范围。');return;}
  if(action==='reset'){pChange({topic:'all',start:0,end:6});return;}
  if(action==='density'){pano.compact=!pano.compact;renderPanorama();return;}
  if(action==='expand'){pano.expanded.has(k)?pano.expanded.delete(k):pano.expanded.add(k);renderPanorama();panoPage.querySelector(`[data-card="${k}"]`).scrollIntoView({block:'nearest',behavior:'smooth'});return;}
  if(action==='detail'){pOpen(k);return;}
  if(action==='subset'){const [key,subset]=k.split('|');pOpen(key,subset);return;}
  if(action==='object'){pObject(k);return;}
  if(action==='objectTopic'){const r=panoramaData.all.find(x=>x.id===k);closeDialog();panels.forEach(p=>p.el.hidden=true);dock();pChange({topic:r.topic});navigate('panorama');return;}
  if(action==='objectDiscuss'){const r=panoramaData.all.find(x=>x.id===k);closeDialog();showChat();addMessage('user',`讨论 ${r.id}：${r.title||r.question||r.topic}`);addMessage('assistant',`<p>当前对象是 <strong>${esc(r.id)} · ${esc(r.topic)}</strong>，观测 / 事件日期 ${r.date}。</p><p>${esc(r.answer||r.criterion||(r.cost!==undefined?`这条投放记录花费 ${money(r.cost)}、点击 ${r.clicks}、报表转化 ${r.conversions} 次，需核验转化有效性。`:r.rank!==undefined?`本次排名 ${r.rank}、前次排名 ${r.previous}，仅代表这个关键词的快照。`:`本条搜索记录 ${r.clicks} 次点击，属于演示主题映射。`))}</p><p>来源：${esc(r.source)}。</p>${pButton('为这个对象拟定行动','objectPlan',r.id)}`);return;}
  if(action==='objectPlan'){const r=panoramaData.all.find(x=>x.id===k);pChange({topic:r.topic,start:Math.min(pano.start,r.day),end:Math.max(pano.end,r.day)});pPlan(r.id.startsWith('AI')?'geo':r.id.startsWith('AD')?'verify':'content',k);return;}
  if(action==='discuss'){pano.focus=k;pContext();pTalk(k,`帮我解读：${panoCards[k][1]}`);return;}
  if(action==='snapshotDiscuss'){const s=panoSnapshots.get(k);if(s){pano.focus=s.card;pTalk(s.card,`解释 ${pScope(s)} 的${panoCards[s.card][1]}`,s);}return;}
  if(action==='plan'){const win=[...panels.values()].find(p=>p.el===b.closest('.detail-window'));const snapshot=win&&panoSnapshots.get(win.key);if(snapshot)pChange({topic:snapshot.topic,start:snapshot.start,end:snapshot.end});closeDialog();pPlan(k);return;}
  if(action==='budget'){acquisition.start=pano.start;acquisition.end=pano.end;acquisition.scope='all';navigate('acquisition');renderAcquisition();return;}if(action==='tasks'){navigate('tasks');return;}
  if(action==='search'){pSearch();return;}
  if(action==='compare'){pCompare();return;}
  if(action==='compareReset'){pano.compare=pSnapshot();closeDialog();renderPanorama();toast('比较基准已更新。');return;}
  if(action==='close'){closeDialog();return;}
  if(action==='tour'){pano.tour=1;pTourRender();return;}
  if(action==='tourNext'){pano.tour=pano.tour===4?0:pano.tour+1;renderPanorama();return;}
  if(action==='tourClose'){pano.tour=0;renderPanorama();return;}
  if(action==='taskReturn'){const t=localDrafts.find(x=>x.id===k);if(t?.sourcePano){closeDialog();pChange(t.sourcePano.scope);navigate('panorama');}return;}
},true);
document.addEventListener('change',e=>{if(e.target.id==='pStart'){const start=Number(e.target.value);pChange({start,end:Math.max(start,pano.end)});}if(e.target.id==='pEnd'){const end=Number(e.target.value);pChange({end,start:Math.min(end,pano.start)});}});
document.addEventListener('input',e=>{if(e.target.id==='pObjectSearch')pSearchResults(e.target.value);});
document.addEventListener('submit',e=>{if(e.target.id!=='pPlanForm')return;e.preventDefault();const f=e.target;if(!f.reportValidity())return;const values=Object.fromEntries(new FormData(f));for(const k of ['title','owner','note','criterion'])values[k]=values[k].trim();if(Object.values(values).some(v=>!v)){toast('请填写完整的行动、负责人和验收信息。');return;}const type=f.dataset.type,object=f.dataset.object,existing=f.dataset.existing,scope=pSnapshot();const duplicate=localDrafts.find(t=>t.status==='draft'&&t.sourcePano&&t.sourcePano.type===type&&(t.sourcePano.decisionChoice||'')===(f.dataset.decisionChoice||'')&&t.sourcePano.object===object&&pScope(t.sourcePano.scope)===pScope(scope)&&t.id!==existing);if(duplicate){showTask(duplicate.id);toast('同一范围已有该方案，请编辑现有草稿。');return;}const scenarioKind=f.dataset.scenarioKind==='synthetic'?'synthetic':'prototype';const task={...values,scenarioKind,handoff:localDrafts.find(x=>x.id===existing)?.handoff,id:existing||'LOCAL-'+Date.now().toString(36).toUpperCase(),issue:type==='geo'?'visibility':type==='content'?'images':'allocation',plan:'verify',reduction:0,status:'draft',sourcePano:{type,object,scope,scenarioKind,decisionChoice:f.dataset.decisionChoice||'',guidance:(typeof guideCapture==='function'?guideCapture(object,scope):null)||localDrafts.find(x=>x.id===existing)?.sourcePano?.guidance||null}};if(existing)localDrafts=localDrafts.map(t=>t.id===existing?task:t);else localDrafts.unshift(task);const saved=persist();renderTasks();renderPanorama();closeDialog();showChat();addMessage('assistant',`<p>方案已${existing?'更新':'保存'}：<strong>${esc(task.title)}</strong>。</p><p>${pScope(scope)}${object?' · '+esc(object):''}<br>负责人：${esc(task.owner)} · 检查日期：${task.due}</p><p>${saved?'保存在当前标签页，刷新后可继续查看。':'浏览器存储不可用，仅本次页面有效。'}可从台账修改、撤回或返回业务范围。</p>`,[{label:'查看待办与完成标准',task:task.id}]);toast('方案已保存到待办与进度。');});
const panoShowTask=showTask;showTask=function(id){panoShowTask(id);const t=localDrafts.find(x=>x.id===id);if(t?.sourcePano)$('#dialogBody').insertAdjacentHTML('beforeend',`<div class="p-detail">${pSyntheticTask(t)?'<p><strong>独立合成演练</strong> · 不计入客户待确认方案，不作为对外执行依据。</p>':''}<p>当时查看的业务与日期：${pScope(t.sourcePano.scope)}${t.sourcePano.object?' · '+esc(t.sourcePano.object):''}</p>${pButton('返回这个业务范围','taskReturn',id)}</div>`);};
const panoShowDraft=showDraft;showDraft=function(id){const t=localDrafts.find(x=>x.id===id);if(t?.sourcePano){pChange(t.sourcePano.scope);pPlan(t.sourcePano.type,t.sourcePano.object,id);return;}panoShowDraft(id);};
window.addEventListener('click',e=>{if(state.page==='panorama'&&e.target.closest('#contextTitle')){e.preventDefault();e.stopImmediatePropagation();pOpen(pano.focus);}},true);
document.documentElement.style.setProperty('--chat-width','39vw');
$('.composer-bottom small').textContent='交互演示 · 回答跟随当前范围';
resetChat();
