/* Drill-down fixtures partition existing paid rows; no additional channel totals. */
function semSplit(total,weights){const parts=weights.map(w=>Math.floor(total*w));for(let i=0,left=total-parts.reduce((a,b)=>a+b,0);left>0;left--,i++)parts[i%parts.length]++;return parts;}
const semKeywordRows=panoramaData.paid.flatMap(row=>{
  const costs=semSplit(Math.round(row.cost*100),[.5,.3,.2]),clicks=semSplit(row.clicks,[.5,.3,.2]),impressions=semSplit(row.impressions,[.5,.3,.2]),conv=semSplit(row.conversions,[.5,.3,.2]);
  return ['方案','系统','厂家'].map((suffix,i)=>({id:`SK-${panoramaData.topics.indexOf(row.topic)+1}${i+1}`,title:row.topic+suffix,topic:row.topic,day:row.day,date:row.date,sourceId:row.id,cost:costs[i]/100,clicks:clicks[i],impressions:impressions[i],conversions:conv[i],device:row.device,plan:row.plan}));
});
function semDepthRows(scope=pSnapshot(),id=null){return semKeywordRows.filter(r=>(scope.topic==='all'||r.topic===scope.topic)&&r.day>=scope.start&&r.day<=scope.end&&(!id||r.id===id));}
function semDepthKeywords(scope=pSnapshot()){const rows=semDepthRows(scope);return [...new Set(rows.map(r=>r.id))].map(id=>{const list=rows.filter(r=>r.id===id);return {...list[0],cost:pSum(list,'cost'),clicks:pSum(list,'clicks'),impressions:pSum(list,'impressions'),conversions:pSum(list,'conversions')};}).sort((a,b)=>b.cost-a.cost);}
function semDepthList(scope=pSnapshot()){const rows=semDepthKeywords(scope),max=Math.max(1,...rows.map(r=>r.cost));return `<div class="sem-keywords">${rows.map(r=>`<button data-sem-keyword="${r.id}" data-sem-scope="${esc(JSON.stringify(scope))}"><span>${esc(r.title)}<small>${r.clicks} 点击 · ${r.conversions} 次报表转化</small></span><strong>${money(r.cost)}</strong><i style="--share:${r.cost/max*100}%"></i></button>`).join('')}</div><p class="sem-fixture-note">关键词拆分为演示设定，合计与当前投放一致；不是已接入的真实词报表。</p>`;}
panoCards.semkeywords=['SEM','哪些广告关键词值得关注','选择关键词，查看查询、终端、地域、时段及操作记录'];
dashboardGroups[0].cards.splice(1,0,'semkeywords');
decisionCases.acquisition.cards.push('semkeywords');
const semDepthCard=pCardBody;pCardBody=function(key){return key==='semkeywords'?semDepthList():semDepthCard(key);};
const semDepthDetails=pDetails;pDetails=function(key,scope,subset=''){return key==='semkeywords'?`<h2>哪些广告关键词值得关注</h2><p>${pScope(scope)} · 当前查看范围</p>${semDepthList(scope)}`:semDepthDetails(key,scope,subset);};
const semDepthRender=renderPanorama;renderPanorama=function(){const retained=fluidOpen?.key==='semkeywords'?{...fluidOpen}:null;semDepthRender();if(retained)fluidOpen=retained;const grid=panoPage.querySelector('.p-grid');if(!grid)return;const card=document.createElement('article');card.className='p-card';card.dataset.card='semkeywords';card.innerHTML=`<header><div><small>SEM</small><h2>哪些广告关键词值得关注</h2></div><div><button data-pano="expand" data-value="semkeywords"></button><button data-pano="detail" data-value="semkeywords" aria-label="弹出哪些广告关键词值得关注">↗</button></div></header><div class="p-body">${semDepthList()}</div><footer><span>点选关键词，继续查证与安排核实</span></footer>`;grid.append(card);card.hidden=!!decision.active&&!decision.allCharts&&!decisionCases[decision.active].cards.includes('semkeywords');fluidDecorate();dashboardArrange();if(fluidOpen?.key==='semkeywords'&&!card.hidden)fluidApply('semkeywords',false);};
let semDepth=null;
const semDepthTabs=[['summary','概览'],['queries','客户搜了什么'],['device','手机或电脑'],['region','地域'],['schedule','时段'],['history','操作记录']];
function semPartition(rows,labels,weights){return labels.map((label,i)=>({label,cost:rows.reduce((n,r)=>n+semSplit(Math.round(r.cost*100),weights)[i]/100,0),clicks:rows.reduce((n,r)=>n+semSplit(r.clicks,weights)[i],0),conversions:rows.reduce((n,r)=>n+semSplit(r.conversions,weights)[i],0)}));}
function semDepthBars(rows){const max=Math.max(1,...rows.map(r=>r.cost));return `<div class="sem-depth-bars">${rows.map(r=>`<div><span>${esc(r.label)}</span><strong>${money(r.cost)}</strong><i style="--share:${r.cost/max*100}%"></i><small>${r.clicks} 点击 · ${r.conversions} 次报表转化</small></div>`).join('')}</div>`;}
function semDepthBody(){const {id,scope,tab}=semDepth,rows=semDepthRows(scope,id),r=semDepthKeywords(scope).find(r=>r.id===id);if(!r)return '<p>当前范围无记录。</p>';
  if(tab==='summary')return `<h3>逐日花费</h3>${semDepthBars(rows.map(x=>({...x,label:x.date})))}<details class="sem-source"><summary>查看 ${rows.length} 条来源记录</summary><div>${rows.map(x=>`<button data-sem-source="${x.sourceId}">${x.sourceId} · ${x.date} ↗</button>`).join('')}</div><p>来源记录为主题总量；该关键词占其中一部分，三词合计还原原记录。</p></details>`;
  if(tab==='queries')return `<h3>哪些查询触发了这个词</h3>${semDepthBars(semPartition(rows,[r.title,r.topic+'供应商对比'],[.7,.3]))}<p>查询为该关键词内部的互不重复的演示分组，不能与关键词金额重复相加。</p>`;
  if(tab==='device')return `<h3>实际采用的演示终端</h3>${semDepthBars([{label:r.device,cost:r.cost,clicks:r.clicks,conversions:r.conversions}])}<p>继承来源计划的终端，不虚构另一终端的表现。该演示范围只有一种终端。</p>`;
  if(tab==='region')return `<h3>地域分布</h3>${semDepthBars(semPartition(rows,['华东','华南'],[.6,.4]))}<p>地域拆分是交互演示设定；没有地域质量或成交归因结论。</p>`;
  if(tab==='schedule')return `<h3>时段分布</h3>${semDepthBars(semPartition(rows,['00:00–08:00','08:00–16:00','16:00–24:00'],[.2,.5,.3]))}<p>时段采用演示分配，不据此自动调整排期或出价。</p>`;
  return `<h3>操作与效果分开记录</h3><div class="sem-operation"><span>流程示意 · 非该词真实历史</span><b>09.02 · 出价调整 ¥8.00 → ¥8.50</b><p>操作结果记录：模拟成功　效果核实：尚无可比结论</p></div><div class="sem-operation"><span>流程示意</span><b>09.04 · 匹配方式核查</b><p>仅形成核查草稿，未向投放平台提交变更。</p></div><p>以上记录只演示状态层级，不用于解释上方趋势。</p>`;
}
function semDepthOpen(id,scope=pSnapshot(),tab='summary'){semDepth={id,scope:{topic:scope.topic,start:scope.start,end:scope.end},tab};const r=semDepthKeywords(scope).find(r=>r.id===id);if(!r)return;showDialog('广告投放 / 关键词详情',`<div class="sem-depth"><div class="sem-depth-heading"><span>演示拆分 · ${id}</span><h2>${esc(r.title)}</h2><p>${pScope(scope)} · ${esc(r.plan)} · 保留打开时的日期范围</p></div><div class="sem-depth-kpis">${[['花费',money(r.cost)],['点击',num(r.clicks)],['报表转化',r.conversions],['报表转化成本',r.conversions?money(r.cost/r.conversions):'—']].map(([k,v])=>`<div><small>${k}</small><b>${v}</b></div>`).join('')}</div><p class="sem-fixture-note">广告平台记录的“转化”可能包括提交表单等行为，仍需确认是否为真实有效的客户咨询；这里的成本不是实际获客成本。</p><div class="sem-depth-tabs" role="tablist" aria-label="关键词分析维度">${semDepthTabs.map(([k,l])=>`<button role="tab" id="sem-tab-${k}" aria-controls="sem-depth-panel" aria-selected="${tab===k}" tabindex="${tab===k?0:-1}" data-sem-tab="${k}">${l}</button>`).join('')}</div><section id="sem-depth-panel" role="tabpanel" aria-labelledby="sem-tab-${tab}">${semDepthBody()}</section><div class="sem-depth-actions"><button data-sem-discuss>带着这个词继续讨论</button><button data-sem-plan>安排核实</button></div></div>`);}
function semDepthChange(tab){semDepth.tab=tab;$('#sem-depth-panel').innerHTML=semDepthBody();$('#sem-depth-panel').setAttribute('aria-labelledby','sem-tab-'+tab);$$('[data-sem-tab]').forEach(b=>{b.setAttribute('aria-selected',String(b.dataset.semTab===tab));b.tabIndex=b.dataset.semTab===tab?0:-1;});}
window.addEventListener('keydown',e=>{const b=e.target.closest('[data-sem-tab]');if(!b||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const index=semDepthTabs.findIndex(([key])=>key===b.dataset.semTab);const next=e.key==='Home'?0:e.key==='End'?5:(index+(e.key==='ArrowRight'?1:5))%6;semDepthChange(semDepthTabs[next][0]);$('#sem-tab-'+semDepthTabs[next][0]).focus();});
window.addEventListener('click',e=>{const b=e.target.closest('[data-sem-keyword],[data-sem-tab],[data-sem-source],[data-sem-return],[data-sem-discuss],[data-sem-plan]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();
 if(b.dataset.semKeyword){semDepthOpen(b.dataset.semKeyword,JSON.parse(b.dataset.semScope));return;}
 if(b.dataset.semTab){semDepthChange(b.dataset.semTab);return;}
 if(b.dataset.semSource){pObject(b.dataset.semSource);$('#dialogBody').insertAdjacentHTML('beforeend','<button class="secondary-button" data-sem-return>返回关键词分析</button>');return;}
 if(b.hasAttribute('data-sem-return')){semDepthOpen(semDepth.id,semDepth.scope,semDepth.tab);return;}
 const {id,scope}=semDepth,r=semDepthKeywords(scope).find(x=>x.id===id);closeDialog();
 if(b.hasAttribute('data-sem-discuss')){showChat();addMessage('user',`查看关键词 ${r.title} 的表现`);addMessage('assistant',`<p><strong>${esc(r.title)}</strong> · ${pScope(scope)}</p><p>演示拆分花费 <strong>${money(r.cost)}</strong>，${r.clicks} 次点击、${r.conversions} 次报表转化。先核实转化业务有效性，再讨论预算。</p><p>查询、地域和时段用于展示深入分析流程，尚未接入真实词报表；操作示意不能证明趋势变化的原因。</p><button class="secondary-button" data-sem-keyword="${id}" data-sem-scope="${esc(JSON.stringify(scope))}">返回这个关键词</button>`);return;}
 pChange(scope);pPlan('verify',id);const form=$('#pPlanForm');form.elements.title.value='核实关键词：'+r.title;form.elements.note.value=`关键词 ${id} / ${r.title}，${pScope(scope)}。核实报表转化的有效性、重复记录及来源覆盖。当前数字是原型拆分示例。`;form.elements.criterion.value='每条可追踪转化有核实结论与依据；无法确认的保留待补充依据，不要求虚构获客效果。';
},true);
const semDepthTalk=pTalk;pTalk=function(key,question='',scope=pSnapshot()){
 if(key!=='semkeywords')return semDepthTalk(key,question,scope);
 if(question)addMessage('user',question);showChat();const rows=semDepthKeywords(scope),top=rows[0];
 addMessage('assistant',`<p><strong>${pScope(scope)} · ${rows.length} 个广告关键词</strong></p><p>合计花费 ${money(pSum(rows,'cost'))}，${pSum(rows,'clicks')} 次点击，${pSum(rows,'conversions')} 次报表转化。${top?`花费最高的是 ${esc(top.title)}：${money(top.cost)}。`:''}</p><p>这是从主题投放总量拆出的演示词报表。先选一个词查看查询与转化依据，再安排核实。</p>${rows.slice(0,3).map(r=>`<button class="secondary-button" data-sem-keyword="${r.id}" data-sem-scope="${esc(JSON.stringify(scope))}">${esc(r.title)} ↗</button>`).join('')}`);
 pano.focus=key;pContext();
};
renderPanorama();
