/* Role-play only. Workflow is nested in local drafts, never sent to a module. */
const handoffLabels={active:'负责人处理中',waiting:'等客户补充信息',review:'等客户检查结果',done:'客户已确认工作完成'};
function handoffActions(w){if(!w)return [['assign','交给负责人（模拟）']];if(w.stage==='done')return [];if(w.stage==='review')return [['accept','确认工作完成（模拟）'],['return','退回继续处理']];if(w.stage==='waiting')return [['supply','补充信息并继续']];return [['progress','更新处理进度'],['ask','请客户补充信息'],['result','提交处理结果']];}
const handoffTask=showTask;showTask=function(id){handoffTask(id);const t=localDrafts.find(x=>x.id===id);if(!t)return;const w=t.handoff;const panel=document.createElement('section');panel.className='task-handoff';panel.innerHTML=`<h3>负责人接手后的流程 · 模拟</h3><p>只在当前标签页扮演负责人和客户，不发送通知、不执行真实业务。</p>${w?`<div class="handoff-state"><b>${handoffLabels[w.stage]}</b><span>负责人：${esc(w.owner)} · 约定检查：${esc(w.due)}</span><span>推广效果：尚未确认</span></div><ol>${w.events.map(e=>`<li><small>${esc(e.time)} · ${esc(e.actor)}</small><b>${esc(e.label)}</b><p>${esc(e.note)}</p></li>`).join('')}</ol>`:'<p>先确认交给谁、何时检查，再模拟处理和客户反馈。</p>'}${t.status==='cancelled'?'<p>方案已撤回，不能继续推进。恢复方案后可继续。</p>':`<div class="seo-actions">${handoffActions(w).map(([k,l])=>`<button data-handoff-task="${id}" data-handoff-action="${k}">${l}</button>`).join('')}</div>`}`;$('#dialogBody').append(panel);if(w)$('#dialogBody .guide-status')?.remove();};
const handoffRender=renderTasks;renderTasks=function(){handoffRender();$('#taskList').querySelectorAll('[data-task]').forEach(b=>{const w=localDrafts.find(t=>t.id===b.dataset.task)?.handoff;if(w)b.querySelector('.task-right')?.insertAdjacentHTML('beforeend',`<small>流程模拟：${handoffLabels[w.stage]}</small>`);});};
function handoffForm(id,action){const t=localDrafts.find(x=>x.id===id);if(!t||t.status==='cancelled'||!handoffActions(t.handoff).some(([k])=>k===action))return;const label=handoffActions(t.handoff).find(([k])=>k===action)[1];showDialog('待办流程 / 本地模拟',`<h2>${label}</h2><p>${esc(t.title)}</p><p>此操作只记录演示状态，不向负责人发送消息。</p><form id="handoffForm" data-task-id="${id}" data-step="${action}">${action==='assign'?`<label>负责人<input name="owner" required maxlength="60" value="${esc(t.owner)}"></label><label>约定检查日期<input name="due" required type="date" value="${esc(t.due)}"></label>`:''}<label>${action==='result'?'完成了什么？检查依据是什么？':action==='return'?'哪里还没做好？请说明需要继续处理什么。':action==='accept'?'确认哪些工作已达到要求？':action==='ask'?'需要客户补充什么？':'说明'}<textarea name="note" required maxlength="1200" rows="4"></textarea></label><p>工作完成不代表咨询量或成交已经增长。</p><div class="seo-actions"><button type="submit">确认记录（模拟）</button><button type="button" data-handoff-back="${id}">返回，不作修改</button></div></form>`);}
window.addEventListener('click',e=>{const b=e.target.closest('[data-handoff-task],[data-handoff-back]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(b.dataset.handoffBack)showTask(b.dataset.handoffBack);else handoffForm(b.dataset.handoffTask,b.dataset.handoffAction);},true);
document.addEventListener('submit',e=>{if(e.target.id!=='handoffForm')return;e.preventDefault();const f=e.target,t=localDrafts.find(x=>x.id===f.dataset.taskId),a=f.dataset.step;if(!t||t.status==='cancelled'||!handoffActions(t.handoff).some(([k])=>k===a)||!f.reportValidity())return;const values=Object.fromEntries(new FormData(f)),note=values.note.trim();if(!note||a==='assign'&&!values.owner.trim()){toast('请补充完整说明与负责人。');return;}const old=t.handoff,w=old?JSON.parse(JSON.stringify(old)):{owner:values.owner.trim(),due:values.due,events:[]};w.stage=({assign:'active',progress:'active',ask:'waiting',supply:'active',result:'review',return:'active',accept:'done'})[a];w.events.push({time:new Date().toLocaleString('zh-CN'),actor:['supply','return','accept','assign'].includes(a)?'客户（模拟）':'负责人（模拟）',label:handoffActions(old).find(([k])=>k===a)[1],note});t.handoff=w;persist();renderTasks();showTask(t.id);});
renderTasks();
