<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { fetchSeoAlerts } from '../../api/seo'
import { currentTenantId } from '../../store/session'
import './seo-suite.css'
const loading=ref(false),error=ref(''),engine=ref('baidu'),severity=ref('');const data=ref({items:[],total:0,high:0})
const items=computed(()=>severity.value?data.value.items.filter(i=>i.severity===severity.value):data.value.items)
const labels={rank_drop:'排名骤降',missing_landing:'缺少承接页',site_issue:'站内问题',toxic_backlink:'风险外链'}
async function load(){if(!currentTenantId.value){error.value='请先选择客户';return}loading.value=true;error.value='';try{data.value=await fetchSeoAlerts({tenantId:currentTenantId.value,engine:engine.value})}catch(e){error.value=e.message}finally{loading.value=false}}
watch([engine,currentTenantId],load);onMounted(load)
</script>
<template><div class="seo-suite" v-loading="loading"><section class="suite-hero"><div><span class="eyebrow">SEO EARLY WARNING</span><h1>异常提醒</h1><p>自动聚合排名下降、缺少承接页、站内技术问题与高风险外链，按严重程度进入处理队列。</p></div></section><el-alert v-if="error" class="suite-error" :title="error" type="warning" :closable="false"/><section class="suite-metrics"><article><span>当前异常</span><strong>{{data.total}}</strong><small>由实时资产规则生成</small></article><article><span>高优先级</span><strong>{{data.high}}</strong><small>建议当日处理</small></article><article><span>排名引擎</span><strong>{{engine.toUpperCase()}}</strong><small>可切换排名口径</small></article><article><span>待处理类型</span><strong>{{new Set(data.items.map(i=>i.type)).size}}</strong><small>排名 / 页面 / 外链</small></article></section><section class="suite-panel"><header><div><span class="panel-kicker">01 / ALERT QUEUE</span><h2>异常处理队列</h2></div><div class="switch"><button v-for="e in ['baidu','bing','360','sogou','google']" :key="e" :class="{active:engine===e}" @click="engine=e">{{e}}</button></div></header><div class="suite-toolbar"><el-select v-model="severity" clearable placeholder="全部级别"><el-option label="高优先级" value="high"/><el-option label="普通" value="medium"/></el-select><span>{{items.length}} 条</span></div><ul v-if="items.length" class="suite-list"><li v-for="item in items" :key="`${item.type}-${item.object_id}`"><span class="suite-pill" :class="item.severity==='high'?'danger':'warn'">{{item.severity==='high'?'P0':'P1'}}</span><div class="grow"><b>{{item.title}}</b><small>{{item.detail}} · {{labels[item.type]}}</small></div><time>{{item.occurred_at?new Date(item.occurred_at).toLocaleString():'—'}}</time></li></ul><div v-else class="suite-empty">当前没有异常</div></section></div></template>
<style scoped>.switch{display:flex;gap:4px}.switch button{padding:5px 8px;border:1px solid #e0e5ed;background:#fff;color:#778197;cursor:pointer}.switch button.active{color:#2658d7;border-color:#9fb3e7}.suite-toolbar>span{align-self:center;margin-left:auto;color:#748097;font-size:11px}time{color:#8993a5;font-size:10px;white-space:nowrap}</style>
