<script setup>
import { computed,onMounted,reactive,ref,watch } from 'vue'
import { ElMessage } from 'element-plus'
import { createSeoBacklink,crawlSeoInternalLinks,fetchSeoBacklinks,fetchSeoInternalLinks } from '../../api/seo'
import { currentTenantId,session } from '../../store/session'
import './seo-suite.css'
const tab=ref('internal'),loading=ref(false),error=ref(''),graph=ref({nodes:[],edges:[],stats:{}}),backlinks=ref({items:[],stats:{}}),dialog=ref(false),saving=ref(false),crawling=ref(null)
const form=reactive({source_url:'',target_url:'',anchor_text:'',authority_score:null,toxic_score:null,status:'active'});const canEdit=computed(()=>!session.isLoggedIn||session.canEdit('seo.links'))
async function load(){if(!currentTenantId.value){error.value='请先选择客户';return}loading.value=true;try{[graph.value,backlinks.value]=await Promise.all([fetchSeoInternalLinks({tenantId:currentTenantId.value}),fetchSeoBacklinks({tenantId:currentTenantId.value})]);error.value=''}catch(e){error.value=e.message}finally{loading.value=false}}
async function crawl(node){crawling.value=node.id;try{const r=await crawlSeoInternalLinks({tenantId:currentTenantId.value,pageId:node.id});ElMessage.success(`已发现 ${r.discovered} 个站内链接`);await load()}catch(e){ElMessage.error(e.message)}finally{crawling.value=null}}
async function save(){saving.value=true;try{await createSeoBacklink({tenant_id:currentTenantId.value,...form,anchor_text:form.anchor_text||null});dialog.value=false;Object.assign(form,{source_url:'',target_url:'',anchor_text:'',authority_score:null,toxic_score:null,status:'active'});ElMessage.success('外链已加入资产库');await load()}catch(e){ElMessage.error(e.message)}finally{saving.value=false}}
watch(currentTenantId,load);onMounted(load)
</script>
<template><div class="seo-suite" v-loading="loading"><section class="suite-hero"><div><span class="eyebrow">LINK INTELLIGENCE</span><h1>内外链管理</h1><p>用站内链接图发现孤立页面，同时维护外部链接来源、权威度与风险评分。</p></div><button v-if="canEdit&&tab==='backlink'" class="suite-primary" @click="dialog=true">＋ 录入外链</button></section><el-alert v-if="error" class="suite-error" :title="error" type="warning" :closable="false"/><section class="tabs"><button :class="{active:tab==='internal'}" @click="tab='internal'">内链图谱</button><button :class="{active:tab==='backlink'}" @click="tab='backlink'">外链资产</button></section>
<template v-if="tab==='internal'"><section class="suite-metrics"><article><span>站内页面</span><strong>{{graph.stats.pages||0}}</strong><small>已纳入图谱</small></article><article><span>链接边</span><strong>{{graph.stats.links||0}}</strong><small>页面之间的真实链接</small></article><article><span>孤立页面</span><strong>{{graph.stats.orphans||0}}</strong><small>没有任何内链指向</small></article><article><span>覆盖率</span><strong>{{graph.stats.pages?Math.round((graph.stats.pages-graph.stats.orphans)/graph.stats.pages*100):0}}%</strong><small>有入链页面占比</small></article></section><section class="suite-panel"><header><div><span class="panel-kicker">01 / INTERNAL GRAPH</span><h2>页面链接关系</h2></div><small>逐页抓取公开 HTML 后生成</small></header><el-table :data="graph.nodes" empty-text="请先在站内优化导入页面"><el-table-column label="页面" min-width="300"><template #default="{row}"><b>{{row.title||'未读取标题'}}</b><small class="url">{{row.url}}</small></template></el-table-column><el-table-column prop="page_type" label="类型" width="110"/><el-table-column prop="incoming" label="入链" width="80"/><el-table-column prop="outgoing" label="出链" width="80"/><el-table-column label="状态" width="100"><template #default="{row}"><span class="suite-pill" :class="row.orphan?'danger':''">{{row.orphan?'孤立':'已连接'}}</span></template></el-table-column><el-table-column label="操作" width="100"><template #default="{row}"><div class="suite-actions"><button v-if="canEdit" :disabled="crawling===row.id" @click="crawl(row)">{{crawling===row.id?'抓取中':'抓取链接'}}</button></div></template></el-table-column></el-table></section></template>
<template v-else><section class="suite-metrics"><article><span>有效外链</span><strong>{{backlinks.stats.active||0}}</strong><small>当前仍可访问</small></article><article><span>来源域名</span><strong>{{backlinks.stats.domains||0}}</strong><small>去重后的引荐域</small></article><article><span>丢失外链</span><strong>{{backlinks.stats.lost||0}}</strong><small>需联系恢复</small></article><article><span>风险外链</span><strong>{{backlinks.stats.toxic||0}}</strong><small>风险评分 ≥ 70</small></article></section><section class="suite-panel"><header><div><span class="panel-kicker">02 / BACKLINK ASSETS</span><h2>外部链接清单</h2></div></header><el-table :data="backlinks.items" empty-text="暂无外链资产"><el-table-column prop="source_domain" label="来源域名" min-width="150"/><el-table-column prop="source_url" label="来源页面" min-width="240" show-overflow-tooltip/><el-table-column prop="target_url" label="目标页面" min-width="220" show-overflow-tooltip/><el-table-column prop="anchor_text" label="锚文本" width="130"/><el-table-column prop="authority_score" label="权威度" width="90"/><el-table-column label="风险" width="90"><template #default="{row}"><span class="suite-pill" :class="row.toxic_score>=70?'danger':''">{{row.toxic_score??'—'}}</span></template></el-table-column><el-table-column prop="status" label="状态" width="90"/></el-table></section></template>
<el-dialog v-model="dialog" title="录入外链资产" width="650px"><el-form label-position="top" class="suite-form"><el-form-item label="来源页面 URL" class="full"><el-input v-model="form.source_url"/></el-form-item><el-form-item label="目标页面 URL" class="full"><el-input v-model="form.target_url"/></el-form-item><el-form-item label="锚文本"><el-input v-model="form.anchor_text"/></el-form-item><el-form-item label="状态"><el-select v-model="form.status"><el-option label="有效" value="active"/><el-option label="丢失" value="lost"/><el-option label="拒绝" value="disavow"/></el-select></el-form-item><el-form-item label="权威度"><el-input-number v-model="form.authority_score" :min="0" :max="100"/></el-form-item><el-form-item label="风险评分"><el-input-number v-model="form.toxic_score" :min="0" :max="100"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog></div></template>
<style scoped>.tabs{display:flex;gap:8px;margin:15px 0}.tabs button{padding:9px 16px;border:1px solid #dde4ef;border-radius:9px;background:#fff;color:#6f7b91;font-weight:700;cursor:pointer}.tabs button.active{border-color:#8da7df;background:#edf3ff;color:#2658d7}.url{display:block;margin-top:4px;color:#748097}.suite-actions button:disabled{opacity:.5}</style>
