<script setup>
import { computed,onMounted,reactive,ref,watch } from 'vue'
import { ElMessage } from 'element-plus'
import { useRoute } from 'vue-router'
import { createSeoBacklink,crawlSeoInternalLinks,fetchSeoBacklinks,fetchSeoInternalLinks } from '../../api/seo'
import { fetchSeoSites } from '../../api/moduleAssets'
import { currentTenantId,session } from '../../store/session'
import { currentSeoSiteId as siteId } from './seoSiteContext'
import { runSeoBatch } from './seoBatchOperations'
import './seo-suite.css'
import SeoBacklinkWorkbench from './SeoBacklinkWorkbench.vue'
const workbench=ref(null)
const route=useRoute()
const tab=ref(route.query.tab==='backlink'?'backlink':'internal'),loading=ref(false),error=ref(''),sites=ref([]),graph=ref({nodes:[],edges:[],stats:{}}),backlinks=ref({items:[],stats:{}}),dialog=ref(false),saving=ref(false),crawling=ref(null),batchCrawling=ref(false),selectedNodes=ref([])
const form=reactive({source_url:'',target_url:'',anchor_text:'',authority_score:null,toxic_score:null,status:'active'});const canEdit=computed(()=>!session.isLoggedIn||session.canEdit('seo.links'))
let loadVersion=0, siteVersion=0
async function load(){const ticket=++loadVersion;graph.value={nodes:[],edges:[],stats:{}};selectedNodes.value=[];dialog.value=false;if(!currentTenantId.value){error.value='请先选择客户';return}if(!siteId.value){error.value='请先选择或创建 SEO 网站';return}loading.value=true;try{const value=await fetchSeoInternalLinks({tenantId:currentTenantId.value,siteId:siteId.value});if(ticket!==loadVersion)return;graph.value=value;error.value=''}catch(e){if(ticket===loadVersion)error.value=e.message}finally{if(ticket===loadVersion)loading.value=false}}

async function crawl(node){if(batchCrawling.value||crawling.value!==null)return ElMessage.warning('内链抓取正在进行，请勿重复提交');crawling.value=node.id;try{const r=await crawlSeoInternalLinks({tenantId:currentTenantId.value,pageId:node.id});ElMessage.success(`已发现 ${r.discovered} 个站内链接`);await load()}catch(e){ElMessage.error(e.message)}finally{crawling.value=null}}
async function crawlSelected(){if(batchCrawling.value||crawling.value!==null)return ElMessage.warning('内链抓取正在进行，请勿重复提交');if(!selectedNodes.value.length)return ElMessage.warning('请先勾选需要抓取内链的页面');batchCrawling.value=true;try{const tenant=currentTenantId.value;const response=await runSeoBatch([...selectedNodes.value],node=>crawlSeoInternalLinks({tenantId:tenant,pageId:node.id}),{concurrency:1,limit:50});const discovered=response.completed.reduce((total,item)=>total+Number(item.value?.discovered||0),0);const message=`批量抓取完成：成功 ${response.completed.length}，失败 ${response.failed.length}，跳过 ${response.skipped.length}，发现链接 ${discovered}`;response.failed.length||response.skipped.length?ElMessage.warning(message):ElMessage.success(message);await load()}catch(e){ElMessage.error(e.message)}finally{batchCrawling.value=false}}
async function save(){saving.value=true;try{await createSeoBacklink({tenant_id:currentTenantId.value,site_id:siteId.value,...form,anchor_text:form.anchor_text||null});dialog.value=false;Object.assign(form,{source_url:'',target_url:'',anchor_text:'',authority_score:null,toxic_score:null,status:'active'});ElMessage.success('外链已加入资产库，等待核验');await workbench.value?.load()}catch(e){ElMessage.error(e.message)}finally{saving.value=false}}
async function loadSites(){const ticket=++siteVersion;loadVersion++;graph.value={nodes:[],edges:[],stats:{}};dialog.value=false;if(!currentTenantId.value){sites.value=[];siteId.value=null;return}try{const value=await fetchSeoSites(currentTenantId.value);if(ticket!==siteVersion)return;sites.value=value.sites||[];const requestedSiteId=Number(route.query.site_id)||null;const nextSiteId=sites.value.some(site=>site.id===requestedSiteId)?requestedSiteId:(sites.value.some(site=>site.id===siteId.value)?siteId.value:(sites.value.find(site=>site.status==='active')?.id||sites.value[0]?.id||null));if(nextSiteId!==siteId.value)siteId.value=nextSiteId;else await load()}catch(e){sites.value=[];siteId.value=null;error.value=e.message}}
watch(siteId,load);watch(currentTenantId,loadSites);watch(()=>route.query.tab,value=>{tab.value=value==='backlink'?'backlink':'internal'});watch(()=>route.query.site_id,loadSites);onMounted(loadSites)
</script>
<template><div class="seo-suite" v-loading="loading"><section class="suite-hero"><div><span class="eyebrow">LINK INTELLIGENCE</span><h1>内外链管理</h1><p>用站内链接图发现孤立页面，并发现、核验和持续监控站外链接。</p></div><div class="link-actions"><el-select v-model="siteId" placeholder="选择 SEO 网站"><el-option v-for="site in sites" :key="site.id" :label="site.name" :value="site.id"/></el-select><button v-if="canEdit&&tab==='internal'" class="suite-primary" :disabled="batchCrawling||crawling!==null||!selectedNodes.length" title="按顺序抓取已选页面，单次最多 50 条" @click="crawlSelected">{{batchCrawling?'批量抓取中…':`批量抓取（已选 ${selectedNodes.length}）`}}</button><button v-if="canEdit&&tab==='backlink'" class="suite-primary" @click="dialog=true">＋ 录入外链</button></div></section><el-alert v-if="error" class="suite-error" :title="error" type="warning" :closable="false"/><section class="tabs"><button :class="{active:tab==='internal'}" @click="tab='internal'">内链图谱</button><button :class="{active:tab==='backlink'}" @click="tab='backlink'">外链资产</button></section>
<template v-if="tab==='internal'"><section class="suite-metrics"><article><span>站内页面</span><strong>{{graph.stats.pages||0}}</strong><small>已纳入图谱</small></article><article><span>链接边</span><strong>{{graph.stats.links||0}}</strong><small>页面之间的真实链接</small></article><article><span>孤立页面</span><strong>{{graph.stats.orphans||0}}</strong><small>没有任何内链指向</small></article><article><span>覆盖率</span><strong>{{graph.stats.pages?Math.round((graph.stats.pages-graph.stats.orphans)/graph.stats.pages*100):0}}%</strong><small>有入链页面占比</small></article></section><section class="suite-panel"><header><div><span class="panel-kicker">01 / INTERNAL GRAPH</span><h2>页面链接关系</h2></div><small>勾选后可顺序抓取最多 50 个公开页面</small></header><el-table :data="graph.nodes" empty-text="请先在站内优化导入页面" @selection-change="selectedNodes=$event"><el-table-column type="selection" width="44"/><el-table-column label="页面" min-width="300"><template #default="{row}"><b>{{row.title||'未读取标题'}}</b><small class="url">{{row.url}}</small></template></el-table-column><el-table-column prop="page_type" label="类型" width="110"/><el-table-column prop="incoming" label="入链" width="80"/><el-table-column prop="outgoing" label="出链" width="80"/><el-table-column label="状态" width="100"><template #default="{row}"><span class="suite-pill" :class="row.orphan?'danger':''">{{row.orphan?'孤立':'已连接'}}</span></template></el-table-column><el-table-column label="操作" width="100"><template #default="{row}"><div class="suite-actions"><button v-if="canEdit" :disabled="batchCrawling||crawling!==null" @click="crawl(row)">{{crawling===row.id?'抓取中':'抓取链接'}}</button></div></template></el-table-column></el-table></section></template>
<SeoBacklinkWorkbench v-else :key="`${session.user?.id}:${currentTenantId}:${siteId}`" ref="workbench" :tenant-id="currentTenantId" :site-id="siteId" :can-edit="canEdit"/>

<el-dialog v-model="dialog" title="录入外链资产" width="650px"><el-form label-position="top" class="suite-form"><el-form-item label="来源页面 URL" class="full"><el-input v-model="form.source_url"/></el-form-item><el-form-item label="目标页面 URL" class="full"><el-input v-model="form.target_url"/></el-form-item><el-form-item label="锚文本"><el-input v-model="form.anchor_text"/></el-form-item><el-form-item label="状态"><el-select v-model="form.status"><el-option label="加入监控（待核验）" value="active"/><el-option label="丢失" value="lost"/><el-option label="停止监控" value="disavow"/></el-select></el-form-item><el-form-item label="权威度"><el-input-number v-model="form.authority_score" :min="0" :max="100"/></el-form-item><el-form-item label="风险评分"><el-input-number v-model="form.toxic_score" :min="0" :max="100"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog></div></template>
<style scoped>.link-actions{display:flex;align-items:center;gap:10px}.link-actions .el-select{width:260px}.tabs{display:flex;gap:8px;margin:15px 0}.tabs button{padding:9px 16px;border:1px solid #dde4ef;border-radius:9px;background:#fff;color:#6f7b91;font-weight:700;cursor:pointer}.tabs button.active{border-color:#8da7df;background:#edf3ff;color:#2658d7}.url{display:block;margin-top:4px;color:#748097}.suite-actions button:disabled{opacity:.5}</style>
